import React,{useEffect,useState} from 'react';
import {Alert,StyleSheet,Text,View} from 'react-native';
import {DESIGN_TOKENS,NATIVE_AUTH_BOUNDARY} from '@sessions/product-core';
import {Body,Card,Eyebrow,Notice,PrimaryButton,Screen,SecondaryButton,Section,Small,Title} from '../src/native-ui';
import {clearNativeSession,readNativeSessionMeta} from '../src/session-store';

const c=DESIGN_TOKENS.color;
export default function SecurityScreen(){const[meta,setMeta]=useState(null);useEffect(()=>{readNativeSessionMeta().then(setMeta)},[]);const blocked=label=>Alert.alert(`${label} requires production identity`,'Recovery may restore the same identity but can never manufacture provider or corporate authority. The real Sessions Supabase environment must be certified first.');return <Screen><Eyebrow>PHASE 4.5 · ACCOUNT SECURITY</Eyebrow><Title>Recovery restores identity, not privilege.</Title><Body style={{marginTop:8}}>Sessions keeps device/session posture separate from organizational roles. Native secrets belong in encrypted device storage, not D1/R2 or browser cookies.</Body><Section eyebrow="CURRENT DEVICE" title="Session posture"><Card><View style={styles.row}><View style={{flex:1}}><Text style={styles.label}>{meta?'Verified native session metadata':'No certified native session'}</Text><Small>{meta?`Provider: ${meta.provider} · expires ${meta.expiresAt||'unknown'}`:`Boundary: ${NATIVE_AUTH_BOUNDARY.status}`}</Small></View><Text style={[styles.dot,meta&&styles.dotActive]}>●</Text></View>{meta?<View style={{marginTop:12}}><SecondaryButton onPress={async()=>{await clearNativeSession();setMeta(null)}}>Sign out this device</SecondaryButton></View>:null}</Card></Section><Section eyebrow="RECOVERY" title="Verification first"><Card><Body>Recover phone/email access → verify the same Supabase identity → re-derive personal/provider/corporate contexts server-side. No role is restored from a local profile field.</Body><View style={{marginTop:12}}><PrimaryButton onPress={()=>blocked('Account recovery')}>Start recovery</PrimaryButton></View></Card></Section><Section eyebrow="DEVICE SESSIONS" title="See and revoke"><Card><Body>Production will list active Sessions devices and allow revocation. Privileged corporate elevation remains session-bound and requires its own security posture.</Body><View style={{marginTop:12}}><SecondaryButton onPress={()=>blocked('Device session management')}>Manage devices</SecondaryButton></View></Card></Section><Notice>SecureStore is reserved for verified native session material. This build refuses to persist a token while the native auth boundary is blocked.</Notice></Screen>}
const styles=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:12},label:{fontSize:15,fontWeight:'850',color:c.ink,marginBottom:3},dot:{fontSize:18,color:c.subtle},dotActive:{color:c.success}});
