-- Correct SQLite expression syntax for the indexes generated by drizzle-kit.
CREATE UNIQUE INDEX `pending_registration_name` ON `studio_registrations` (lower(trim(json_extract(content, '$.name')))) WHERE status = 'pending';
--> statement-breakpoint
CREATE UNIQUE INDEX `studio_name_unique` ON `studio_registry` (lower(trim(json_extract(content, '$.name'))));
