import {getProductionUser} from '@/app/chatgpt-auth';
import {database} from '@/db/store';
import {isRegistryUserOperator} from '@/db/registry-store';
import {hasPermission} from '@/lib/access-control';
import {settlementCsv,settlementPdf,type SettlementExportLine} from '@/lib/settlement-documents';
import type {Studio,StudioBooking,StudioInvoice,StudioSettlement} from '@/lib/registry';

const monthPattern=/^\d{4}-(0[1-9]|1[0-2])$/;
const safeName=(value:string)=>value.replace(/[^a-z0-9-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase().slice(0,60)||'studio';

export async function GET(request:Request){
 try{
  const user=await getProductionUser();if(!user)return Response.json({error:'Sign in to export statements'},{status:401});const url=new URL(request.url),studioId=url.searchParams.get('studio')||'',period=url.searchParams.get('month')||'',format=url.searchParams.get('format')||'csv';if(!/^[a-zA-Z0-9-]{1,100}$/.test(studioId)||!monthPattern.test(period)||!['csv','pdf'].includes(format))return Response.json({error:'Invalid export request'},{status:400});
  const db=database(),studioRow=await db.prepare('SELECT owner,content FROM studio_registry WHERE id=?').bind(studioId).first();if(!studioRow)return Response.json({error:'Studio not found'},{status:404});const finance=hasPermission(user,'settlements:review'),operator=isRegistryUserOperator(user),identity=user.memberships.find(value=>value.organizationId===studioId&&value.active),legacy=user.method==='chatgpt_demo';const contacts=[user.email?.toLowerCase(),user.phone].filter(Boolean);const staff=contacts.length?await db.prepare("SELECT role FROM studio_staff WHERE studio_id=? AND email IN (?,?) AND status='active'").bind(studioId,contacts[0]||'',contacts[1]||'').first():null;const owner=studioRow.owner===user.id&&(legacy||identity?.role==='owner'),manager=staff?.role==='manager'&&(legacy||identity?.role==='manager'||identity?.role==='staff'||identity?.role==='owner');if(!finance&&!operator&&!owner&&!manager)return Response.json({error:'Studio statement access required'},{status:403});
  const settlementRows=(await db.prepare("SELECT content FROM studio_settlements WHERE studio_id=? AND settled_month=? AND status='settled_off_platform' ORDER BY settled_at").bind(studioId,period).all()).results;const settlements:StudioSettlement[]=settlementRows.map((row:any)=>JSON.parse(row.content) as StudioSettlement);const bookingRows:StudioBooking[]=(await db.prepare("SELECT content FROM studio_bookings WHERE studio_id=?").bind(studioId).all()).results.map((row:any)=>JSON.parse(row.content) as StudioBooking);const bookings=new Map<string,StudioBooking>(bookingRows.map((booking:StudioBooking)=>[booking.id,booking]));const invoiceRow=await db.prepare('SELECT content FROM studio_invoices WHERE studio_id=? AND period=?').bind(studioId,period).first();const invoice:StudioInvoice|null=invoiceRow?JSON.parse(invoiceRow.content):null;const included=invoice?new Set(invoice.settlementIds):null;const lines:SettlementExportLine[]=settlements.filter((settlement:StudioSettlement)=>!included||included.has(settlement.id)).map((settlement:StudioSettlement)=>({settlement,booking:bookings.get(settlement.bookingId)||null}));const studio:Studio=JSON.parse(studioRow.content);const filename=`sessions-${safeName(studio.name)}-${period}.${format}`;
  if(format==='pdf')return new Response(settlementPdf(studio.name,period,invoice,lines),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${filename}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
  return new Response(settlementCsv(studio.name,period,invoice,lines),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${filename}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
 }catch(error){console.error('Statement export failed',error instanceof Error?error.message:'Unknown error');return Response.json({error:'Statement export is temporarily unavailable'},{status:503})}
}
