import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const temp=mkdtempSync(join(tmpdir(),'sessions-test-'));
const sql=new DatabaseSync(':memory:');
for(const file of ['0000_premium_charles_xavier.sql','0001_violet_angel.sql'])sql.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(query){this.query=query;this.params=[]}bind(...params){this.params=params;return this}async first(){return sql.prepare(this.query).get(...this.params)??null}async all(){return {results:sql.prepare(this.query).all(...this.params)}}async run(){return sql.prepare(this.query).run(...this.params)}}
const db={prepare:q=>new Statement(q),async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(sql.prepare(s.query).run(...s.params));sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__sessionsTest={db,user:{email:'musician-a@example.test',displayName:'Test Musician'}};
const authFixture=`
export const getChatGPTUser=async()=>globalThis.__sessionsTest.user;
export const getProductionUser=async()=>{const user=globalThis.__sessionsTest.user;return user?{id:user.email.toLowerCase(),displayName:user.displayName,email:user.email.toLowerCase(),phone:null,roles:['musician'],scopedRoles:[],memberships:[],method:'chatgpt_demo',sessionId:'test-session',assuranceLevel:null}:null};
`;
const plugin={name:'test-boundaries',setup(b){b.onResolve({filter:/cloudflare:workers/},()=>({path:'runtime',namespace:'fixture'}));b.onResolve({filter:/chatgpt-auth/},()=>({path:'auth',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='auth'?authFixture:'export const env={DB:globalThis.__sessionsTest.db};',loader:'js'}))}};
for(const [name,entry]of [['route','app/api/action/route.ts'],['domain','lib/domain.ts'],['state','app/api/state/route.ts']]){await build({entryPoints:[resolve(entry)],bundle:true,platform:'node',format:'esm',outfile:join(temp,name+'.mjs'),plugins:[plugin],logLevel:'silent'})}
const {POST}=await import(pathToFileURL(join(temp,'route.mjs')));const {GET}=await import(pathToFileURL(join(temp,'state.mjs')));const d=await import(pathToFileURL(join(temp,'domain.mjs')));
async function action(payload){const response=await POST(new Request('https://sessions.test/api/action',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://sessions.test'},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}}
const date=d.addDays(d.localDate(),14);let booked;
const base=()=>({type:'book',roomId:'the-live-room',date,start:600,duration:60,weeks:1,groupName:'The Test Band',groupSize:4,key:crypto.randomUUID()});
test('inventory rejects invalid duration, institutional hours and the past',()=>{const studio=d.seedRooms[0],church=d.seedRooms[2];assert.match(d.slotReason(studio,date,600,15,[],[]),/Minimum/);assert.match(d.slotReason(studio,'2001-01-01',600,60,[],[]),/passed/);const sunday='2026-09-06';assert.match(d.slotReason(church,sunday,600,60,[],[],new Date('2026-09-01').getTime()),/Outside/);assert.equal(d.slotReason(studio,date,600,60,[],[]),null)});
test('fee is configurable and deposit is separate from provider subtotal',()=>{const q=d.quote({...d.seedRooms[0],deposit:500},90,1250);assert.deepEqual(q,{subtotal:2700,fee:338,deposit:500,total:3538});assert.equal(d.quote(d.seedRooms[0],60,0).fee,0)});
test('natural-language constraints become editable structured filters',()=>{const p=d.parseSearch('Four-piece gospel band Saturday afternoon near Borrowdale, drums and PA under US$25.');assert.equal(p.capacity,4);assert.equal(p.area,'Borrowdale');assert.equal(p.time,'afternoon');assert.equal(p.budget,25);assert.deepEqual(p.equipment,['Drum kit','PA system'])});
test('missing identity cannot create reservations',async()=>{const previous=globalThis.__sessionsTest.user;globalThis.__sessionsTest.user=null;const r=await action(base());assert.equal(r.status,401);globalThis.__sessionsTest.user=previous});
test('state persists seeded inventory for the authenticated workspace',async()=>{const state=await(await GET()).json();assert.equal(state.rooms.length,10);assert.equal(state.bookings.length,0)});
test('cross-origin mutations are rejected',async()=>{const res=await POST(new Request('https://sessions.test/api/action',{method:'POST',headers:{Origin:'https://hostile.test'},body:JSON.stringify(base())}));assert.equal(res.status,403)});
test('declined demo payment leaves no booking or inventory claim',async()=>{const r=await action({...base(),simulateFailure:true});assert.equal(r.status,402);assert.equal(sql.prepare('SELECT count(*) n FROM bookings').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM slot_claims').get().n,0)});
test('booking is server-priced, durable and idempotent',async()=>{const request=base();const r=await action({...request,total:1});assert.equal(r.status,200);assert.equal(r.booking.total,1980);assert.equal(r.booking.status,'confirmed');booked=r.booking;const again=await action(request);assert.equal(again.booking.id,booked.id);assert.equal(sql.prepare('SELECT count(*) n FROM bookings').get().n,1);assert.equal((await(await GET()).json()).bookings[0].id,booked.id)});
test('double booking and the reset buffer cannot overlap',async()=>{assert.equal((await action(base())).status,409);assert.equal((await action({...base(),start:660})).status,409);assert.equal((await action({...base(),start:690})).status,200)});
test('reviews require a completed booking',async()=>{const r=await action({type:'review',id:booked.id,review:{rating:5,text:'Clear and balanced sound.'}});assert.equal(r.status,400)});
test('one conflicting recurring week rolls back the whole series',async()=>{const existing=await action({...base(),date:d.addDays(date,7),start:900});assert.equal(existing.status,200);const count=sql.prepare('SELECT count(*) n FROM bookings').get().n;const r=await action({...base(),start:900,weeks:4});assert.equal(r.status,409);assert.equal(sql.prepare('SELECT count(*) n FROM bookings').get().n,count)});
test('concurrent competing reservations commit only one',async()=>{const requests=[{...base(),start:1020},{...base(),start:1020}];const out=await Promise.all(requests.map(action));assert.equal(out.filter(r=>r.status===200).length,1);assert.equal(out.filter(r=>r.status===409).length,1)});
test('manual institutional blocks prevent reservations',async()=>{const r=await action({type:'block',block:{roomId:'the-live-room',date,start:1140,end:1260,reason:'Internal use'}});assert.equal(r.status,200);assert.equal((await action({...base(),start:1140})).status,409)});
test('cancellation records a refund and releases the inventory',async()=>{const r=await action({type:'cancel',id:booked.id});assert.equal(r.status,200);assert.equal(r.booking.refund,r.booking.total);assert.equal(r.booking.payment,'refunded');assert.equal((await action(base())).status,200)});
test('approval-required room authorizes then captures only after approval',async()=>{const room='the-music-hall';let day=d.addDays(d.localDate(),15);while(new Date(day+'T12:00Z').getUTCDay()!==6)day=d.addDays(day,1);const req=await action({...base(),roomId:room,date:day,start:600});assert.equal(req.status,200);assert.equal(req.booking.status,'pending_approval');assert.equal(req.booking.payment,'authorized');const approved=await action({type:'approve',id:req.booking.id});assert.equal(approved.booking.payment,'paid');assert.equal(approved.booking.status,'confirmed')});
test('completed demo sessions support one review with moderation',async()=>{const state=await(await GET()).json();const b=state.bookings.find(b=>b.status==='confirmed');assert.equal((await action({type:'complete',id:b.id})).status,200);const r=await action({type:'review',id:b.id,review:{rating:5,text:'Clear and balanced sound.'}});assert.equal(r.status,200);assert.equal((await action({type:'review',id:b.id,review:{rating:5,text:'Duplicate review.'}})).status,400);assert.equal((await action({type:'moderateReview',id:b.id})).booking.review.hidden,true)});
test('second identity cannot inspect or mutate the first workspace',async()=>{globalThis.__sessionsTest.user={email:'musician-b@example.test',displayName:'Other User'};const state=await(await GET()).json();assert.equal(state.bookings.length,0);assert.equal((await action({type:'cancel',id:booked.id})).status,404);globalThis.__sessionsTest.user={email:'musician-a@example.test',displayName:'Test Musician'}});
test('fee updates leave existing booking receipts unchanged',async()=>{const old=await(await GET()).json();assert.equal((await action({type:'fee',feeBps:0})).status,200);const state=await(await GET()).json();assert.equal(state.feeBps,0);assert.deepEqual(state.bookings.map(b=>b.total),old.bookings.map(b=>b.total));assert.equal((await action({...base(),date:d.addDays(date,2),start:600})).booking.fee,0)});
after(()=>{sql.close();rmSync(temp,{recursive:true,force:true});delete globalThis.__sessionsTest});
