import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';

const temp=mkdtempSync(join(tmpdir(),'sessions-w4-')),sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(file=>file.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(query){this.query=query;this.params=[]}bind(...params){this.params=params;return this}async first(){return sql.prepare(this.query).get(...this.params)??null}async all(){return {results:sql.prepare(this.query).all(...this.params)}}async run(){return sql.prepare(this.query).run(...this.params)}}
const db={prepare:query=>new Statement(query),async batch(statements){sql.exec('BEGIN');try{const result=statements.map(statement=>sql.prepare(statement.query).run(...statement.params));sql.exec('COMMIT');return result}catch(error){sql.exec('ROLLBACK');throw error}}};
globalThis.__w4Test={db,user:null};
const plugin={name:'w4-fixture',setup(builder){builder.onResolve({filter:/cloudflare:workers/},()=>({path:'runtime',namespace:'fixture'}));builder.onResolve({filter:/chatgpt-auth/},()=>({path:'auth',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='auth'?"export const getProductionUser=async()=>{const user=globalThis.__w4Test.user;return user?{id:user.id,displayName:user.id,email:user.email||user.id,phone:null,roles:user.operator?['musician','operations_admin']:['musician'],memberships:[],method:'chatgpt_demo',sessionId:'w4-test'}:null};":`export const env={DB:globalThis.__w4Test.db,SESSIONS_ADMIN_EMAILS:'operator@example.test',EMAIL_PROVIDER_ENABLED:'false'};`,loader:'js'}))}};
await build({entryPoints:{registry:resolve('app/api/registry/route.ts'),communications:resolve('app/api/booking-communications/route.ts'),preferences:resolve('app/api/notification-preferences/route.ts'),calendar:resolve('app/api/bookings/[id]/calendar/route.ts'),offline:resolve('app/api/bookings/offline/route.ts'),reminders:resolve('lib/booking-reminders.ts')},bundle:true,platform:'node',format:'esm',outdir:temp,plugins:[plugin],logLevel:'silent'});
const registry=await import(pathToFileURL(join(temp,'registry.js'))),communications=await import(pathToFileURL(join(temp,'communications.js'))),preferences=await import(pathToFileURL(join(temp,'preferences.js'))),calendar=await import(pathToFileURL(join(temp,'calendar.js'))),offline=await import(pathToFileURL(join(temp,'offline.js'))),reminders=await import(pathToFileURL(join(temp,'reminders.js')));

const studioId='w4-studio',owner='owner@example.test',customer='band@example.test',outsider='outsider@example.test',operator='operator@example.test',bookingId='RS-w4-booking';
const identity=(id,operatorRole=false)=>{globalThis.__w4Test.user=id?{id,email:id,operator:operatorRole}:null};
const registryPost=async payload=>{const response=await registry.POST(new Request('https://sessions.test/api/registry',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://sessions.test'},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}};
const messageGet=async()=>{const response=await communications.GET(new Request(`https://sessions.test/api/booking-communications?booking=${bookingId}&studio=${studioId}`));return {status:response.status,...await response.json()}};
const messagePost=async(payload,origin='https://sessions.test')=>{const response=await communications.POST(new Request('https://sessions.test/api/booking-communications',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}};
const preferencePost=async(payload,origin='https://sessions.test')=>{const response=await preferences.POST(new Request('https://sessions.test/api/notification-preferences',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}};
const studio={id:studioId,name:'W4 Fixture Studio',area:'Harare CBD',address:'Fixture Street, Harare',category:'Rehearsal studio',services:['Rehearsal'],description:'Fixture studio for private booking communication tests.',website:'',phone:'+263000000000',email:'',sources:[],status:'bookable',bookingEnabled:true,rooms:[{id:'room-a',name:'Main room',price:2500,capacity:8,open:0,close:1440,days:[0,1,2,3,4,5,6],buffer:0,minimum:60,photos:[]}],equipment:'',rules:'Fixture terms.',location:{lat:-17.82,lng:31.04},revision:0};
const booking={id:bookingId,studioId,roomId:'room-a',roomName:'Main room',customer,name:'Fixture Band',phone:'+263771111111',date:'2026-09-20',start:600,duration:60,size:4,note:'Private fixture booking note',staffId:'',status:'requested',price:2500,createdAt:'2026-09-01T10:00:00.000Z'};
sql.prepare('INSERT INTO studio_registry(id,owner,revision,content) VALUES(?,?,0,?)').run(studioId,owner,JSON.stringify(studio));
sql.prepare('INSERT INTO studio_bookings(id,studio_id,customer,request_key,content) VALUES(?,?,?,?,?)').run(booking.id,studioId,customer,crypto.randomUUID(),JSON.stringify(booking));

test('confirmation creates an active minimal voucher and in-app notice for each booking side',async()=>{identity(owner);const result=await registryPost({type:'bookingStatus',studioId,id:bookingId,status:'confirmed'});assert.equal(result.status,200);const voucher=sql.prepare('SELECT token,status,content FROM booking_vouchers WHERE booking_id=?').get(bookingId);assert.equal(voucher.status,'active');assert.match(voucher.token,/^[0-9a-f-]{36}$/);assert.ok(!voucher.content.includes(booking.phone));assert.equal(sql.prepare("SELECT count(*) n FROM booking_notifications WHERE booking_id=? AND kind='booking_confirmed' AND channel='in_app'").get(bookingId).n,2)});

test('booking inbox is authenticated, tenant-isolated, idempotent, and auditable without sending WhatsApp',async()=>{identity(null);assert.equal((await messageGet()).status,401);assert.equal((await messagePost({type:'send',bookingId,studioId,key:crypto.randomUUID(),body:'Hello'})).status,401);identity(outsider);assert.equal((await messageGet()).status,403);identity(operator,true);assert.equal((await messageGet()).status,403);identity(customer);assert.equal((await messagePost({type:'send',bookingId,studioId,key:crypto.randomUUID(),body:'Hello from the band'},'https://hostile.test')).status,403);const key=crypto.randomUUID(),sent=await messagePost({type:'send',bookingId,studioId,key,body:'Hello from the band'});assert.equal(sent.status,200);assert.equal(sent.message.sender,customer);assert.equal(sent.message.recipient,`studio:${studioId}`);const duplicate=await messagePost({type:'send',bookingId,studioId,key,body:'Hello from the band'});assert.equal(duplicate.status,200);assert.equal(duplicate.duplicate,true);assert.equal(sql.prepare('SELECT count(*) n FROM booking_messages WHERE booking_id=?').get(bookingId).n,1);assert.equal((await messagePost({type:'markRead',bookingId,studioId})).status,200);const whatsapp=await messagePost({type:'whatsappLink',bookingId,studioId,key:crypto.randomUUID()});assert.equal(whatsapp.status,200);assert.match(whatsapp.href,/^https:\/\/wa\.me\//);assert.equal(sql.prepare("SELECT count(*) n FROM booking_notifications WHERE booking_id=? AND channel='whatsapp' AND status='user_opened'").get(bookingId).n,1);identity(owner);const received=await messageGet();assert.equal(received.status,200);assert.equal(received.messages.length,1);assert.equal((await messagePost({type:'markRead',bookingId,studioId})).status,200)});

test('calendar and offline artifacts reveal only an authenticated participant’s confirmed reference',async()=>{identity(null);assert.equal((await calendar.GET(new Request(`https://sessions.test/api/bookings/${bookingId}/calendar`),{params:Promise.resolve({id:bookingId})})).status,401);identity(outsider);assert.equal((await calendar.GET(new Request(`https://sessions.test/api/bookings/${bookingId}/calendar`),{params:Promise.resolve({id:bookingId})})).status,403);identity(customer);const file=await calendar.GET(new Request(`https://sessions.test/api/bookings/${bookingId}/calendar`),{params:Promise.resolve({id:bookingId})});assert.equal(file.status,200);const ics=await file.text();assert.match(ics,/BEGIN:VCALENDAR/);assert.match(ics,/W4 Fixture Studio/);assert.ok(!ics.includes(booking.phone));assert.ok(!ics.includes(booking.note));const reference=await offline.GET();assert.equal(reference.status,200);const body=await reference.json();assert.equal(body.bookings.length,1);assert.equal(body.bookings[0].id,bookingId);assert.equal(body.bookings[0].voucher.reference.startsWith('SES-'),true);assert.ok(!JSON.stringify(body).includes(booking.phone));assert.ok(!JSON.stringify(body).includes(booking.note))});

test('email preferences require identity, same-origin consent, idempotency, and a current revision',async()=>{identity(null);assert.equal((await preferences.GET()).status,401);assert.equal((await preferencePost({key:crypto.randomUUID(),revision:0,emailConsent:true,reminderConsent:true})).status,401);identity(customer);assert.equal((await preferencePost({key:crypto.randomUUID(),revision:0,emailConsent:true,reminderConsent:true},'https://hostile.test')).status,403);const key=crypto.randomUUID(),saved=await preferencePost({key,revision:0,emailConsent:true,reminderConsent:true});assert.equal(saved.status,200);assert.equal(saved.preference.revision,1);assert.equal((await preferencePost({key,revision:0,emailConsent:true,reminderConsent:true})).duplicate,true);assert.equal((await preferencePost({key:crypto.randomUUID(),revision:0,emailConsent:false,reminderConsent:false})).status,409);assert.equal((await preferences.GET()).status,200)});

test('scheduled reminder contract creates two idempotent in-app notices and never calls an unconfigured email provider',async()=>{const reminderBooking={...booking,id:'RS-w4-reminder',date:'2026-09-10',start:600,status:'confirmed',createdAt:'2026-09-01T10:00:00.000Z'};sql.prepare('INSERT INTO studio_bookings(id,studio_id,customer,request_key,content) VALUES(?,?,?,?,?)').run(reminderBooking.id,studioId,customer,crypto.randomUUID(),JSON.stringify(reminderBooking));const now=new Date('2026-09-09T08:00:00.000Z'),first=await reminders.runBookingReminders(now);assert.equal(first.queued,2);assert.equal(first.delivered,0);assert.equal(first.failed,0);assert.equal(sql.prepare("SELECT count(*) n FROM booking_notifications WHERE booking_id=? AND kind='reminder_24h' AND channel='in_app'").get(reminderBooking.id).n,2);const second=await reminders.runBookingReminders(now);assert.equal(second.queued,0);assert.equal(second.delivered,0);assert.equal(sql.prepare("SELECT count(*) n FROM booking_notifications WHERE booking_id=? AND channel='email'").get(reminderBooking.id).n,0)});

test('cancelling a confirmed booking revokes its public voucher instead of leaving fabricated proof',async()=>{identity(customer);assert.equal((await registryPost({type:'bookingStatus',studioId,id:bookingId,status:'cancelled'})).status,200);const row=sql.prepare('SELECT status,content FROM booking_vouchers WHERE booking_id=?').get(bookingId);assert.equal(row.status,'revoked');assert.equal(JSON.parse(row.content).status,'revoked');assert.equal((await messagePost({type:'whatsappLink',bookingId,studioId,key:crypto.randomUUID()})).status,409)});

after(()=>{sql.close();rmSync(temp,{recursive:true,force:true});delete globalThis.__w4Test});
