import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';

const temp=mkdtempSync(join(tmpdir(),'sessions-commerce-test-')),sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(value=>value.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(query){this.query=query;this.params=[]}bind(...params){this.params=params;return this}async first(){return sql.prepare(this.query).get(...this.params)??null}async all(){return {results:sql.prepare(this.query).all(...this.params)}}async run(){return sql.prepare(this.query).run(...this.params)}}
const db={prepare:query=>new Statement(query),async batch(statements){sql.exec('BEGIN');try{const value=statements.map(statement=>sql.prepare(statement.query).run(...statement.params));sql.exec('COMMIT');return value}catch(error){sql.exec('ROLLBACK');throw error}}};
globalThis.__commerceTest={db,user:null};
const plugin={name:'commerce-fixture',setup(builder){builder.onResolve({filter:/cloudflare:workers/},()=>({path:'runtime',namespace:'fixture'}));builder.onResolve({filter:/chatgpt-auth/},()=>({path:'auth',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='auth'?"export const getProductionUser=async()=>{const u=globalThis.__commerceTest.user;return u?{id:u,email:u,displayName:u,roles:u==='ops@example.test'?['operations_admin']:['musician'],memberships:[],method:'chatgpt_demo'}:null};":"export const env={DB:globalThis.__commerceTest.db,SESSIONS_ADMIN_EMAILS:'ops@example.test'};",loader:'js'}))}};
for(const [name,path] of [['policies','app/api/fee-policies/route.ts'],['quote','lib/booking-quote.ts'],['server','lib/commerce-server.ts']])await build({entryPoints:[resolve(path)],bundle:true,platform:'node',format:'esm',outfile:join(temp,name+'.mjs'),plugins:[plugin],logLevel:'silent'});
const policies=await import(pathToFileURL(join(temp,'policies.mjs'))),quoteLib=await import(pathToFileURL(join(temp,'quote.mjs'))),server=await import(pathToFileURL(join(temp,'server.mjs')));
const identity=user=>{globalThis.__commerceTest.user=user};
const post=async(payload,origin='https://sessions.test')=>{const response=await policies.POST(new Request('https://sessions.test/api/fee-policies',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}};
const create=(overrides={})=>({type:'create',key:crypto.randomUUID(),scope:'global',payer:'studio',musicianBps:0,studioBps:1000,basis:'room_plus_addons',effectiveFrom:'2026-10-01',...overrides});

test('fee policy endpoint rejects missing identity, wrong role and hostile origin',async()=>{identity(null);assert.equal((await post(create())).status,401);identity('musician@example.test');assert.equal((await post(create())).status,403);identity('ops@example.test');assert.equal((await post(create(),'https://hostile.test')).status,403)});
let globalPolicy;
test('Operations creates an idempotent effective-dated policy and overlap is atomic',async()=>{identity('ops@example.test');const request=create();const first=await post(request);assert.equal(first.status,200);globalPolicy=first.policy;assert.equal(first.policy.policy.studioBps,1000);const duplicate=await post(request);assert.equal(duplicate.status,200);assert.equal(duplicate.duplicate,true);assert.equal(sql.prepare('SELECT count(*) n FROM fee_policies').get().n,2);assert.equal((await post(create({effectiveFrom:'2026-10-15'}))).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM fee_policies').get().n,2)});
test('room override wins over global policy and only commissionable add-ons enter the configured basis',async()=>{identity('ops@example.test');const room=await post(create({scope:'room',studioId:'studio-a',roomId:'room-a',payer:'split',musicianBps:500,studioBps:500,basis:'room_plus_addons',effectiveFrom:'2026-11-01'}));assert.equal(room.status,200);const policy=await server.resolveFeePolicy('studio-a','room-a','2026-11-02');assert.equal(policy.id,room.policy.id);const roomModel={id:'room-a',name:'Main',price:2000,capacity:8,open:0,close:1440,days:[0,1,2,3,4,5,6],buffer:0,minimum:60,deposit:500,addOns:[{id:'engineer',name:'Engineer',price:1000,commissionable:true,available:true},{id:'water',name:'Water',price:200,commissionable:false,available:true}]};const quote=quoteLib.quoteRoomBooking(roomModel,60,[{id:'engineer',quantity:2},{id:'water',quantity:1}],policy);assert.equal(quote.pricing.roomSubtotal,2000);assert.equal(quote.pricing.addOnSubtotal,2200);assert.equal(quote.pricing.customerFee,200);assert.equal(quote.pricing.studioFee,200);assert.equal(quote.pricing.customerTotal,4400);assert.equal(quote.pricing.depositDue,500)});
test('quotes reject duplicate or unavailable add-ons and historic policy snapshot is immutable',async()=>{const before=await server.resolveFeePolicy('other','room','2026-10-20');assert.equal(before.id,globalPolicy.id);const room={id:'room',name:'Main',price:2000,capacity:8,open:0,close:1440,days:[0],buffer:0,minimum:60,addOns:[{id:'amp',name:'Amp',price:500,commissionable:true,available:false}]};assert.throws(()=>quoteLib.quoteRoomBooking(room,60,[{id:'amp',quantity:1}],before),/not available/);assert.throws(()=>quoteLib.quoteRoomBooking({...room,addOns:[{...room.addOns[0],available:true}]},60,[{id:'amp',quantity:1},{id:'amp',quantity:1}],before),/selected once/);identity('ops@example.test');assert.equal((await post({type:'retire',key:crypto.randomUUID(),id:globalPolicy.id,revision:globalPolicy.revision})).status,200);const after=await server.resolveFeePolicy('other','room','2026-10-20');assert.equal(after.id,'founding-pilot-zero-v1');assert.equal(before.policy.studioBps,1000)});
after(()=>{sql.close();rmSync(temp,{recursive:true,force:true});delete globalThis.__commerceTest});
