import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const temp=mkdtempSync(join(tmpdir(),'sessions-expansion-')),sql=new DatabaseSync(':memory:');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(query){this.query=query;this.params=[]}bind(...params){this.params=params;return this}async first(){return sql.prepare(this.query).get(...this.params)??null}async all(){return {results:sql.prepare(this.query).all(...this.params)}}async run(){return sql.prepare(this.query).run(...this.params)}}
const db={prepare:q=>new Statement(q),async batch(steps){sql.exec('BEGIN');try{const r=steps.map(s=>sql.prepare(s.query).run(...s.params));sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
const env={DB:db,SESSIONS_ADMIN_EMAILS:'operator@example.test'};globalThis.__expansion={env,user:null};
const plugin={name:'expansion-fixture',setup(b){b.onResolve({filter:/cloudflare:workers/},()=>({path:'runtime',namespace:'fixture'}));b.onResolve({filter:/chatgpt-auth/},()=>({path:'auth',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='auth'?'export const getChatGPTUser=async()=>globalThis.__expansion.user;':'export const env=globalThis.__expansion.env;',loader:'js'}))}};
await build({entryPoints:{registry:resolve('app/api/registry/route.ts'),planner:resolve('app/api/planner/route.ts'),billing:resolve('app/api/billing/route.ts'),providers:resolve('lib/billing-server.ts'),discovery:resolve('lib/discovery.ts')},bundle:true,platform:'node',format:'esm',outdir:temp,plugins:[plugin],packages:'bundle',logLevel:'silent'});
const registry=await import(pathToFileURL(join(temp,'registry.js'))),planner=await import(pathToFileURL(join(temp,'planner.js'))),billing=await import(pathToFileURL(join(temp,'billing.js'))),providers=await import(pathToFileURL(join(temp,'providers.js'))),discovery=await import(pathToFileURL(join(temp,'discovery.js')));
const identify=email=>{globalThis.__expansion.user=email?{email,displayName:'Fixture User'}:null};
const request=(p,path='/api/registry',origin='https://sessions.test')=>new Request('https://sessions.test'+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(p)});
const action=async p=>{const r=await registry.POST(request(p));return {...await r.json(),status:r.status}};
const state=async()=>await (await registry.GET(new Request('https://sessions.test/api/registry'))).json();
const owner='owner@example.test',customer='customer@example.test',operator='operator@example.test';let registration,studioId,member,booking;
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Harare'}),date=new Date(Date.now()+2*86400000).toISOString().slice(0,10);
const application={type:'registerStudio',name:'Fixture Rehearsal House',area:'Harare CBD',address:'42 Fixture Road, Harare (test address)',category:'Rehearsal studio',description:'A private test fixture for validating registration and studio onboarding.',website:'https://example.test/studio',phone:'+263000000000',representative:'Fixture Owner, Director',evidence:'PRIVATE REGISTRATION EVIDENCE: independent business channel control test.',consent:true};
const review=(id,decision='approved')=>({type:'reviewRegistration',id,decision,note:'Verified independently using the test business channel.',independentContact:true,authorityChecked:true});
const room={id:'fixture-room',name:'Rehearsal room',price:2000,capacity:6,open:540,close:1080,days:[0,1,2,3,4,5,6],buffer:30,minimum:60};
const plan={id:'regular',name:'Regular band',fee:1000,termDays:5,discountPercent:20,priority:true,benefits:'Five days of room discounts and priority request review. External payment.',active:true};
const book=()=>({type:'book',studioId,roomId:room.id,date,start:600,duration:60,size:4,name:'Fixture Band',phone:'+263000000001',note:'',key:crypto.randomUUID(),terms:true});
test('registration needs authentication and cannot publish or grant itself ownership',async()=>{assert.equal((await action(application)).status,401);identify(owner);registration=(await action({...application,status:'approved',owner})).registration;assert.equal(registration.status,'pending');assert.deepEqual((await state()).ownerIds,[]);assert.equal((await action(application)).status,409);identify(customer);assert.deepEqual((await state()).registrations,[]);assert.ok(!JSON.stringify(await state()).includes('PRIVATE REGISTRATION'));assert.equal((await action(review(registration.id))).status,403)});
test('only an independent operator approves registration and creates an unbookable owner workspace',async()=>{identify(operator);const own=(await action({...application,name:'Operator Fixture Studio'})).registration;assert.equal((await action(review(own.id))).status,403);assert.equal((await action({...review(registration.id),independentContact:false})).status,400);assert.equal((await action(review(registration.id))).status,200);assert.equal((await action(review(registration.id))).status,409);identify(owner);const s=await state();studioId=s.registrations.find(r=>r.id===registration.id).studioId;assert.ok(s.ownerIds.includes(studioId));assert.equal(s.studios.find(s=>s.id===studioId).bookingEnabled,false);assert.deepEqual(s.studios.find(s=>s.id===studioId).rooms,[])});
test('owner must add real room capacity, hours and an entrance pin to enable bookings',async()=>{const profile={type:'profile',studioId,description:application.description,address:application.address,area:'Harare CBD',website:application.website,phone:application.phone,email:'',equipment:'Test equipment',rules:'Test payment and cancellation rules are confirmed with this studio.',services:['Rehearsal'],location:{lat:-17.82,lng:31.04},rooms:[room],bookingEnabled:true};assert.equal((await action({...profile,rooms:[{...room,capacity:0}]})).status,400);assert.equal((await action(profile)).status,200)});
test('membership prices and discounts are owner controlled and pending memberships confer no privileges',async()=>{identify(customer);assert.equal((await action({type:'memberPlans',studioId,plans:[plan]})).status,403);identify(owner);assert.equal((await action({type:'memberPlans',studioId,plans:[{...plan,discountPercent:90}]})).status,400);assert.equal((await action({type:'memberPlans',studioId,plans:[plan]})).status,200);identify(customer);member=(await action({type:'joinMembership',studioId,planId:plan.id,name:'Fixture Band',consent:true,status:'active',discountPercent:100})).membership;assert.equal(member.status,'requested');assert.equal((await action({type:'joinMembership',studioId,planId:plan.id,name:'Fixture Band',consent:true})).status,409);const b=(await action({...book(),price:1,priority:true,discount:2000})).booking;assert.equal(b.price,2000);assert.equal(b.priority,false);await action({type:'bookingStatus',studioId,id:b.id,status:'cancelled'});identify('stranger@example.test');assert.deepEqual((await state()).memberships,[])});
test('paid membership needs owner payment confirmation, snapshots terms and never changes staff access',async()=>{identify(owner);const approve={type:'reviewMembership',studioId,id:member.id,decision:'active',note:'External payment received for the agreed term.',paymentConfirmed:false};assert.equal((await action(approve)).status,400);member=(await action({...approve,paymentConfirmed:true})).membership;assert.equal(member.status,'active');assert.equal(member.plan.discountPercent,20);assert.ok(member.startsOn&&member.expiresOn);await action({type:'memberPlans',studioId,plans:[{...plan,discountPercent:5}]});identify(customer);assert.equal((await state()).memberships[0].plan.discountPercent,20);assert.deepEqual((await state()).managedIds,[]);booking=(await action({...book(),price:0})).booking;assert.equal(booking.price,1600);assert.equal(booking.discount,400);assert.equal(booking.basePrice,2000);assert.equal(booking.priority,true);assert.equal((await action({...book(),start:750,size:7})).status,400)});
test('membership expiry uses the session date and cancellation does not rewrite booking receipts',async()=>{identify(customer);const future=new Date(Date.now()+10*86400000).toISOString().slice(0,10);const b=(await action({...book(),date:future})).booking;assert.equal(b.price,2000);assert.equal(b.priority,false);identify(owner);assert.equal((await action({type:'bookingStatus',studioId,id:booking.id,status:'confirmed'})).status,200)});
test('guided planner checks total budget, capacity, date, published calendars and occupied reset buffers',async()=>{identify(customer);const input={date,start:null,duration:60,size:4,budget:1700,area:'CBD',service:'Rehearsal',flexDays:0};const r=await planner.POST(request({mode:'guided',input},'/api/planner'));assert.equal(r.status,200);const p=await r.json();assert.equal(p.mode,'guided');assert.ok(p.options.length>0);assert.ok(p.options.every(o=>o.price===1600&&o.capacity>=4&&o.start!==600&&o.start!==660));assert.ok(p.unknownPriceCount>=12);const impossible=await (await planner.POST(request({mode:'guided',input:{...input,size:9}},'/api/planner'))).json();assert.deepEqual(impossible.options,[]);const long=await (await planner.POST(request({mode:'guided',input:{...input,duration:120}},'/api/planner'))).json();assert.deepEqual(long.options,[])});
test('AI missing configuration is explicit and never silently impersonated by guided logic',async()=>{const config=await (await planner.GET()).json();assert.equal(config.aiReady,false);const r=await planner.POST(request({mode:'ai',prompt:'A session under $50',consent:true,input:{date,start:null,duration:60,size:4,budget:5000,area:'',service:'',flexDays:0}},'/api/planner'));assert.equal(r.status,503);assert.match((await r.json()).error,/not connected/);const hostile=await planner.POST(request({mode:'guided',input:{}},'/api/planner','https://hostile.test'));assert.equal(hostile.status,403)});
test('near me sorts measured pins and excludes unknown or out-of-radius positions',()=>{const p={lat:-17.82,lng:31.04};assert.equal(discovery.distanceKm(p,p),0);const studios=[{id:'unknown',location:null},{id:'far',location:{lat:-18.5,lng:31.04}},{id:'near',location:{lat:-17.825,lng:31.04}},{id:'here',location:p}];assert.deepEqual(discovery.findAStudioNearMe(studios,p,5).map(r=>r.studio.id),['here','near']);assert.ok(discovery.distanceKm(p,{lat:-17.83,lng:31.04})>1)});
test('ending a membership revokes new discounts without altering past booking prices',async()=>{identify('stranger@example.test');assert.equal((await action({type:'cancelMembership',studioId,id:member.id,consent:true})).status,403);identify(customer);assert.equal((await action({type:'cancelMembership',studioId,id:member.id,consent:true})).status,200);assert.equal((await state()).bookings.find(b=>b.id===booking.id).price,1600);const b=(await action({...book(),start:780})).booking;assert.equal(b.price,2000);assert.equal(b.priority,false)});
test('billing has no pretend connections, rejects unauthorised changes and keeps secrets private',async()=>{identify(null);const b=await (await billing.GET(new Request('https://sessions.test/api/billing'))).json();assert.equal(b.amount,null);assert.ok(b.providers.every(p=>!p.ready));assert.equal((await billing.POST(request({action:'checkout',studioId,provider:'stripe',id:crypto.randomUUID(),consent:true},'/api/billing'))).status,401);identify(customer);assert.equal((await billing.POST(request({action:'checkout',studioId,provider:'stripe',id:crypto.randomUUID(),consent:true},'/api/billing'))).status,403);identify(owner);const r=await billing.POST(request({action:'checkout',studioId,provider:'stripe',id:crypto.randomUUID(),consent:true},'/api/billing'));assert.match((await r.json()).error,/not configured/);assert.equal(sql.prepare('SELECT count(*) n FROM billing_checkouts').get().n,0)});
const originalFetch=globalThis.fetch;let stripeCreates=0,checkoutId,subscriptionPaid=false;const now=Date.now(),end=Math.floor(now/1000)+30*86400;
function configure(){Object.assign(env,{BILLING_ENABLED:'true',BILLING_WEBHOOK_READY:'true',BILLING_MODE:'test',BILLING_AMOUNT_CENTS:'1500',BILLING_ORIGIN:'https://sessions.test',BILLING_MERCHANT_NAME:'Fixture merchant',BILLING_SUPPORT_EMAIL:'support@example.test',STRIPE_SECRET_KEY:'sk_test_fixture_not_a_real_key',STRIPE_PRICE_ID:'price_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture_not_real'});}
const json=x=>Response.json(x);
function mockStripe(){globalThis.fetch=async(url,init)=>{url=String(url);if(url.includes('/prices/'))return json({active:true,currency:'usd',unit_amount:1500,type:'recurring',recurring:{interval:'month',interval_count:1},livemode:false});if(url.endsWith('/checkout/sessions')){stripeCreates++;const body=new URLSearchParams(init.body);assert.equal(body.get('line_items[0][price]'),'price_fixture');assert.equal(body.get('mode'),'subscription');assert.equal(body.get('customer_email'),owner);assert.ok(!body.has('payment_method_types'));assert.equal(body.get('success_url').startsWith('https://sessions.test/'),true);checkoutId=body.get('client_reference_id');return json({id:'cs_test_fixture',url:'https://checkout.stripe.com/c/pay/cs_test_fixture'})}if(url.includes('/checkout/sessions/cs_test_fixture'))return json({id:'cs_test_fixture',client_reference_id:checkoutId,metadata:{checkout_id:checkoutId},livemode:false,status:'complete',subscription:subscriptionPaid?'sub_fixture':null});if(url.includes('/subscriptions/sub_fixture'))return json({id:'sub_fixture',customer:'cus_fixture',metadata:{checkout_id:checkoutId},status:'active',items:{data:[{price:{id:'price_fixture',unit_amount:1500},quantity:1,current_period_end:end}]},latest_invoice:{currency:'usd',status:'paid',amount_paid:1500}});throw new Error('Unexpected provider call '+url)};}
test('Stripe checkout uses server price and idempotency; duplicate checkout attempts never create two subscriptions',async()=>{configure();mockStripe();identify(owner);const id=crypto.randomUUID();const p={action:'checkout',studioId,provider:'stripe',id,consent:true,amount:1,returnUrl:'https://evil.test'};const a=await billing.POST(request(p,'/api/billing'));assert.equal(a.status,200);assert.equal((await a.json()).url,'https://checkout.stripe.com/c/pay/cs_test_fixture');const b=await billing.POST(request(p,'/api/billing'));assert.equal(b.status,200);assert.equal(stripeCreates,1);const other=await billing.POST(request({...p,id:crypto.randomUUID()},'/api/billing'));assert.equal(other.status,400);assert.equal(stripeCreates,1);const visible=JSON.stringify(await (await billing.GET(new Request('https://sessions.test/api/billing?studio='+studioId))).json());assert.ok(!visible.includes('sk_test_fixture'));assert.ok(!visible.includes('whsec_fixture'));assert.equal(sql.prepare('SELECT count(*) n FROM billing_accounts').get().n,0)});
test('return parameters never activate subscriptions and forged webhooks are rejected',async()=>{await billing.GET(new Request('https://sessions.test/api/billing?studio='+studioId+'&success=true&paid=true'));assert.equal(sql.prepare('SELECT count(*) n FROM billing_accounts').get().n,0);await assert.rejects(()=>providers.processBillingWebhook('stripe',new Request('https://sessions.test/api/billing/webhook/stripe',{method:'POST',headers:{'stripe-signature':'t=1,v1=forged'},body:'{"id":"evt_fixture"}'})),/signature/);await providers.reconcileCheckout(checkoutId);assert.equal(sql.prepare('SELECT count(*) n FROM billing_accounts').get().n,0)});
async function sign(raw,secret,t=Math.floor(Date.now()/1000)){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(t+'.'+raw))).toString('hex');return `t=${t},v1=${sig}`;}
test('signed webhook reconciles canonical paid invoice, activates once and rejects tampering or stale signatures',async()=>{subscriptionPaid=true;const raw=JSON.stringify({id:'evt_fixture_paid',livemode:false,data:{object:{metadata:{checkout_id:checkoutId}}}}),sig=await sign(raw,env.STRIPE_WEBHOOK_SECRET);assert.equal(await providers.verifyStripeSignature(raw,sig,env.STRIPE_WEBHOOK_SECRET),true);assert.equal(await providers.verifyStripeSignature(raw+'x',sig,env.STRIPE_WEBHOOK_SECRET),false);assert.equal(await providers.verifyStripeSignature(raw,await sign(raw,env.STRIPE_WEBHOOK_SECRET,1),env.STRIPE_WEBHOOK_SECRET),false);const req=()=>new Request('https://sessions.test/api/billing/webhook/stripe',{method:'POST',headers:{'stripe-signature':sig},body:raw});await providers.processBillingWebhook('stripe',req());await providers.processBillingWebhook('stripe',req());assert.equal(sql.prepare('SELECT count(*) n FROM billing_accounts').get().n,1);assert.equal(sql.prepare('SELECT count(*) n FROM billing_events').get().n,1);const a=JSON.parse(sql.prepare('SELECT content FROM billing_accounts').get().content);assert.equal(a.status,'active');assert.equal(a.provider,'stripe');assert.equal(a.paidUntil,new Date(end*1000).toISOString());identify(customer);const hidden=await (await billing.GET(new Request('https://sessions.test/api/billing?studio='+studioId))).json();assert.equal(hidden.account,null);assert.deepEqual(hidden.checkouts,[])});
test('Paynow SHA-512 hashing matches the published provider test vector',async()=>{const p=new URLSearchParams({id:'1201',reference:'TEST REF',amount:'99.99',additionalinfo:'A test ticket transaction',returnurl:'http://www.google.com/search?q=returnurl',resulturl:'http://www.google.com/search?q=resulturl',status:'Message'});assert.equal(await providers.paynowHash(p,'3e9fed89-60e1-4ce5-ab6e-6b1eb2d4f977'),'2A033FC38798D913D42ECB786B9B19645ADEDBDE788862032F1BD82CF3B92DEF84F316385D5B40DBB35F1A4FD7D5BFE73835174136463CDD48C9366B0749C689');assert.throws(()=>providers.trustedUrl('https://checkout.stripe.com.evil.test/',['checkout.stripe.com']),/unsafe/);assert.throws(()=>providers.trustedUrl('http://www.paynow.co.zw/',['www.paynow.co.zw']),/unsafe/)});
test('PayPal validates the configured monthly plan and reconciles payment without trusting redirects',async()=>{
 Object.assign(env,{PAYPAL_CLIENT_ID:'fixture-client',PAYPAL_CLIENT_SECRET:'fixture-secret',PAYPAL_PLAN_ID:'P-FIXTURE',PAYPAL_WEBHOOK_ID:'WH-FIXTURE'});
 const sid='paypal-fixture-studio',id=crypto.randomUUID();let paid=false;
 sql.prepare('INSERT INTO studio_registry(id,owner,content) VALUES(?,?,?)').run(sid,owner,JSON.stringify({...JSON.parse(sql.prepare('SELECT content FROM studio_registry WHERE id=?').get(studioId).content),id:sid,name:'PayPal Fixture Studio',rooms:[],bookingEnabled:false}));
 globalThis.fetch=async(url,init)=>{url=String(url);if(url.endsWith('/v1/oauth2/token'))return json({access_token:'fixture-access-token'});if(url.includes('/v1/billing/plans/'))return json({status:'ACTIVE',billing_cycles:[{tenure_type:'REGULAR',total_cycles:0,frequency:{interval_unit:'MONTH',interval_count:1},pricing_scheme:{fixed_price:{currency_code:'USD',value:'15.00'}}}]});if(url.endsWith('/v1/billing/subscriptions')){const body=JSON.parse(init.body);assert.equal(body.plan_id,'P-FIXTURE');assert.equal(body.custom_id,id);assert.ok(body.application_context.return_url.startsWith('https://sessions.test/'));return json({id:'I-FIXTURE',links:[{rel:'approve',href:'https://www.sandbox.paypal.com/webapps/billing/approval'}]})}if(url.endsWith('/v1/billing/subscriptions/I-FIXTURE'))return json({id:'I-FIXTURE',plan_id:'P-FIXTURE',custom_id:id,status:paid?'ACTIVE':'APPROVAL_PENDING',billing_info:paid?{last_payment:{amount:{currency_code:'USD',value:'15.00'},time:new Date().toISOString()},next_billing_time:new Date(Date.now()+28*86400000).toISOString()}:undefined});throw new Error('Unexpected PayPal request');};
 const started=await providers.startCheckout(sid,owner,'paypal',id);assert.match(started.url,/sandbox.paypal.com/);assert.equal((await providers.reconcileCheckout(id)).status,'pending');assert.equal(sql.prepare('SELECT content FROM billing_accounts WHERE studio_id=?').get(sid),undefined);paid=true;assert.equal((await providers.reconcileCheckout(id)).status,'active');assert.equal(JSON.parse(sql.prepare('SELECT content FROM billing_accounts WHERE studio_id=?').get(sid).content).provider,'paypal');
});
test('Paynow verifies initiation and polling hashes, exact amounts and replay-stable prepaid expiry',async()=>{
 Object.assign(env,{PAYNOW_INTEGRATION_ID:'fixture-123',PAYNOW_INTEGRATION_KEY:'fixture-paynow-key',PAYNOW_CURRENCY:'USD',PAYNOW_MODE:'test'});
 const sid='paynow-fixture-studio',id=crypto.randomUUID();let wrongAmount=false;
 sql.prepare('INSERT INTO studio_registry(id,owner,content) VALUES(?,?,?)').run(sid,owner,JSON.stringify({...JSON.parse(sql.prepare('SELECT content FROM studio_registry WHERE id=?').get(studioId).content),id:sid,name:'Paynow Fixture Studio',rooms:[],bookingEnabled:false}));
 const signed=async values=>{const p=new URLSearchParams(values);p.append('hash',await providers.paynowHash(p,env.PAYNOW_INTEGRATION_KEY));return new Response(p.toString())};
 globalThis.fetch=async(url,init)=>{url=String(url);if(url.endsWith('/interface/initiatetransaction')){const p=new URLSearchParams(init.body);assert.equal(p.get('reference'),id);assert.equal(p.get('amount'),'15.00');assert.equal(p.get('hash'),await providers.paynowHash(p,env.PAYNOW_INTEGRATION_KEY));return signed({status:'Ok',browserurl:'https://www.paynow.co.zw/Payment/ConfirmPayment/fixture',pollurl:'https://www.paynow.co.zw/Interface/CheckPayment/fixture'})}if(url.endsWith('/Interface/CheckPayment/fixture'))return signed({reference:id,amount:wrongAmount?'1.00':'15.00',status:'Paid'});throw new Error('Unexpected Paynow request')};
 await providers.startCheckout(sid,owner,'paynow',id);wrongAmount=true;await assert.rejects(()=>providers.reconcileCheckout(id),/amount mismatch/);assert.equal(sql.prepare('SELECT content FROM billing_accounts WHERE studio_id=?').get(sid),undefined);wrongAmount=false;const first=await providers.reconcileCheckout(id),second=await providers.reconcileCheckout(id);assert.equal(first.status,'active');assert.equal(first.paidUntil,second.paidUntil);await assert.rejects(()=>providers.processBillingWebhook('paynow',new Request('https://sessions.test/api/billing/webhook/paynow',{method:'POST',body:'reference='+id+'&amount=15.00&status=Paid&hash=forged'})),/signature/);
});
test('configured AI only interprets requirements; it receives no account or location and cannot book',async()=>{
 identify(customer);env.OPENAI_API_KEY='fixture-ai-key';env.OPENAI_MODEL='fixture-structured-model';let requests=0;
 globalThis.fetch=async(url,init)=>{assert.equal(String(url),'https://api.openai.com/v1/responses');const body=JSON.parse(init.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.ok(!JSON.stringify(body).includes(customer));assert.ok(!JSON.stringify(body).includes('31.04'));requests++;return json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({date,start:900,duration:60,size:4,budget:2100,area:'CBD',service:'Rehearsal',flexDays:0})}]}]})};
 const before=sql.prepare('SELECT count(*) n FROM studio_bookings').get().n;const r=await planner.POST(request({mode:'ai',prompt:'Rehearsal tomorrow, four people, $21 total',consent:true,input:{date,start:null,duration:60,size:4,budget:5000,area:'',service:'',flexDays:0}},'/api/planner'));assert.equal(r.status,200);const output=await r.json();assert.equal(output.mode,'ai');assert.equal(output.input.budget,2100);assert.ok(output.options.every(o=>o.price<=2100));assert.equal(requests,1);assert.equal(sql.prepare('SELECT count(*) n FROM studio_bookings').get().n,before);delete env.OPENAI_API_KEY;delete env.OPENAI_MODEL;
});
test('live billing requires an explicit launch gate and matching live keys',()=>{env.BILLING_MODE='live';assert.ok(providers.billingConfiguration().providers.every(p=>!p.ready));env.BILLING_LIVE_APPROVED='true';assert.equal(providers.billingConfiguration().providers.find(p=>p.id==='stripe').ready,false);env.BILLING_MODE='test';});
after(()=>{globalThis.fetch=originalFetch;sql.close();rmSync(temp,{recursive:true,force:true});delete globalThis.__expansion});
