import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';

const temp=mkdtempSync(join(tmpdir(),'sessions-settlement-test-')),sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(value=>value.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(query){this.query=query;this.params=[]}bind(...params){this.params=params;return this}async first(){return sql.prepare(this.query).get(...this.params)??null}async all(){return {results:sql.prepare(this.query).all(...this.params)}}async run(){return sql.prepare(this.query).run(...this.params)}}
const db={prepare:query=>new Statement(query),async batch(statements){sql.exec('BEGIN');try{const results=statements.map(statement=>sql.prepare(statement.query).run(...statement.params));sql.exec('COMMIT');return results}catch(error){sql.exec('ROLLBACK');throw error}}};
globalThis.__settlementTest={db,user:null};
const plugin={name:'settlement-fixture',setup(builder){builder.onResolve({filter:/cloudflare:workers/},()=>({path:'runtime',namespace:'fixture'}));builder.onResolve({filter:/chatgpt-auth/},()=>({path:'auth',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='auth'?"export const getProductionUser=async()=>{const user=globalThis.__settlementTest.user;return user?{id:user.id,displayName:user.id,email:user.email,phone:null,roles:user.operator?['musician','operations_admin']:['musician'],memberships:[],method:'chatgpt_demo',sessionId:'test'}:null};":"export const env={DB:globalThis.__settlementTest.db,SESSIONS_ADMIN_EMAILS:'operator@example.test'};",loader:'js'}))}};
for(const [name,path] of [['registry','app/api/registry/route.ts'],['settlements','app/api/settlements/route.ts'],['export','app/api/settlements/export/route.ts']])await build({entryPoints:[resolve(path)],bundle:true,platform:'node',format:'esm',outfile:join(temp,name+'.mjs'),plugins:[plugin],logLevel:'silent'});
const registry=await import(pathToFileURL(join(temp,'registry.mjs')),),settlements=await import(pathToFileURL(join(temp,'settlements.mjs'))),exports=await import(pathToFileURL(join(temp,'export.mjs')));
const studioId='settlement-studio',otherStudio='other-studio',owner='owner@example.test',customer='customer@example.test',outsider='outsider@example.test',operator='operator@example.test',bookingId='RS-settlement-fixture';
const identity=(id,operatorRole=false)=>{globalThis.__settlementTest.user=id?{id,email:id,operator:operatorRole}:null};
const post=async(handler,payload)=>{const response=await handler(new Request('https://sessions.test/api/settlements',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://sessions.test'},body:JSON.stringify(payload)}));let body={};try{body=await response.json()}catch{}return {status:response.status,...body}};
const registryAction=async payload=>{const response=await registry.POST(new Request('https://sessions.test/api/registry',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://sessions.test'},body:JSON.stringify(payload)}));return {status:response.status,...await response.json()}};
const get=async(query='')=>{const response=await settlements.GET(new Request('https://sessions.test/api/settlements'+query));return {status:response.status,...await response.json()}};
const studio={id:studioId,name:'Settlement Test Studio',area:'Harare CBD',address:'Test address, Harare',category:'Rehearsal studio',services:['Rehearsal'],description:'A private fixture studio for settlement lifecycle verification.',website:'',phone:'+263000000000',email:'',sources:[],status:'bookable',bookingEnabled:true,rooms:[{id:'room-1',name:'Main room',price:2000,capacity:6,open:0,close:1440,days:[0,1,2,3,4,5,6],buffer:0,minimum:60,photos:[]}],equipment:'',rules:'Fixture terms for direct studio settlement.',location:{lat:-17.82,lng:31.04},revision:0};
const booking={id:bookingId,studioId,roomId:'room-1',roomName:'Main room',customer,name:'Test Band',phone:'+263771111111',date:'2026-09-20',start:600,duration:60,size:4,note:'',staffId:'',status:'requested',price:2000,createdAt:new Date().toISOString()};
sql.prepare('INSERT INTO studio_registry(id,owner,revision,content) VALUES(?,?,0,?)').run(studioId,owner,JSON.stringify(studio));
sql.prepare('INSERT INTO studio_registry(id,owner,revision,content) VALUES(?,?,0,?)').run(otherStudio,outsider,JSON.stringify({...studio,id:otherStudio,name:'Other Test Studio'}));
sql.prepare('INSERT INTO studio_bookings(id,studio_id,customer,request_key,content) VALUES(?,?,?,?,?)').run(booking.id,studioId,customer,crypto.randomUUID(),JSON.stringify(booking));

let settlement,proofKey;
test('confirming a booking creates one zero-fee, server-priced concierge settlement',async()=>{identity(owner);const result=await registryAction({type:'bookingStatus',studioId,id:bookingId,status:'confirmed'});assert.equal(result.status,200);settlement=result.settlement;assert.equal(settlement.status,'awaiting_payment');assert.equal(settlement.pricing.roomSubtotal,2000);assert.equal(settlement.pricing.customerTotal,2000);assert.equal(settlement.pricing.platformFee,0);assert.equal(settlement.pricing.policy.id,'founding-pilot-zero-v1');assert.equal(sql.prepare('SELECT count(*) n FROM studio_settlements WHERE booking_id=?').get(bookingId).n,1)});
test('absent settlement is visible to both parties and Operations, not unrelated users',async()=>{identity(customer);assert.equal((await get()).settlements[0].status,'awaiting_payment');identity(operator,true);assert.ok((await get()).settlements.some(value=>value.id===settlement.id));identity(outsider);assert.deepEqual((await get()).settlements,[])});
test('identity, customer ownership, studio role and revision are enforced',async()=>{identity(null);assert.equal((await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),proofMediaId:crypto.randomUUID(),method:'ecocash',note:''})).status,401);identity(outsider);assert.equal((await post(settlements.POST,{type:'confirmDirect',studioId,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),method:'cash'})).status,403);identity(customer);assert.equal((await post(settlements.POST,{type:'confirmDirect',studioId,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),method:'cash'})).status,403);identity(operator,true);assert.equal((await post(settlements.POST,{type:'confirmDirect',studioId,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),method:'cash'})).status,403);identity(owner);assert.equal((await post(settlements.POST,{type:'confirmDirect',studioId,settlementId:settlement.id,revision:99,key:crypto.randomUUID(),method:'cash'})).status,409);assert.equal((await post(settlements.POST,{type:'confirmDirect',studioId:otherStudio,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),method:'cash'})).status,404)});
test('customer proof is private, idempotent and studio-declinable with a visible reason',async()=>{const media=crypto.randomUUID();sql.prepare("INSERT INTO uploads(id,owner,type,studio_id,booking_id,purpose,created_at) VALUES(?,?,?,?,?,'settlement_proof',?)").run(media,customer,'image/png',studioId,bookingId,new Date().toISOString());identity(customer);assert.equal((await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:0,key:crypto.randomUUID(),proofMediaId:crypto.randomUUID(),method:'ecocash',note:''})).status,403);proofKey=crypto.randomUUID();let result=await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:0,key:proofKey,proofMediaId:media,method:'ecocash',note:'Fixture transaction'});assert.equal(result.status,200);settlement=result.settlement;assert.equal(settlement.status,'proof_submitted');const duplicate=await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:0,key:proofKey,proofMediaId:media,method:'ecocash',note:'Fixture transaction'});assert.equal(duplicate.status,200);assert.equal(duplicate.duplicate,true);assert.equal(sql.prepare("SELECT count(*) n FROM settlement_events WHERE event='proof_submitted'").get().n,1);identity(owner);result=await post(settlements.POST,{type:'declineProof',studioId,settlementId:settlement.id,revision:settlement.revision,key:crypto.randomUUID(),reason:'Transaction reference could not be matched'});settlement=result.settlement;assert.equal(settlement.status,'payment_declined');identity(customer);const customerView=await get();assert.equal(customerView.settlements[0].declineReason,'Transaction reference could not be matched')});
test('replacement proof requires a fresh revision and studio acknowledgement settles exact arithmetic',async()=>{identity(customer);const stale=await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:1,key:crypto.randomUUID(),proofMediaId:settlement.proofMediaId,method:'ecocash',note:'Replacement'});assert.equal(stale.status,409);let result=await post(settlements.POST,{type:'submitProof',studioId,settlementId:settlement.id,revision:settlement.revision,key:crypto.randomUUID(),proofMediaId:settlement.proofMediaId,method:'ecocash',note:'Replacement'});settlement=result.settlement;identity(owner);result=await post(settlements.POST,{type:'confirmDirect',studioId,settlementId:settlement.id,revision:settlement.revision,key:crypto.randomUUID(),method:'cash'});settlement=result.settlement;assert.equal(settlement.status,'settled_off_platform');assert.equal(settlement.settledMethod,'ecocash');const row=sql.prepare('SELECT * FROM studio_settlements WHERE id=?').get(settlement.id);assert.equal(row.gross_cents,row.room_subtotal_cents+row.addon_subtotal_cents);assert.equal(row.platform_fee_cents,row.customer_fee_cents+row.studio_fee_cents);assert.equal(row.customer_total_cents,row.gross_cents+row.customer_fee_cents);assert.equal(row.studio_net_cents,row.gross_cents-row.studio_fee_cents)});
test('paid booking cannot be silently cancelled and disputes are visible and independently resolved',async()=>{identity(customer);assert.equal((await registryAction({type:'bookingStatus',studioId,id:bookingId,status:'cancelled'})).status,409);let result=await post(settlements.POST,{type:'openSettlementDispute',studioId,settlementId:settlement.id,revision:settlement.revision,key:crypto.randomUUID(),reason:'The studio confirmation does not match the agreed payment record.'});settlement=result.settlement;assert.equal(settlement.status,'disputed');identity(operator,true);assert.ok((await get()).settlements.some(value=>value.status==='disputed'));result=await post(settlements.POST,{type:'resolveSettlementDispute',studioId,settlementId:settlement.id,revision:settlement.revision,key:crypto.randomUUID(),note:'Both parties confirmed the original direct payment record is correct.'});settlement=result.settlement;assert.equal(settlement.status,'settled_off_platform')});
test('closed-month invoice and authenticated CSV/PDF reconcile to settled ledger rows',async()=>{const content={...settlement,settledMonth:'2026-08',settledAt:'2026-08-31T10:00:00.000Z',updatedAt:'2026-08-31T10:00:00.000Z'};sql.prepare('UPDATE studio_settlements SET settled_month=?,settled_at=?,content=? WHERE id=?').run('2026-08',content.settledAt,JSON.stringify(content),settlement.id);identity(owner);const issued=await post(settlements.POST,{type:'issueInvoice',studioId,period:'2026-08',key:crypto.randomUUID()});assert.equal(issued.status,200);assert.equal(issued.invoice.gross,2000);assert.equal(issued.invoice.platformFee,0);const again=await post(settlements.POST,{type:'issueInvoice',studioId,period:'2026-08',key:crypto.randomUUID()});assert.equal(again.invoice.id,issued.invoice.id);const csv=await exports.GET(new Request('https://sessions.test/api/settlements/export?studio='+studioId+'&month=2026-08&format=csv'));assert.equal(csv.status,200);assert.match(csv.headers.get('content-type'),/^text\/csv/);assert.match(await csv.text(),/20\.00/);const pdf=await exports.GET(new Request('https://sessions.test/api/settlements/export?studio='+studioId+'&month=2026-08&format=pdf'));assert.equal(pdf.status,200);assert.equal(pdf.headers.get('content-type'),'application/pdf');assert.equal(new TextDecoder().decode((await pdf.arrayBuffer()).slice(0,8)),'%PDF-1.4');identity(outsider);assert.equal((await exports.GET(new Request('https://sessions.test/api/settlements/export?studio='+studioId+'&month=2026-08&format=csv'))).status,403)});

after(()=>{sql.close();rmSync(temp,{recursive:true,force:true});delete globalThis.__settlementTest});
