import React,{useEffect,useMemo,useState} from 'react';
import {
  ActivityIndicator,Alert,BackHandler,KeyboardAvoidingView,Modal,Platform,Pressable,
  RefreshControl,ScrollView,StatusBar,Text,TextInput,View,
} from 'react-native';
import {SafeAreaProvider,SafeAreaView,initialWindowMetrics} from 'react-native-safe-area-context';
import {
  CUSTOMER_TABS,DESIGN_TOKENS,NATIVE_AUTH_BOUNDARY,PHASE_1_5_PARITY,PROVIDER_TABS,
  SESSIONS_RELEASE,WORKSPACE_CONTEXTS,
} from '@sessions/product-core';
import {probeProtectedEndpoint,UAT_ORIGIN,verifyRelease} from './src/api';
import {UAT_DATA_NOTICE,UAT_IDENTITY,UAT_PROVIDER_BOOKINGS,UAT_SESSIONS,UAT_STUDIOS} from './src/uat-data';
import {MIN_TOUCH,styles} from './src/styles';

const GLYPHS={home:'⌂',search:'⌕',sessions:'▣',profile:'○'};
const initialRoute={name:'home',params:{}};

function money(cents){return cents?`US$${(cents/100).toFixed(cents%100?2:0)}`:'Rates not published'}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()}

function PrimaryButton({children,onPress,disabled=false}){
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[styles.primary,pressed&&styles.primaryPressed,disabled&&styles.primaryDisabled]}><Text style={styles.primaryText}>{children}</Text></Pressable>;
}
function SecondaryButton({children,onPress}){return <Pressable accessibilityRole="button" onPress={onPress} style={styles.secondary}><Text style={styles.secondaryText}>{children}</Text></Pressable>}
function TopBar({title='SESSIONS',action,onBack}){return <View style={title==='SESSIONS'?styles.brandRow:styles.header}>{onBack?<Pressable accessibilityRole="button" accessibilityLabel="Back" hitSlop={8} style={styles.back} onPress={onBack}><Text style={styles.strong}>‹</Text></Pressable>:null}{title==='SESSIONS'?<Text style={styles.wordmark}>SESSIONS<Text style={styles.blueDot}>.</Text></Text>:<Text style={styles.headerTitle}>{title}</Text>}{action||<View style={{width:MIN_TOUCH}}/>}</View>}
function SectionHead({eyebrow,title,action}){return <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.sectionTitle}>{title}</Text></View>{action}</View>}
function StudioArt({studio}){return <View style={styles.studioArt}><View style={styles.studioArtBadge}><Text style={styles.studioArtBadgeText}>{studio.bookable?'Bookable':'Profile'}</Text></View><Text style={styles.studioInitials}>{initials(studio.name)}</Text></View>}
function StudioCard({studio,onPress}){return <Pressable accessibilityRole="button" onPress={onPress} style={styles.studioCard}><StudioArt studio={studio}/><View style={styles.studioBody}><Text style={styles.strong}>{studio.name}</Text><Text style={styles.small}>{studio.area} · {studio.category}</Text><Text style={styles.strong}>{studio.rate?`from ${money(studio.rate)}/hr`:'Rates not published'}</Text></View></Pressable>}
function StatePill({value}){return <View style={styles.statePill}><Text style={styles.stateText}>{value}</Text></View>}
function Notice({children}){return <View style={styles.notice}><Text style={styles.noticeText}>{children}</Text></View>}

function HomeScreen({go}){
  return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
    <TopBar action={<Pressable accessibilityRole="button" accessibilityLabel="Native diagnostics" hitSlop={8} style={styles.topAction} onPress={()=>go('diagnostics')}><Text style={styles.strong}>i</Text></Pressable>}/>
    <Text style={styles.eyebrow}>HARARE · ZIMBABWE</Text><Text style={styles.heroTitle}>Find your next{`\n`}rehearsal room.</Text>
    <Pressable accessibilityRole="search" style={styles.searchEntry} onPress={()=>go('search')}><Text style={styles.searchGlyph}>⌕</Text><Text style={styles.searchText}>Where do you want to rehearse?</Text><Text style={styles.strong}>›</Text></Pressable>
    <View style={styles.section}><SectionHead eyebrow="DISCOVER" title="Spaces for your sound" action={<Pressable onPress={()=>go('search')}><Text style={styles.linkText}>Search</Text></Pressable>}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}>{UAT_STUDIOS.map(studio=><StudioCard key={studio.id} studio={studio} onPress={()=>go('studio',{studioId:studio.id})}/>)}</ScrollView></View>
    <View style={styles.section}><Pressable style={styles.banner} onPress={()=>go('search')}><View style={{flex:1}}><Text style={styles.eyebrow}>EXPLORE HARARE</Text><Text style={styles.bannerTitle}>Search by area, service and availability</Text><Text style={styles.bannerBody}>A focused mobile flow instead of a compressed desktop filter panel.</Text></View><Text style={{color:'#fff',fontSize:24}}>›</Text></Pressable></View>
    <View style={styles.section}><View style={styles.providerEntry}><Text style={styles.eyebrow}>STUDIO OWNER?</Text><Text style={styles.providerTitle}>Run today’s studio work from mobile.</Text><Text style={[styles.body,{marginTop:6}]}>Daily provider operations get a dedicated native surface. Full configuration remains on desktop/PWA.</Text><Pressable style={{minHeight:MIN_TOUCH,justifyContent:'center',marginTop:10}} onPress={()=>go('provider')}><Text style={styles.linkText}>Open provider mode →</Text></Pressable></View></View>
  </ScrollView>;
}

function SearchScreen({go}){
  const[query,setQuery]=useState('');const[filter,setFilter]=useState('all');
  const visible=useMemo(()=>UAT_STUDIOS.filter(studio=>{const text=`${studio.name} ${studio.area} ${studio.category} ${studio.services.join(' ')}`.toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;if(filter==='bookable'&&!studio.bookable)return false;if(filter!=='all'&&filter!=='bookable'&&!studio.services.some(item=>item.toLowerCase().includes(filter)))return false;return true}),[query,filter]);
  return <View style={styles.screen}><View style={{paddingHorizontal:18,paddingTop:12}}><TopBar title="Search"/><TextInput accessibilityLabel="Search studios" autoCapitalize="none" autoCorrect={false} returnKeyType="search" value={query} onChangeText={setQuery} placeholder="Studio, area or service" placeholderTextColor={DESIGN_TOKENS.color.subtle} style={styles.field}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{[['all','All'],['rehearsal','Rehearsal'],['recording','Recording'],['bookable','Bookable']].map(([value,label])=><Pressable key={value} onPress={()=>setFilter(value)} style={[styles.chip,filter===value&&styles.chipActive]}><Text style={[styles.chipText,filter===value&&styles.chipTextActive]}>{label}</Text></Pressable>)}</ScrollView></View><ScrollView contentContainerStyle={styles.scroll}>{visible.length?visible.map(studio=><Pressable key={studio.id} style={styles.resultCard} onPress={()=>go('studio',{studioId:studio.id})}><View style={styles.between}><View style={{flex:1,gap:4}}><View style={styles.status}><Text style={styles.statusText}>{studio.bookable?'Bookable now':'Studio profile'}</Text></View><Text style={[styles.strong,{fontSize:18,marginTop:4}]}>{studio.name}</Text><Text style={styles.small}>{studio.area} · {studio.services.slice(0,3).join(' · ')}</Text><Text style={styles.strong}>{studio.rate?`from ${money(studio.rate)}/hr`:'Rates not published'}</Text></View><Text style={{fontSize:24}}>›</Text></View></Pressable>):<View style={styles.empty}><Text style={styles.emptyTitle}>No matching spaces</Text><Text style={styles.body}>Try another area, studio name or filter.</Text></View>}</ScrollView></View>;
}

function StudioScreen({route,go,back}){
  const studio=UAT_STUDIOS.find(item=>item.id===route.params.studioId);
  if(!studio)return <View style={styles.screen}><TopBar title="Studio unavailable" onBack={back}/></View>;
  return <View style={styles.screen}><ScrollView contentContainerStyle={{paddingBottom:118}}><View style={styles.detailHero}><Pressable accessibilityRole="button" accessibilityLabel="Back" style={[styles.back,{position:'absolute',top:10,left:10,backgroundColor:'rgba(255,255,255,.9)'}]} onPress={back}><Text style={styles.strong}>‹</Text></Pressable><Text style={styles.detailInitials}>{initials(studio.name)}</Text></View><View style={styles.detailBody}><View style={styles.status}><Text style={styles.statusText}>{studio.bookable?'Bookable through Sessions':'Profile only'}</Text></View><Text style={styles.title}>{studio.name}</Text><Text style={[styles.body,{marginTop:5}]}>{studio.area}, Harare · {studio.category}</Text><View style={styles.summary}><View style={styles.summaryCell}><Text style={styles.eyebrow}>FROM</Text><Text style={styles.strong}>{studio.rate?`${money(studio.rate)}/hr`:'—'}</Text></View><View style={styles.summaryCell}><Text style={styles.eyebrow}>ROOMS</Text><Text style={styles.strong}>{studio.rooms.length||'—'}</Text></View><View style={[styles.summaryCell,{borderRightWidth:0}]}><Text style={styles.eyebrow}>TYPE</Text><Text style={styles.strong}>{studio.category.replace(' studio','')}</Text></View></View><View style={styles.section}><SectionHead eyebrow="WHAT YOU CAN DO" title="Services"/><View style={styles.infoCard}><Text style={styles.body}>{studio.services.join(' · ')}</Text></View></View>{studio.rooms.length?<View style={styles.section}><SectionHead eyebrow="BOOKING" title="Rooms"/>{studio.rooms.map(room=><View key={room.id} style={styles.infoCard}><View style={styles.between}><View><Text style={styles.strong}>{room.name}</Text><Text style={styles.small}>Up to {room.capacity} people</Text></View><Text style={styles.strong}>{money(room.price)}/hr</Text></View></View>)}</View>:null}<View style={styles.section}><Notice>{UAT_DATA_NOTICE}</Notice></View></View></ScrollView><View style={styles.stickyCta}><PrimaryButton disabled={!studio.bookable} onPress={()=>go('booking',{studioId:studio.id})}>{studio.bookable?'Choose a time':'Not bookable yet'}</PrimaryButton></View></View>;
}

function BookingScreen({route,back}){
  const studio=UAT_STUDIOS.find(item=>item.id===route.params.studioId);const[roomId,setRoomId]=useState(studio?.rooms[0]?.id||'');const[time,setTime]=useState('18:00');const[showConfirm,setShowConfirm]=useState(false);
  if(!studio)return <View style={styles.screen}><TopBar title="Booking unavailable" onBack={back}/></View>;
  const room=studio.rooms.find(item=>item.id===roomId);
  return <View style={styles.screen}><TopBar title="Book a session" onBack={back}/><ScrollView contentContainerStyle={styles.scrollNoTabs} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>PHASE 5 · MOBILE BOOKING</Text><Text style={styles.title}>Choose your session.</Text><Text style={[styles.body,{marginTop:7}]}>Pick one room and time. Live inventory and authenticated mutation will use the canonical Sessions API after native identity is connected.</Text><View style={styles.section}><SectionHead eyebrow="ROOM" title="Where"/><View style={{gap:8}}>{studio.rooms.map(item=><Pressable key={item.id} onPress={()=>setRoomId(item.id)} style={[styles.resultCard,roomId===item.id&&{borderColor:DESIGN_TOKENS.color.royal,borderWidth:2}]}><View style={styles.between}><View><Text style={styles.strong}>{item.name}</Text><Text style={styles.small}>Up to {item.capacity} people</Text></View><Text style={styles.strong}>{money(item.price)}/hr</Text></View></Pressable>)}</View></View><View style={styles.section}><SectionHead eyebrow="TIME" title="Start time"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{['16:00','16:30','17:00','17:30','18:00','18:30'].map(item=><Pressable key={item} style={[styles.chip,time===item&&styles.chipActive]} onPress={()=>setTime(item)}><Text style={[styles.chipText,time===item&&styles.chipTextActive]}>{item}</Text></Pressable>)}</ScrollView></View><View style={styles.section}><Notice>Phase 4.5 production native auth is intentionally blocked until the genuine Sessions Supabase project is identified. This flow never imports ChatGPT Sites browser cookies.</Notice></View></ScrollView><View style={styles.stickyCta}><PrimaryButton onPress={()=>setShowConfirm(true)}>Review request · {room?money(room.price):'—'}</PrimaryButton></View><Modal visible={showConfirm} transparent animationType="slide" onRequestClose={()=>setShowConfirm(false)}><View style={styles.modalShade}><View style={styles.modalCard}><Text style={styles.eyebrow}>CONFIRM SESSION</Text><Text style={styles.modalTitle}>{studio.name}</Text><Text style={styles.body}>{room?.name} · {time} · 60 minutes</Text><View style={{marginTop:18,gap:9}}><PrimaryButton onPress={()=>{setShowConfirm(false);Alert.alert('Sessions Auth required','The native booking mutation is correctly blocked until the real Sessions Supabase identity environment is configured. No authentication bypass was created.')}}>Continue securely</PrimaryButton><SecondaryButton onPress={()=>setShowConfirm(false)}>Edit session</SecondaryButton></View></View></View></Modal></View>;
}

function SessionsScreen({go}){return <ScrollView contentContainerStyle={styles.scroll}><TopBar title="Sessions"/><Text style={styles.eyebrow}>YOUR BOOKINGS</Text><Text style={styles.title}>What’s next.</Text><View style={styles.section}>{UAT_SESSIONS.map(item=><Pressable key={item.id} style={styles.sessionCard} onPress={()=>go('session',{id:item.id})}><View style={styles.between}><StatePill value={item.status}/><Text style={styles.small}>{item.date}</Text></View><Text style={[styles.strong,{fontSize:18,marginTop:10}]}>{item.studio}</Text><Text style={[styles.body,{marginTop:3}]}>{item.time} · {item.duration} · {item.room}</Text></Pressable>)}</View><Notice>{UAT_DATA_NOTICE}</Notice></ScrollView>}
function SessionScreen({route,back}){const item=UAT_SESSIONS.find(value=>value.id===route.params.id);return <ScrollView contentContainerStyle={styles.scrollNoTabs}><TopBar title="Session details" onBack={back}/>{item?<><StatePill value={item.status}/><Text style={styles.title}>{item.studio}</Text><View style={styles.infoCard}><Text style={styles.eyebrow}>WHEN</Text><Text style={styles.strong}>{item.date} · {item.time} · {item.duration}</Text></View><View style={styles.infoCard}><Text style={styles.eyebrow}>ROOM</Text><Text style={styles.strong}>{item.room}</Text></View><View style={styles.section}><Pressable style={styles.destructive} onPress={()=>Alert.alert('Cancel session?','Destructive booking actions require an authenticated Sessions session and server confirmation. The native UAT shell will not fake this mutation.')}><Text style={styles.destructiveText}>Cancel session</Text></Pressable></View></>:null}</ScrollView>}

function ProfileScreen({go}){const[editing,setEditing]=useState(false),[name,setName]=useState(UAT_IDENTITY.displayName);return <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><TopBar title="Profile"/><Text style={styles.eyebrow}>YOUR SESSIONS IDENTITY</Text><Text style={styles.title}>One account,{`\n`}authorized contexts.</Text><View style={styles.identityCard}><Text style={styles.strong}>{name}</Text><Text style={[styles.body,{marginTop:4}]}>{UAT_IDENTITY.contact}</Text><View style={{marginTop:12}}><SecondaryButton onPress={()=>setEditing(true)}>Edit profile preview</SecondaryButton></View></View><View style={styles.section}><SectionHead eyebrow="WORKSPACES" title="Same resources, different composition." action={<Pressable onPress={()=>go('workspace')}><Text style={styles.linkText}>Manage</Text></Pressable>}/>{UAT_IDENTITY.contexts.map(context=><Pressable key={context.type} disabled={!context.authorized} onPress={()=>context.type==='provider'?go('provider'):go('workspace')} style={[styles.identityCard,!context.authorized&&styles.contextLocked]}><View style={styles.between}><View style={{flex:1}}><Text style={styles.strong}>{context.label}</Text><Text style={styles.small}>{context.detail}</Text></View><Text style={styles.strong}>{context.authorized?'›':'Locked'}</Text></View></Pressable>)}</View><View style={styles.section}><Pressable style={styles.resultCard} onPress={()=>go('diagnostics')}><View style={styles.between}><View><Text style={styles.strong}>Native diagnostics</Text><Text style={styles.small}>Runtime, release and security checks</Text></View><Text style={styles.strong}>›</Text></View></Pressable></View><Modal visible={editing} transparent animationType="slide" onRequestClose={()=>setEditing(false)}><KeyboardAvoidingView style={styles.modalShade} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.modalCard}><Text style={styles.modalTitle}>Profile preview</Text><TextInput value={name} onChangeText={setName} autoCapitalize="words" returnKeyType="done" style={styles.field}/><View style={{marginTop:12,gap:8}}><PrimaryButton onPress={()=>setEditing(false)}>Save preview</PrimaryButton><SecondaryButton onPress={()=>setEditing(false)}>Cancel</SecondaryButton></View><Text style={[styles.small,{marginTop:12}]}>Preview state is local-only and is never written as identity authority.</Text></View></KeyboardAvoidingView></Modal></ScrollView>}

function WorkspaceScreen({back,go}){return <ScrollView contentContainerStyle={styles.scrollNoTabs}><TopBar title="Workspaces" onBack={back}/><Text style={styles.eyebrow}>PHASE 2–3</Text><Text style={styles.title}>Authorized contexts.</Text><Text style={[styles.body,{marginTop:7}]}>Workspace membership projects the canonical identity model. It never creates separate native roles.</Text>{WORKSPACE_CONTEXTS.map(context=>{const authorized=context.access!=='authorized-only';return <Pressable key={context.type} disabled={!authorized} onPress={()=>context.type==='provider'?go('provider'):undefined} style={[styles.identityCard,!authorized&&styles.contextLocked]}><View style={styles.between}><View style={{flex:1}}><Text style={styles.strong}>{context.label}</Text><Text style={styles.small}>{context.description}</Text><Text style={[styles.eyebrow,{marginTop:6}]}>{context.access}</Text></View><Text style={styles.strong}>{authorized?'›':'Locked'}</Text></View></Pressable>})}<View style={styles.section}><Notice>Corporate is never public self-selection. It appears only after trusted invitation/staff assignment or an already-authorized corporate context.</Notice></View></ScrollView>}

function ProviderScreen({back}){const[tab,setTab]=useState('today');const requested=UAT_PROVIDER_BOOKINGS.filter(item=>item.status==='requested');return <View style={styles.screen}><View style={styles.providerHeader}><Pressable accessibilityRole="button" accessibilityLabel="Back to customer app" onPress={back} style={[styles.back,{alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.12)',marginBottom:8}]}><Text style={{color:'#fff',fontSize:22}}>‹</Text></Pressable><Text style={styles.providerEyebrow}>PROVIDER MODE · PHASE 4–5</Text><Text style={styles.providerHeading}>Today at OneVibe Studiox</Text></View><View style={styles.providerTabs}>{PROVIDER_TABS.map(item=><Pressable key={item.key} onPress={()=>setTab(item.key)} style={styles.providerTab}><Text style={[styles.providerTabText,tab===item.key&&styles.providerTabTextActive]}>{item.label}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.scrollNoTabs} refreshControl={<RefreshControl refreshing={false} onRefresh={()=>{}}/>}>{tab==='today'?<><SectionHead eyebrow="TODAY" title="Session timeline"/>{UAT_PROVIDER_BOOKINGS.filter(item=>item.date==='Today').map(item=><ProviderBooking key={item.id} item={item}/>)}</>:null}{tab==='requests'?<><SectionHead eyebrow="NEEDS ACTION" title={`${requested.length} waiting`}/>{requested.map(item=><ProviderBooking key={item.id} item={item} actions/>)}</>:null}{tab==='rooms'?<><SectionHead eyebrow="ROOMS" title="What’s running."/>{UAT_STUDIOS[0].rooms.map(room=><View key={room.id} style={styles.resultCard}><View style={styles.between}><View><Text style={styles.strong}>{room.name}</Text><Text style={styles.small}>Capacity {room.capacity}</Text></View><Text style={styles.statusText}>LIVE</Text></View></View>)}</>:null}{tab==='more'?<><SectionHead eyebrow="PROVIDER TOOLS" title="Mobile for today. Desktop for setup."/><Text style={styles.body}>Pricing, recurring schedules, staff administration, reports and long-range configuration remain intentionally desktop/PWA.</Text><View style={styles.section}><Notice>Native provider scope is bounded to today’s sessions, booking requests, room status and urgent actions. This is deliberate Phase 4 classification, not missing parity.</Notice></View></>:null}</ScrollView></View>}
function ProviderBooking({item,actions=false}){return <View style={styles.sessionCard}><View style={styles.between}><View><Text style={styles.eyebrow}>{item.date} · {item.time}</Text><Text style={[styles.strong,{fontSize:18,marginTop:4}]}>{item.room}</Text><Text style={styles.small}>{item.name} · {item.size} people · {item.duration}</Text></View><StatePill value={item.status}/></View>{actions?<View style={styles.quickActions}><View style={{flex:1}}><Pressable style={styles.destructive} onPress={()=>Alert.alert('Decline request?','This UAT build will not send a privileged mutation without Sessions native authentication.')}><Text style={styles.destructiveText}>Decline</Text></Pressable></View><View style={{flex:1}}><PrimaryButton onPress={()=>Alert.alert('Accept request?','This UAT build will not send a privileged mutation without Sessions native authentication.')}>Accept</PrimaryButton></View></View>:null}</View>}

function DiagnosticsScreen({back}){
  const[release,setRelease]=useState({status:'idle',value:null,error:null});const[probe,setProbe]=useState({status:'idle',value:null,error:null});
  const runRelease=async()=>{setRelease({status:'loading',value:null,error:null});try{const value=await verifyRelease();setRelease({status:'success',value,error:null})}catch(error){setRelease({status:'error',value:null,error:String(error)})}};
  const runProbe=async()=>{setProbe({status:'loading',value:null,error:null});try{const value=await probeProtectedEndpoint();setProbe({status:'success',value,error:null})}catch(error){setProbe({status:'error',value:null,error:String(error)})}};
  useEffect(()=>{void runRelease()},[]);
  return <ScrollView contentContainerStyle={styles.scrollNoTabs}><TopBar title="Native diagnostics" onBack={back}/><Text style={styles.eyebrow}>STAGE N0–N5 EVIDENCE</Text><Text style={styles.title}>Real native runtime.</Text><Text style={[styles.body,{marginTop:7}]}>Platform: {Platform.OS} {String(Platform.Version)} · API: {UAT_ORIGIN}</Text><View style={styles.diagnosticCard}><Text style={styles.eyebrow}>RUNTIME</Text><Text style={styles.strong}>React Native installed application</Text><Text style={[styles.small,{marginTop:4}]}>No Sessions PWA/WebView application shell is present.</Text></View><View style={[styles.diagnosticCard,release.value?.matches&&styles.diagnosticOk,release.status==='error'&&styles.diagnosticBad]}><Text style={styles.eyebrow}>/api/release</Text>{release.status==='loading'?<ActivityIndicator/>:<Text selectable style={styles.code}>{release.error||JSON.stringify(release.value?.release||SESSIONS_RELEASE,null,2)}</Text>}<View style={{marginTop:10}}><SecondaryButton onPress={runRelease}>Verify Phase 5 backend</SecondaryButton></View></View><View style={[styles.diagnosticCard,probe.value?.protected&&styles.diagnosticOk,probe.value&&!probe.value.protected&&styles.diagnosticBad]}><Text style={styles.eyebrow}>PROTECTED ENDPOINT</Text><Text style={styles.small}>Anonymous GET /api/corporate/overview must return 401/403.</Text>{probe.status==='loading'?<ActivityIndicator/>:probe.value||probe.error?<Text selectable style={[styles.code,{marginTop:8}]}>{probe.error||JSON.stringify(probe.value,null,2)}</Text>:null}<View style={{marginTop:10}}><SecondaryButton onPress={runProbe}>Run anonymous security probe</SecondaryButton></View></View><View style={styles.section}><SectionHead eyebrow="PARITY" title="Phase 1–5 ledger"/>{Object.entries(PHASE_1_5_PARITY).map(([phase,value])=><View key={phase} style={styles.infoCard}><Text style={styles.strong}>Phase {phase} · {value.name}</Text><Text style={styles.small}>iOS {value.ios} · Android {value.android} · PWA {value.pwa} · Desktop {value.desktop}</Text></View>)}</View><View style={styles.section}><Notice>Auth boundary: {NATIVE_AUTH_BOUNDARY.status}. ChatGPT Sites audience cookies are not native authentication. Forbidden Sessions test project: {NATIVE_AUTH_BOUNDARY.forbiddenProject}.</Notice></View></ScrollView>;
}

function CustomerTabs({route,onTab}){const active=['studio','booking'].includes(route.name)?'search':route.name==='session'?'sessions':route.name==='diagnostics'||route.name==='workspace'?'profile':route.name;return <View style={styles.tabBar}>{CUSTOMER_TABS.map(tab=><Pressable key={tab.key} accessibilityRole="tab" accessibilityState={{selected:active===tab.key}} onPress={()=>onTab(tab.key)} style={styles.tab}><Text style={[styles.tabGlyph,active===tab.key&&styles.tabGlyphActive]}>{GLYPHS[tab.key]}</Text><Text style={[styles.tabLabel,active===tab.key&&styles.tabLabelActive]}>{tab.label}</Text></Pressable>)}</View>}

export default function App(){
  const[stack,setStack]=useState([initialRoute]);const route=stack[stack.length-1];
  const go=(name,params={})=>setStack(current=>[...current,{name,params}]);
  const back=()=>setStack(current=>current.length>1?current.slice(0,-1):current);
  const onTab=name=>setStack([{name,params:{}}]);
  useEffect(()=>{if(Platform.OS!=='android')return;const subscription=BackHandler.addEventListener('hardwareBackPress',()=>{if(stack.length<=1)return false;back();return true});return()=>subscription.remove()},[stack.length]);
  let content;
  if(route.name==='search')content=<SearchScreen go={go}/>;else if(route.name==='sessions')content=<SessionsScreen go={go}/>;else if(route.name==='profile')content=<ProfileScreen go={go}/>;else if(route.name==='studio')content=<StudioScreen route={route} go={go} back={back}/>;else if(route.name==='booking')content=<BookingScreen route={route} back={back}/>;else if(route.name==='session')content=<SessionScreen route={route} back={back}/>;else if(route.name==='workspace')content=<WorkspaceScreen back={back} go={go}/>;else if(route.name==='provider')content=<ProviderScreen back={back}/>;else if(route.name==='diagnostics')content=<DiagnosticsScreen back={back}/>;else content=<HomeScreen go={go}/>;
  const customerTabs=!['provider','booking','studio','session','workspace','diagnostics'].includes(route.name);
  return <SafeAreaProvider initialMetrics={initialWindowMetrics}><SafeAreaView edges={['top','right','bottom','left']} style={[styles.safe,route.name==='provider'&&{backgroundColor:DESIGN_TOKENS.color.ink}]}><StatusBar barStyle={route.name==='provider'?'light-content':'dark-content'} backgroundColor={route.name==='provider'?DESIGN_TOKENS.color.ink:DESIGN_TOKENS.color.white}/><View style={styles.app}>{content}{customerTabs?<CustomerTabs route={route} onTab={onTab}/>:null}</View></SafeAreaView></SafeAreaProvider>;
}
