import {z} from 'zod';
import {getProductionUser} from '@/app/chatgpt-auth';
import {database} from '@/db/store';
import {isRegistryUserOperator} from '@/db/registry-store';
import {readLoyaltyCreditSetting,type LoyaltyCreditSetting} from '@/lib/retention';

const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
class Fault extends Error{constructor(message:string,public status:number){super(message)}}
async function operationsUser(){const user=await getProductionUser();if(!user)return null;if(!isRegistryUserOperator(user))throw new Fault('Operations role required',403);return user;}
const settingsSchema=z.object({key:z.string().uuid(),enabled:z.boolean(),creditCents:z.number().int().min(0).max(100000),revision:z.number().int().min(0)}).superRefine((value,ctx)=>{if(value.enabled&&value.creditCents<1)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Enabled loyalty credit needs a positive amount'});});
export async function GET(){try{if(!await operationsUser())return response({error:'Sign in to Sessions to continue'},401);return response({setting:await readLoyaltyCreditSetting()});}catch(error){return response({error:error instanceof Error?error.message:'Unable to load loyalty settings'},403)}}
export async function POST(request:Request){try{const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)return response({error:'Cross-origin request rejected'},403);const user=await operationsUser();if(!user)return response({error:'Sign in to Sessions to continue'},401);if(Number(request.headers.get('content-length')||0)>4000)return response({error:'Request too large'},413);const raw=await request.text();if(raw.length>4000)return response({error:'Request too large'},413);const input=settingsSchema.parse(JSON.parse(raw));const current=await readLoyaltyCreditSetting(),db=database();const duplicate=await db.prepare('SELECT content FROM loyalty_credit_events WHERE actor=? AND idempotency_key=?').bind(user.id,input.key).first();if(duplicate)return response({...JSON.parse(duplicate.content),duplicate:true});if(current.revision!==input.revision)return response({error:'Loyalty credit settings changed. Refresh and try again.'},409);const now=new Date().toISOString();const setting:LoyaltyCreditSetting={...current,enabled:input.enabled,creditCents:input.creditCents,revision:current.revision+1,updatedAt:now,updatedBy:user.id};const result={ok:true,setting},guard=crypto.randomUUID();await db.batch([db.prepare('INSERT INTO operation_guards(id,valid) VALUES(?,(SELECT CASE WHEN revision=? THEN 1 ELSE 0 END FROM loyalty_credit_settings WHERE id=?))').bind(guard,input.revision,current.id),db.prepare('UPDATE loyalty_credit_settings SET enabled=?,credit_cents=?,revision=revision+1,content=? WHERE id=? AND revision=?').bind(input.enabled?1:0,input.creditCents,JSON.stringify(setting),current.id,input.revision),db.prepare('INSERT INTO loyalty_credit_events(id,actor,idempotency_key,created_at,content) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),user.id,input.key,now,JSON.stringify(result)),db.prepare('DELETE FROM operation_guards WHERE id=?').bind(guard)]);return response(result);}catch(error){const message=error instanceof z.ZodError?error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`).join('; '):error instanceof Error?error.message:'Unable to save loyalty settings';return response({error:message},error instanceof Fault?error.status:400)}}
