import {z} from 'zod';
import {getProductionUser} from '@/app/chatgpt-auth';
import {database} from '@/db/store';
import {readRegistry,seedRegistry,isRegistryUserOperator} from '@/db/registry-store';
import {type Studio,type Staff,type Claim,type StudioBooking,type StudioSettlement,type RegistryIssue,type VerificationRequest,registrySlotReason} from '@/lib/registry';
import {timestamp,localDate,addDays} from '@/lib/domain';
import {registrationAction} from '@/db/registrations';
import {memberForDate,sessionPrice,type StudioMember} from '@/lib/discovery';
import {syncPlatformCalendar} from '@/lib/google-calendar-server';
import {provisionStudioMembership} from '@/lib/supabase-admin';
import {normalizeZimbabwePhone} from '@/lib/identity-core';
import {settlementPricing} from '@/lib/commerce';
import {resolveFeePolicy} from '@/lib/commerce-server';
import {quoteRoomBooking} from '@/lib/booking-quote';
import {readLoyaltyCreditSetting,type BookingSeries,type MembershipLedgerEntry} from '@/lib/retention';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
class Fault extends Error{constructor(message:string,public status=400){super(message)}}
function fail(message:string,status=400):never{throw new Fault(message,status)}
const text=z.string().trim();const id=text.min(1).max(100);const https=z.union([z.literal(''),z.string().url().startsWith('https://').max(1000)]);
const mediaUrl=z.string().regex(/^\/api\/media\/[0-9a-f-]{36}$/,'Use a photo uploaded to this studio workspace');
const addOnSchema=z.object({id:id,name:text.min(2).max(100),price:z.number().int().min(0).max(100000),commissionable:z.boolean(),available:z.boolean()});
const roomSchema=z.object({id:id,name:text.min(2).max(100),price:z.number().int().min(100).max(100000),capacity:z.number().int().min(1).max(200),open:z.number().int().min(0).max(1410).multipleOf(30),close:z.number().int().min(30).max(1440).multipleOf(30),days:z.array(z.number().int().min(0).max(6)).min(1).max(7),buffer:z.number().int().min(0).max(120).multipleOf(30),minimum:z.number().int().min(30).max(480).multipleOf(30),deposit:z.number().int().min(0).max(100000).optional(),addOns:z.array(addOnSchema).max(12).optional(),photos:z.array(mediaUrl).max(5).optional()}).refine(r=>r.close-r.open>=r.minimum+r.buffer,'Hours must accommodate the minimum session and buffer').refine(r=>new Set((r.addOns||[]).map(value=>value.id)).size===(r.addOns||[]).length,'Each add-on needs a unique ID');
export async function GET(req:Request){try{const user=await getProductionUser();return response(await readRegistry(user,new URL(req.url).searchParams.get('studio')||undefined));}catch(e){console.error('Registry load failed',e instanceof Error?e.message:'Unknown error');return response({error:'The studio registry is temporarily unavailable. Please retry.'},503)}}
export async function POST(req:Request){
 try{
 const origin=req.headers.get('Origin');if(origin&&origin!==new URL(req.url).origin)fail('Cross-origin request rejected',403);
 const user=await getProductionUser();if(!user)fail('Sign in to Sessions to continue',401);const email=user.id;const contactEmail=user.email?.toLowerCase()||'';const contactPhone=user.phone||'';const identityContacts=[contactEmail,contactPhone].filter(Boolean);
 if(Number(req.headers.get('content-length')||0)>40000)fail('Request too large',413);
 const rawText=await req.text();if(rawText.length>40000)fail('Request too large',413);let p:any;try{p=JSON.parse(rawText)}catch{fail('Invalid JSON')};
 z.object({type:text.min(1).max(40)}).parse(p);await seedRegistry();const db=database();const operator=isRegistryUserOperator(user);const now=new Date().toISOString();
 const registration=await registrationAction(p,email,operator);if(registration)return registration;
 const audit=(studioId:string,event:string)=>db.prepare('INSERT INTO studio_audit(id,studio_id,actor,event,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),studioId,email,event,now);
 if(p.type==='addStudio'){
 if(!operator)fail('Registry operator access required',403);const v=z.object({name:text.min(3).max(120),area:text.min(2).max(80),address:text.min(5).max(300),description:text.min(30).max(2000),category:z.enum(['Rehearsal studio','Recording studio','Music institution','Production facility']),source:z.string().url().startsWith('https://').max(1000),sourceTitle:text.min(3).max(120)}).parse(p);
 const newId='studio-'+crypto.randomUUID();const s:Studio={id:newId,name:v.name,area:v.area,address:v.address,description:v.description,category:v.category,services:[v.category==='Rehearsal studio'?'Rehearsal':'Recording'],website:'',phone:'',email:'',sources:[{title:v.sourceTitle,url:v.source,checked:now.slice(0,10),kind:'Public directory',note:'Added after operator review'}],status:'unclaimed',bookingEnabled:false,rooms:[],equipment:'',rules:'',location:null,revision:0};
 const duplicate=await db.prepare("SELECT id FROM studio_registry WHERE lower(json_extract(content,'$.name'))=lower(?)").bind(v.name).first();if(duplicate)fail('A studio with this name already exists',409);
 await db.batch([db.prepare('INSERT INTO studio_registry(id,content) VALUES(?,?)').bind(newId,JSON.stringify(s)),audit(newId,'add sourced studio')]);return response({ok:true,studio:s});
 }
 if(p.type==='issue'){
 const v=z.object({studioId:text.max(100),kind:z.enum(['correction','suggestion','removal']),text:text.min(15).max(2000),source:https}).parse(p);
 const count=await db.prepare("SELECT count(*) n FROM studio_issues WHERE reporter=? AND json_extract(content,'$.status')='open'").bind(email).first();if(count.n>=20)fail('Please wait for your existing suggestions to be reviewed.',429);
 const issue:RegistryIssue={...v,id:crypto.randomUUID(),status:'open',createdAt:now,reporter:email};await db.prepare('INSERT INTO studio_issues(id,reporter,content) VALUES(?,?,?)').bind(issue.id,email,JSON.stringify(issue)).run();return response({ok:true});
 }
 if(p.type==='resolveIssue'){
 if(!operator)fail('Registry operator access required',403);const v=z.object({id}).parse(p);const row=await db.prepare('SELECT content FROM studio_issues WHERE id=?').bind(v.id).first();if(!row)fail('Issue not found',404);const issue=JSON.parse(row.content);issue.status='resolved';await db.batch([db.prepare('UPDATE studio_issues SET content=? WHERE id=?').bind(JSON.stringify(issue),v.id),audit(issue.studioId,'resolve registry issue')]);return response({ok:true});
 }
 const studioId=id.parse(p.studioId);const row=await db.prepare('SELECT * FROM studio_registry WHERE id=?').bind(studioId).first();if(!row)fail('Studio not found',404);const studio:Studio={...JSON.parse(row.content),revision:row.revision};
 const identityMembership=user.memberships.find(value=>value.organizationId===studioId&&value.active);const identityReady=user.method==='chatgpt_demo'||!!identityMembership;
 const owner=row.owner===email&&identityReady&&(user.method==='chatgpt_demo'||identityMembership?.role==='owner');const membership=identityContacts.length?await db.prepare("SELECT * FROM studio_staff WHERE studio_id=? AND email IN (?,?) AND status='active'").bind(studioId,identityContacts[0]||'',identityContacts[1]||'').first():null;const manager=owner||identityReady&&membership?.role==='manager';
 const statements:any[]=[];let result:Record<string,unknown>={ok:true};let calendarBooking:StudioBooking|undefined;
 const own=()=>{if(!owner)fail('Only the verified studio owner can do this',403)};const manage=()=>{if(!manager)fail('Studio manager access required',403)};
 const bookingRow=async()=>{const r=await db.prepare('SELECT content FROM studio_bookings WHERE id=? AND studio_id=?').bind(id.parse(p.id),studioId).first();if(!r)fail('Booking not found',404);return JSON.parse(r.content) as StudioBooking};
 if(p.type==='claim'){
 if(studio.hidden||row.owner)fail('This profile cannot be claimed. Use Report a problem for ownership disputes.',409);
 const v=z.object({name:text.min(2).max(120),role:text.min(2).max(120),phone:text.min(7).max(40),evidence:text.min(30).max(2000),authorized:z.literal(true)}).parse(p);
 const existing=await db.prepare('SELECT * FROM studio_claim_requests WHERE studio_id=? AND applicant=?').bind(studioId,email).first();if(existing?.status==='pending')fail('You already have a pending claim for this studio',409);
 const n=await db.prepare("SELECT count(*) n FROM studio_claim_requests WHERE applicant=? AND status='pending'").bind(email).first();if(n.n>=5)fail('Please wait for your pending claims to be reviewed.',429);
 const claim:Claim={id:existing?.id||crypto.randomUUID(),studioId,applicant:email,name:v.name,role:v.role,phone:v.phone,evidence:v.evidence,code:'SESSIONS-'+crypto.randomUUID().slice(0,8).toUpperCase(),status:'pending',createdAt:now};
 statements.push(db.prepare('INSERT INTO studio_claim_requests(id,studio_id,applicant,status,content) VALUES(?,?,?,?,?) ON CONFLICT(studio_id,applicant) DO UPDATE SET status=excluded.status,content=excluded.content').bind(claim.id,studioId,email,'pending',JSON.stringify(claim)));result={ok:true,claim};
 }else if(p.type==='reviewClaim'){
 if(!operator)fail('Registry operator access required',403);
 const v=z.object({id,decision:z.enum(['approved','rejected']),note:text.min(20).max(2000),independentContact:z.literal(true),authorityChecked:z.literal(true)}).parse(p);
 const r=await db.prepare('SELECT * FROM studio_claim_requests WHERE id=? AND studio_id=?').bind(v.id,studioId).first();if(!r||r.status!=='pending')fail('This claim is no longer pending',409);const claim:Claim=JSON.parse(r.content);if(claim.applicant===email)fail('You cannot review your own ownership claim',403);if(row.owner&&v.decision==='approved')fail('This studio already has an owner',409);
 Object.assign(claim,{status:v.decision,note:v.note,reviewedBy:email,reviewedAt:now});statements.push(db.prepare('UPDATE studio_claim_requests SET status=?,content=? WHERE id=?').bind(v.decision,JSON.stringify(claim),claim.id));
 if(v.decision==='approved'){await provisionStudioMembership({studioId,studioName:studio.name,userId:claim.applicant,role:'owner',grantedBy:user.id});studio.status='claimed';delete studio.verifiedAt;statements.push(db.prepare('UPDATE studio_registry SET owner=? WHERE id=? AND owner IS NULL').bind(claim.applicant,studioId));const competing=(await db.prepare("SELECT * FROM studio_claim_requests WHERE studio_id=? AND id!=? AND status='pending'").bind(studioId,claim.id).all()).results;for(const c of competing){const value=JSON.parse(c.content);Object.assign(value,{status:'rejected',note:'Another ownership claim was approved. Use the correction form to dispute ownership.',reviewedAt:now});statements.push(db.prepare('UPDATE studio_claim_requests SET status=?,content=? WHERE id=?').bind('rejected',JSON.stringify(value),c.id));}}
 }else if(p.type==='submitVerification'){
 own();if(!['claimed','pending_verification'].includes(studio.status))fail(studio.status==='bookable'||studio.status==='verified'?'This studio is already verified':'Claim ownership before submitting verification',409);
	 const v=z.object({legalName:text.min(2).max(120),evidenceType:z.enum(['official_channel','registration','premises']),registrationNumber:text.max(100),contactPhone:text.min(7).max(40),evidence:text.min(30).max(2000),evidenceMediaId:z.string().uuid().optional(),consent:z.literal(true)}).parse(p);
	 const pending=await db.prepare("SELECT id FROM studio_verification_requests WHERE studio_id=? AND status='pending'").bind(studioId).first();if(pending)fail('A verification request is already under review',409);
	 if(v.evidenceMediaId){const media=await db.prepare("SELECT id FROM uploads WHERE id=? AND owner=? AND studio_id=? AND purpose='studio_verification'").bind(v.evidenceMediaId,email,studioId).first();if(!media)fail('That private evidence file does not belong to this studio workspace',403);}
	 const verification:VerificationRequest={id:crypto.randomUUID(),studioId,applicant:email,legalName:v.legalName,evidenceType:v.evidenceType,registrationNumber:v.registrationNumber||undefined,contactPhone:v.contactPhone,evidence:v.evidence,evidenceMediaId:v.evidenceMediaId,status:'pending',createdAt:now};
 studio.status='pending_verification';statements.push(db.prepare('INSERT INTO studio_verification_requests(id,studio_id,applicant,status,content) VALUES(?,?,?,?,?)').bind(verification.id,studioId,email,'pending',JSON.stringify(verification)));result={ok:true,verification};
 }else if(p.type==='reviewVerification'){
 if(!operator)fail('Registry operator access required',403);const v=z.object({id,decision:z.enum(['approved','rejected']),note:text.min(20).max(2000),businessChecked:z.literal(true),premisesChecked:z.literal(true)}).parse(p);
 const r=await db.prepare('SELECT * FROM studio_verification_requests WHERE id=? AND studio_id=?').bind(v.id,studioId).first();if(!r||r.status!=='pending')fail('This verification request is no longer pending',409);const verification:VerificationRequest=JSON.parse(r.content);if(verification.applicant===email)fail('You cannot review your own studio verification',403);
 Object.assign(verification,{status:v.decision,note:v.note,reviewedAt:now,reviewedBy:email});statements.push(db.prepare('UPDATE studio_verification_requests SET status=?,content=? WHERE id=?').bind(v.decision,JSON.stringify(verification),v.id));
 if(v.decision==='approved'){studio.status='verified';studio.verifiedAt=now}else{studio.status='claimed';delete studio.verifiedAt}result={ok:true,verification};
 }else if(p.type==='profile'){
 own();const v=z.object({description:text.min(30).max(2000),address:text.min(10).max(300),area:text.min(2).max(80),website:https,phone:text.min(7).max(40),email:z.union([z.literal(''),z.string().email().max(200)]),equipment:text.max(2000),rules:text.max(2000),services:z.array(text.min(2).max(50)).min(1).max(12),location:z.object({lat:z.number().min(-18.2).max(-17.4),lng:z.number().min(30.6).max(31.5)}).nullable(),rooms:z.array(roomSchema).max(12),bookingEnabled:z.boolean()}).parse(p);
	 if(new Set(v.rooms.map(r=>r.id)).size!==v.rooms.length)fail('Each room must have a unique ID');if(v.bookingEnabled&&!['verified','bookable'].includes(studio.status))fail('Operations verification is required before this studio can take bookings',409);if(v.bookingEnabled&&(!v.rooms.length||!v.location||v.rules.length<20))fail('Add a room, confirmed map pin and booking rules before enabling requests');
	 for(const room of v.rooms){if(new Set(room.photos||[]).size!==(room.photos||[]).length)fail('A room photo can only be added once');for(const photo of room.photos||[]){const mediaId=photo.split('/').pop();const media=await db.prepare("SELECT id FROM uploads WHERE id=? AND owner=? AND studio_id=? AND room_id=? AND purpose='studio_room_photo'").bind(mediaId,email,studioId,room.id).first();if(!media)fail('A room photo does not belong to this studio and room',403);}}
 const future=(await db.prepare('SELECT content FROM studio_bookings WHERE studio_id=?').bind(studioId).all()).results.map((r:any)=>JSON.parse(r.content) as StudioBooking).filter((b:StudioBooking)=>['requested','confirmed'].includes(b.status));
 if(future.length&&JSON.stringify(v.rooms)!==JSON.stringify(studio.rooms))fail('Resolve existing requests and bookings before changing room schedules or rates. Contact details can still be edited.',409);
 Object.assign(studio,v,{updatedAt:now,status:v.bookingEnabled?'bookable':studio.status==='bookable'?'verified':studio.status});delete studio.publicLocation;
 }else if(p.type==='memberPlans'){
 own();const v=z.object({plans:z.array(z.object({id:id,name:text.min(2).max(80),fee:z.number().int().min(0).max(100000),termDays:z.number().int().min(1).max(366),discountPercent:z.number().int().min(0).max(50),priority:z.boolean(),benefits:text.min(10).max(600),active:z.boolean()})).max(5)}).parse(p);
 if(new Set(v.plans.map(x=>x.id)).size!==v.plans.length)fail('Each membership plan needs a unique ID');studio.memberPlans=v.plans;studio.updatedAt=now;
 }else if(p.type==='joinMembership'){
 const v=z.object({planId:id,name:text.min(2).max(120),consent:z.literal(true)}).parse(p);if(studio.hidden||!row.owner)fail('Memberships require a claimed studio',409);
 const plan=studio.memberPlans?.find(x=>x.id===v.planId&&x.active);if(!plan)fail('This membership plan is not available',409);
 const old=await db.prepare('SELECT content FROM studio_members WHERE studio_id=? AND customer=?').bind(studioId,email).first();const existing:StudioMember|undefined=old?JSON.parse(old.content):undefined;
 if(existing&&(existing.status==='requested'||existing.status==='active'&&!!existing.expiresOn&&existing.expiresOn>=localDate()))fail('You already have an active or pending membership here',409);
 const member:StudioMember={id:existing?.id||crypto.randomUUID(),studioId,customer:email,name:v.name,plan,status:'requested',createdAt:now};
 statements.push(db.prepare('INSERT INTO studio_members(id,studio_id,customer,content) VALUES(?,?,?,?) ON CONFLICT(studio_id,customer) DO UPDATE SET content=excluded.content').bind(member.id,studioId,email,JSON.stringify(member)));result={ok:true,membership:member};
 }else if(p.type==='reviewMembership'){
 own();const v=z.object({id,decision:z.enum(['active','declined']),note:text.min(10).max(500),paymentConfirmed:z.boolean(),paymentMethod:z.enum(['ecocash','bank_transfer','cash','other']).optional()}).parse(p);
 const r=await db.prepare('SELECT content FROM studio_members WHERE id=? AND studio_id=?').bind(v.id,studioId).first();if(!r)fail('Membership not found',404);const member:StudioMember=JSON.parse(r.content);if(member.status!=='requested')fail('This request was already reviewed',409);
 if(v.decision==='active'&&member.plan.fee>0&&!v.paymentConfirmed)fail('Confirm the agreed fee was collected outside Sessions before activating');
 member.status=v.decision;member.note=v.note;if(v.decision==='active'){member.startsOn=localDate();member.expiresOn=addDays(member.startsOn,member.plan.termDays-1);if(member.plan.fee>0){const ledger:MembershipLedgerEntry={id:'ML-'+crypto.randomUUID(),studioId,membershipId:member.id,customer:member.customer,kind:'membership_settlement',amount:member.plan.fee,method:v.paymentMethod||'other',occurredAt:now,note:'Studio owner recorded an off-platform membership settlement.'};statements.push(db.prepare('INSERT INTO membership_ledger(id,studio_id,membership_id,customer,kind,amount_cents,method,idempotency_key,occurred_at,content) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(ledger.id,studioId,member.id,member.customer,ledger.kind,ledger.amount,ledger.method,'membership-activation:'+member.id,now,JSON.stringify(ledger)));}}
 statements.push(db.prepare('UPDATE studio_members SET content=? WHERE id=?').bind(JSON.stringify(member),v.id));result={ok:true,membership:member};
 }else if(p.type==='cancelMembership'){
 const v=z.object({id,consent:z.literal(true)}).parse(p);const r=await db.prepare('SELECT content FROM studio_members WHERE id=? AND studio_id=?').bind(v.id,studioId).first();if(!r)fail('Membership not found',404);const member:StudioMember=JSON.parse(r.content);if(!owner&&member.customer!==email)fail('Membership belongs to another account',403);
 member.status='cancelled';member.note='Membership ended. Existing booking prices remain unchanged. Settle any externally paid fee directly with the studio.';
 statements.push(db.prepare('UPDATE studio_members SET content=? WHERE id=?').bind(JSON.stringify(member),v.id));
 }else if(p.type==='inviteStaff'){
  own();const v=z.object({contact:text.min(7).max(320),role:z.enum(['manager','staff']),title:text.min(2).max(100)}).parse({...p,contact:p.contact||p.email});let inviteContact:string;let inviteEmail:string|undefined;if(v.contact.includes('@')){inviteContact=z.string().email().max(200).parse(v.contact).toLowerCase();inviteEmail=inviteContact}else{try{inviteContact=normalizeZimbabwePhone(v.contact)}catch{fail('Enter a valid Zimbabwe phone number or email address')}}
  const count=await db.prepare('SELECT count(*) n FROM studio_staff WHERE studio_id=?').bind(studioId).first();if(count.n>=50)fail('Team limit reached',429);
  const staff:Staff={id:crypto.randomUUID(),studioId,inviteContact,email:inviteEmail,role:v.role,title:v.title,name:'',bio:'',skills:'',status:'invited',public:false};statements.push(db.prepare('INSERT INTO studio_staff(id,studio_id,email,status,role,content) VALUES(?,?,?,?,?,?)').bind(staff.id,studioId,inviteContact,'invited',v.role,JSON.stringify(staff)));result={ok:true,staff};
 }else if(p.type==='staffProfile'){
  const v=z.object({id,name:text.min(2).max(120),title:text.min(2).max(100),bio:text.max(1000),skills:text.max(300),public:z.boolean(),consent:z.literal(true)}).parse(p);
  if(!identityContacts.length)fail('Add and verify a phone number or email before accepting an invitation',409);const r=await db.prepare('SELECT * FROM studio_staff WHERE id=? AND studio_id=? AND email IN (?,?)').bind(v.id,studioId,identityContacts[0]||'',identityContacts[1]||'').first();if(!r)fail('This invitation belongs to another account',403);
 const staff:Staff={...JSON.parse(r.content),name:v.name,title:v.title,bio:v.bio,skills:v.skills,public:v.public,status:'active',joinedAt:now};await provisionStudioMembership({studioId,studioName:studio.name,userId:user.id,role:staff.role,grantedBy:row.owner});statements.push(db.prepare("UPDATE studio_staff SET status='active',content=? WHERE id=?").bind(JSON.stringify(staff),v.id));
 }else if(p.type==='removeStaff'){
  const v=z.object({id}).parse(p);const r=await db.prepare('SELECT * FROM studio_staff WHERE id=? AND studio_id=?').bind(v.id,studioId).first();if(!r)fail('Team member not found',404);if(!owner&&!identityContacts.includes(r.email))fail('Only the owner or team member can remove this membership',403);
 const assigned=(await db.prepare('SELECT content FROM studio_bookings WHERE studio_id=?').bind(studioId).all()).results.map((b:any)=>JSON.parse(b.content));for(const b of assigned.filter((b:any)=>b.staffId===v.id)){b.staffId='';statements.push(db.prepare('UPDATE studio_bookings SET content=? WHERE id=?').bind(JSON.stringify(b),b.id));}statements.push(db.prepare('DELETE FROM studio_staff WHERE id=?').bind(v.id));
 }else if(p.type==='book'){
 const v=z.object({key:z.string().uuid(),roomId:id,date:text.regex(/^\d{4}-\d{2}-\d{2}$/),start:z.number().int(),duration:z.number().int().min(30).max(480),size:z.number().int().min(1).max(200),name:text.min(2).max(120),phone:text.min(7).max(40),note:text.max(1000),addOns:z.array(z.object({id,quantity:z.number().int().min(1).max(12)})).max(12).default([]),useLoyaltyCredit:z.boolean().default(false),terms:z.literal(true)}).parse(p);
 const existing=await db.prepare('SELECT content FROM studio_bookings WHERE customer=? AND request_key=?').bind(email,v.key).first();if(existing)return response({ok:true,booking:JSON.parse(existing.content)});
 if(studio.status!=='bookable'||!row.owner||!studio.bookingEnabled||studio.hidden)fail('This studio is not accepting Sessions booking requests',409);
 const room=studio.rooms.find(r=>r.id===v.roomId);if(!room)fail('Room not found',404);if(v.size>room.capacity)fail('Your group exceeds the room capacity');
 const all=(await db.prepare('SELECT content FROM studio_bookings WHERE studio_id=?').bind(studioId).all()).results.map((r:any)=>JSON.parse(r.content));if(all.filter((b:StudioBooking)=>b.customer===email&&b.status==='requested').length>=10)fail('Please wait for your current requests to be reviewed.',429);const reason=registrySlotReason(studio,room,v.date,v.start,v.duration,all);if(reason)fail(reason,409);
 const members=(await db.prepare('SELECT content FROM studio_members WHERE studio_id=? AND customer=?').bind(studioId,email).all()).results.map((m:any)=>JSON.parse(m.content));
 const calculated=sessionPrice(room.price,v.duration,memberForDate(members,studioId,v.date));const loyaltySetting=await readLoyaltyCreditSetting();let loyaltyCreditCents=0;if(v.useLoyaltyCredit){if(!loyaltySetting.enabled||loyaltySetting.creditCents<=0)fail('Loyalty credit is not currently enabled',409);const balance=await db.prepare('SELECT balance_cents FROM studio_loyalty_balances WHERE studio_id=? AND customer=?').bind(studioId,email).first();loyaltyCreditCents=Math.min(Number(balance?.balance_cents||0),calculated.price);if(!loyaltyCreditCents)fail('No loyalty credit is available for this studio',409);}
 const policy=await resolveFeePolicy(studioId,room.id,v.date);const quote=quoteRoomBooking(room,v.duration,v.addOns,policy,calculated.price-loyaltyCreditCents);
 const booking:StudioBooking={id:'RS-'+crypto.randomUUID(),studioId,roomId:room.id,roomName:room.name,customer:email,name:v.name,phone:v.phone,date:v.date,start:v.start,duration:v.duration,size:v.size,note:v.note,staffId:'',status:'requested',...calculated,price:quote.roomSubtotal,loyaltyCreditCents:loyaltyCreditCents||undefined,pricing:quote.pricing,addOns:quote.addOns,quotedAt:now,createdAt:now};
 statements.push(db.prepare('INSERT INTO studio_bookings(id,studio_id,customer,request_key,content) VALUES(?,?,?,?,?)').bind(booking.id,studioId,email,v.key,JSON.stringify(booking)));for(let m=v.start;m<v.start+v.duration+room.buffer;m+=30)statements.push(db.prepare('INSERT INTO studio_booking_slots(studio_id,room_id,date,minute,booking_id) VALUES(?,?,?,?,?)').bind(studioId,room.id,v.date,m,booking.id));result={ok:true,booking};
 if(loyaltyCreditCents){const creditGuard=crypto.randomUUID(),ledger:MembershipLedgerEntry={id:'ML-'+crypto.randomUUID(),studioId,customer:email,bookingId:booking.id,kind:'loyalty_redemption',amount:loyaltyCreditCents,occurredAt:now,note:'Credit reserved for a Sessions booking request.'};statements.push(db.prepare('INSERT INTO operation_guards(id,valid) VALUES(?,(SELECT CASE WHEN COALESCE((SELECT balance_cents FROM studio_loyalty_balances WHERE studio_id=? AND customer=?),0)>=? THEN 1 ELSE 0 END))').bind(creditGuard,studioId,email,loyaltyCreditCents),db.prepare('UPDATE studio_loyalty_balances SET balance_cents=balance_cents-?,updated_at=? WHERE studio_id=? AND customer=?').bind(loyaltyCreditCents,now,studioId,email),db.prepare('INSERT INTO membership_ledger(id,studio_id,customer,booking_id,kind,amount_cents,idempotency_key,occurred_at,content) VALUES(?,?,?,?,?,?,?,?,?)').bind(ledger.id,studioId,email,booking.id,ledger.kind,ledger.amount,'loyalty-redemption:'+booking.id,now,JSON.stringify(ledger)),db.prepare('DELETE FROM operation_guards WHERE id=?').bind(creditGuard));}
 }else if(p.type==='bookSeries'){
 const v=z.object({key:z.string().uuid(),roomId:id,date:text.regex(/^\d{4}-\d{2}-\d{2}$/),start:z.number().int(),duration:z.number().int().min(30).max(480),size:z.number().int().min(1).max(200),name:text.min(2).max(120),phone:text.min(7).max(40),note:text.max(1000),addOns:z.array(z.object({id,quantity:z.number().int().min(1).max(12)})).max(12).default([]),occurrences:z.number().int().min(2).max(12),terms:z.literal(true)}).parse(p);
 const existing=await db.prepare('SELECT content FROM booking_series WHERE customer=? AND request_key=?').bind(email,v.key).first();if(existing)return response({ok:true,series:JSON.parse(existing.content),duplicate:true});if(v.date<localDate()||addDays(v.date,(v.occurrences-1)*7)>addDays(localDate(),365))fail('Choose a weekly series within the next year');if(studio.status!=='bookable'||!row.owner||!studio.bookingEnabled||studio.hidden)fail('This studio is not accepting Sessions booking requests',409);const room=studio.rooms.find(value=>value.id===v.roomId);if(!room)fail('Room not found',404);if(v.size>room.capacity)fail('Your group exceeds the room capacity');
 const all=(await db.prepare('SELECT content FROM studio_bookings WHERE studio_id=?').bind(studioId).all()).results.map((value:any)=>JSON.parse(value.content) as StudioBooking);if(all.filter((value:StudioBooking)=>value.customer===email&&value.status==='requested').length+v.occurrences>10)fail('Please wait for your current requests to be reviewed.',429);const members=(await db.prepare('SELECT content FROM studio_members WHERE studio_id=? AND customer=?').bind(studioId,email).all()).results.map((value:any)=>JSON.parse(value.content) as StudioMember);const seriesId='SER-'+crypto.randomUUID(),bookings:StudioBooking[]=[];
 for(let index=0;index<v.occurrences;index++){const date=addDays(v.date,index*7),reason=registrySlotReason(studio,room,date,v.start,v.duration,[...all,...bookings]);if(reason)fail(`Week ${index+1} (${date}) cannot be requested: ${reason}`,409);const calculated=sessionPrice(room.price,v.duration,memberForDate(members,studioId,date));const policy=await resolveFeePolicy(studioId,room.id,date);const quote=quoteRoomBooking(room,v.duration,v.addOns,policy,calculated.price);bookings.push({id:'RS-'+crypto.randomUUID(),studioId,roomId:room.id,roomName:room.name,customer:email,name:v.name,phone:v.phone,date,start:v.start,duration:v.duration,size:v.size,note:v.note,staffId:'',status:'requested',seriesId,seriesIndex:index+1,seriesCount:v.occurrences,...calculated,price:quote.roomSubtotal,pricing:quote.pricing,addOns:quote.addOns,quotedAt:now,createdAt:now});}
 const series:BookingSeries={id:seriesId,studioId,customer:email,requestKey:v.key,status:'requested',bookingIds:bookings.map(value=>value.id),occurrences:v.occurrences,createdAt:now};statements.push(db.prepare('INSERT INTO booking_series(id,studio_id,customer,request_key,status,created_at,content) VALUES(?,?,?,?,?,?,?)').bind(series.id,studioId,email,v.key,series.status,now,JSON.stringify(series)));for(const booking of bookings){statements.push(db.prepare('INSERT INTO studio_bookings(id,studio_id,customer,request_key,content) VALUES(?,?,?,?,?)').bind(booking.id,studioId,email,`${v.key}:${booking.seriesIndex}`,JSON.stringify(booking)));for(let minute=booking.start;minute<booking.start+booking.duration+room.buffer;minute+=30)statements.push(db.prepare('INSERT INTO studio_booking_slots(studio_id,room_id,date,minute,booking_id) VALUES(?,?,?,?,?)').bind(studioId,room.id,booking.date,minute,booking.id));}result={ok:true,series,bookings};
 }else if(p.type==='bookingStatus'){
 const v=z.object({id,status:z.enum(['confirmed','declined','cancelled','completed']),staffId:text.max(100).optional()}).parse(p);const b=await bookingRow();const previousStatus=b.status;
 const settlementRow=await db.prepare('SELECT revision,content FROM studio_settlements WHERE booking_id=? AND studio_id=?').bind(b.id,studioId).first();const settlement:StudioSettlement|undefined=settlementRow?{...JSON.parse(settlementRow.content),revision:settlementRow.revision}:undefined;
 if(v.status==='cancelled'){if(b.customer!==email&&!manager)fail('This booking belongs to another account',403);if(!['requested','confirmed'].includes(b.status))fail('This booking cannot be cancelled',409);if(settlement&&['settled_off_platform','disputed'].includes(settlement.status))fail('Open a settlement dispute before cancelling a paid booking',409)}else{manage();if(v.status==='completed'){if(b.status!=='confirmed'||timestamp(b.date,b.start+b.duration)>Date.now())fail('Only a finished confirmed session can be completed',409);if(settlement?.status!=='settled_off_platform')fail('Record the direct studio payment before completing this booking',409)}else if(b.status!=='requested')fail('Only a pending request can be accepted or declined',409)}
 if(v.staffId){manage();const staff=await db.prepare("SELECT * FROM studio_staff WHERE id=? AND studio_id=? AND status='active'").bind(v.staffId,studioId).first();if(!staff)fail('Select an active member of this studio');b.staffId=v.staffId;}
 b.status=v.status;statements.push(db.prepare('UPDATE studio_bookings SET content=? WHERE id=?').bind(JSON.stringify(b),b.id));if(['cancelled','declined'].includes(v.status))statements.push(db.prepare('DELETE FROM studio_booking_slots WHERE booking_id=?').bind(b.id));
 if(v.status==='confirmed'){
  const pricing=b.pricing||settlementPricing(b.price);const value:StudioSettlement={id:'SET-'+crypto.randomUUID(),bookingId:b.id,studioId,customer:b.customer,status:'awaiting_payment',revision:0,pricing,createdAt:now,updatedAt:now};
  statements.push(db.prepare('INSERT INTO studio_settlements(id,booking_id,studio_id,customer,status,room_subtotal_cents,addon_subtotal_cents,gross_cents,customer_fee_cents,studio_fee_cents,platform_fee_cents,customer_total_cents,deposit_due_cents,studio_net_cents,currency,created_at,updated_at,content) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(value.id,b.id,studioId,b.customer,value.status,pricing.roomSubtotal,pricing.addOnSubtotal,pricing.gross,pricing.customerFee,pricing.studioFee,pricing.platformFee,pricing.customerTotal,pricing.depositDue,pricing.studioNet,pricing.currency,now,now,JSON.stringify(value)));
  statements.push(db.prepare('INSERT INTO settlement_events(id,settlement_id,studio_id,actor,event,idempotency_key,created_at,content) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),value.id,studioId,email,'created','booking-confirmed:'+b.id,now,JSON.stringify({bookingId:b.id,pricing})));
  result={ok:true,booking:b,settlement:value};
 }else if(v.status==='cancelled'&&settlement){
  const settlementGuard=crypto.randomUUID();settlement.status='cancelled';settlement.updatedAt=now;
  statements.push(db.prepare('INSERT INTO operation_guards(id,valid) VALUES(?,(SELECT CASE WHEN revision=? THEN 1 ELSE 0 END FROM studio_settlements WHERE id=?))').bind(settlementGuard,settlement.revision,settlement.id));
  statements.push(db.prepare('UPDATE studio_settlements SET status=?,revision=revision+1,updated_at=?,content=? WHERE id=?').bind(settlement.status,now,JSON.stringify({...settlement,revision:settlement.revision+1}),settlement.id));
  statements.push(db.prepare('INSERT INTO settlement_events(id,settlement_id,studio_id,actor,event,idempotency_key,created_at,content) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),settlement.id,studioId,email,'cancelled','booking-cancelled:'+b.id,now,JSON.stringify({bookingId:b.id})));
  statements.push(db.prepare('DELETE FROM operation_guards WHERE id=?').bind(settlementGuard));
 }
 if(['declined','cancelled'].includes(v.status)&&b.loyaltyCreditCents){const ledger:MembershipLedgerEntry={id:'ML-'+crypto.randomUUID(),studioId,customer:b.customer,bookingId:b.id,kind:'loyalty_reversal',amount:b.loyaltyCreditCents,occurredAt:now,note:'Credit reservation released because the booking did not proceed.'};statements.push(db.prepare('INSERT INTO membership_ledger(id,studio_id,customer,booking_id,kind,amount_cents,idempotency_key,occurred_at,content) VALUES(?,?,?,?,?,?,?,?,?)').bind(ledger.id,studioId,b.customer,b.id,ledger.kind,ledger.amount,'loyalty-reversal:'+b.id,now,JSON.stringify(ledger)),db.prepare('INSERT INTO studio_loyalty_balances(studio_id,customer,balance_cents,updated_at) VALUES(?,?,?,?) ON CONFLICT(studio_id,customer) DO UPDATE SET balance_cents=balance_cents+excluded.balance_cents,updated_at=excluded.updated_at').bind(studioId,b.customer,b.loyaltyCreditCents,now));}
 if(v.status==='completed'){
  if(b.membershipId){const attendance:MembershipLedgerEntry={id:'ML-'+crypto.randomUUID(),studioId,membershipId:b.membershipId,customer:b.customer,bookingId:b.id,kind:'attendance',amount:0,occurredAt:now,note:'Completed Sessions booking counted toward this studio membership.',seriesId:b.seriesId};statements.push(db.prepare('INSERT INTO membership_ledger(id,studio_id,membership_id,customer,booking_id,kind,amount_cents,idempotency_key,occurred_at,content) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(attendance.id,studioId,b.membershipId,b.customer,b.id,attendance.kind,0,'membership-attendance:'+b.id,now,JSON.stringify(attendance)));}
  const loyaltySetting=await readLoyaltyCreditSetting();if(loyaltySetting.enabled&&loyaltySetting.creditCents>0){const credit:MembershipLedgerEntry={id:'ML-'+crypto.randomUUID(),studioId,customer:b.customer,bookingId:b.id,kind:'loyalty_credit',amount:loyaltySetting.creditCents,occurredAt:now,note:'Platform loyalty credit earned from a completed Sessions booking.',seriesId:b.seriesId};statements.push(db.prepare('INSERT INTO membership_ledger(id,studio_id,customer,booking_id,kind,amount_cents,idempotency_key,occurred_at,content) VALUES(?,?,?,?,?,?,?,?,?)').bind(credit.id,studioId,b.customer,b.id,credit.kind,credit.amount,'loyalty-credit:'+b.id,now,JSON.stringify(credit)),db.prepare('INSERT INTO studio_loyalty_balances(studio_id,customer,balance_cents,updated_at) VALUES(?,?,?,?) ON CONFLICT(studio_id,customer) DO UPDATE SET balance_cents=balance_cents+excluded.balance_cents,updated_at=excluded.updated_at').bind(studioId,b.customer,credit.amount,now));}
 }
 if(v.status==='confirmed'||v.status==='completed'||v.status==='cancelled'&&previousStatus==='confirmed'){
  calendarBooking={...b};statements.push(db.prepare("INSERT INTO studio_calendar_events(booking_id,studio_id,event_id,status,updated_at,content) VALUES(?,?,?,?,?,?) ON CONFLICT(booking_id) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at,content=excluded.content").bind(b.id,studioId,'','awaiting_setup',now,JSON.stringify({bookingStatus:b.status,queued:true,lastError:''})));
 }
 if(v.status!=='confirmed')result={ok:true,booking:b};
 }else if(p.type==='correctStudio'){
 if(!operator)fail('Registry operator access required',403);const v=z.object({name:text.min(3).max(120),area:text.min(2).max(80),address:text.min(5).max(300),notice:text.min(20).max(500),source:z.string().url().startsWith('https://').max(1000),sourceTitle:text.min(3).max(120)}).parse(p);
 const addressChanged=studio.address!==v.address;Object.assign(studio,{name:v.name,area:v.area,address:v.address,notice:v.notice,updatedAt:now});if(addressChanged){studio.location=null;studio.bookingEnabled=false;}studio.sources=[...studio.sources.slice(-19),{title:v.sourceTitle,url:v.source,checked:now.slice(0,10),kind:'Public directory',note:'Operator correction'}];
 }else if(p.type==='visibility'){
 if(!operator)fail('Registry operator access required',403);const v=z.object({hidden:z.boolean(),note:text.min(20).max(500)}).parse(p);studio.hidden=v.hidden;studio.notice=v.note;if(v.hidden)studio.bookingEnabled=false;
 }else fail('Unknown action');
 const guard=crypto.randomUUID();const check=db.prepare('INSERT INTO operation_guards(id,valid) VALUES(?,(SELECT CASE WHEN revision=? THEN 1 ELSE 0 END FROM studio_registry WHERE id=?))').bind(guard,row.revision,studioId);
 await db.batch([check,...statements,db.prepare('UPDATE studio_registry SET content=?,revision=revision+1 WHERE id=?').bind(JSON.stringify(studio),studioId),audit(studioId,p.type),db.prepare('DELETE FROM operation_guards WHERE id=?').bind(guard)]);
 if(calendarBooking){try{result.calendar=await syncPlatformCalendar(studio,calendarBooking)}catch(error){console.error('Calendar sync could not be recorded',error instanceof Error?error.message:'Unknown error');result.calendar={status:'failed'}}}
 return response(result);
 }catch(e){if(e instanceof Fault)return response({error:e.message},e.status);if(e instanceof z.ZodError)return response({error:e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')},400);if(e instanceof Error&&/UNIQUE|CHECK|constraint/i.test(e.message))return response({error:'This record changed or already exists. Refresh and try again.'},409);console.error('Registry operation failed',e instanceof Error?e.message:'Unknown error');return response({error:'Unable to save this change. Please retry.'},503)}
}
