'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import QRCode from 'qrcode';
import {Bell,Calendar,Check,Clipboard,ImagePlus,MessageCircle,MessagesSquare,Send,Share2,WifiOff} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Field,CheckField,Empty} from './registry-ui';
import {sessionFetch} from '@/lib/supabase-browser';
import {money,prettyDate,timeLabel} from '@/lib/domain';
import type {BookingMessage,BookingNotification,BookingVoucher,RegistryState,Studio,StudioBooking} from '@/lib/registry';

const sharePath=(voucher:BookingVoucher)=>`${window.location.origin}/voucher/${voucher.token}`;

export function BookingProofActions({booking,studio,voucher,cacheForOffline=false}:{booking:StudioBooking;studio?:Studio;voucher?:BookingVoucher;cacheForOffline?:boolean}){
 const[qr,setQr]=useState(''),[working,setWorking]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{if(!voucher||voucher.status!=='active')return;const url=sharePath(voucher);void QRCode.toDataURL(url,{width:260,margin:1,errorCorrectionLevel:'M',color:{dark:'#17324d',light:'#ffffff'}}).then(setQr).catch(()=>setNotice('QR code could not be prepared. Use the booking reference instead.'));},[voucher?.token,voucher?.status]);
 const download=async()=>{setWorking('calendar');try{const response=await sessionFetch(`/api/bookings/${encodeURIComponent(booking.id)}/calendar`);if(!response.ok){const value=await response.json();throw new Error(value.error)}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`sessions-${booking.id}.ics`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){setNotice(error instanceof Error?error.message:'Calendar file unavailable')}finally{setWorking('')}};
 const copy=async()=>{if(!voucher)return;try{await navigator.clipboard.writeText(sharePath(voucher));setNotice('Shareable booking voucher link copied.')}catch{setNotice('Copy is unavailable in this browser.')}};
 const share=async()=>{if(!voucher)return;const url=sharePath(voucher),text=`Sessions booking ${voucher.reference}: ${voucher.studioName}, ${prettyDate(voucher.date)} at ${timeLabel(voucher.start)} CAT.`;try{if(navigator.share){await navigator.share({title:'Sessions booking voucher',text,url});setNotice('Booking voucher ready to share.')}else await copy();}catch{}};
 if(!voucher||voucher.status!=='active'||!['confirmed','completed'].includes(booking.status))return null;
 return <section className="r-booking-proof" aria-label="Booking voucher and calendar options"><div><span className="r-badge claimed"><Check size={13}/>Confirmed booking voucher</span><h4>{voucher.reference}</h4><p>{studio?.name||voucher.studioName} · {prettyDate(voucher.date)} · {timeLabel(voucher.start)} CAT</p><small>Not proof of payment or admission. Confirm the live booking before travelling.</small></div>{qr&&<img className="r-voucher-qr" src={qr} alt={`Scannable Sessions booking voucher QR code for ${voucher.reference}`}/>}<div className="r-button-row"><Button type="button" variant="outline" onClick={()=>void download()} disabled={working==='calendar'}><Calendar size={15}/>{working==='calendar'?'Preparing…':'Add to calendar'}</Button><Button type="button" variant="outline" onClick={()=>void copy()}><Clipboard size={15}/>Copy voucher</Button><Button type="button" variant="outline" onClick={()=>void share()}><Share2 size={15}/>Share</Button></div>{cacheForOffline&&<p className="r-small"><WifiOff size={14}/>This confirmed reference is saved for this device after you open My sessions. Offline copies never confirm a live reservation or payment.</p>}{notice&&<p className="r-small" role="status">{notice}</p>}</section>;
}

async function uploadAttachment(file:File,booking:StudioBooking){const form=new FormData();form.set('file',file);form.set('purpose','booking_message_attachment');form.set('studioId',booking.studioId);form.set('bookingId',booking.id);const response=await sessionFetch('/api/upload',{method:'POST',body:form}),value=await response.json();if(!response.ok)throw new Error(value.error||'Image upload failed');return value as {id:string;url:string};}

export function BookingThread({booking,data,onChanged,embedded=false}:{booking:StudioBooking;data:RegistryState;onChanged?:()=>void;embedded?:boolean}){
 const currentRecipient=booking.customer===data.user?.id?(data.user?.id||''):`studio:${booking.studioId}`;const initial=useMemo(()=>((data.bookingMessages||[]).filter(message=>message.bookingId===booking.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))),[data.bookingMessages,booking.id]);const[messages,setMessages]=useState<BookingMessage[]>(initial),[body,setBody]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{setMessages(initial)},[initial]);
 useEffect(()=>{let active=true;void sessionFetch(`/api/booking-communications?booking=${encodeURIComponent(booking.id)}&studio=${encodeURIComponent(booking.studioId)}`).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(active)setMessages(value.messages)}).catch(()=>{});void sessionFetch('/api/booking-communications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'markRead',bookingId:booking.id,studioId:booking.studioId})}).then(()=>onChanged?.()).catch(()=>{});return()=>{active=false};},[booking.id,booking.studioId]);
 const send=async(event:FormEvent)=>{event.preventDefault();if(!body.trim()&&!file)return;setBusy(true);setNotice('');try{const attachment=file?await uploadAttachment(file,booking):undefined;const response=await sessionFetch('/api/booking-communications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'send',bookingId:booking.id,studioId:booking.studioId,key:crypto.randomUUID(),body,attachmentMediaId:attachment?.id})}),value=await response.json();if(!response.ok)throw new Error(value.error);setMessages(current=>[...current,value.message]);setBody('');setFile(null);setNotice('Message saved in Sessions.');onChanged?.();}catch(error){setNotice(error instanceof Error?error.message:'Message could not be sent')}finally{setBusy(false)}};
 const whatsapp=async()=>{const popup=window.open('about:blank','_blank','noopener');setBusy(true);try{const response=await sessionFetch('/api/booking-communications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'whatsappLink',bookingId:booking.id,studioId:booking.studioId,key:crypto.randomUUID()})}),value=await response.json();if(!response.ok)throw new Error(value.error);if(popup)popup.location.href=value.href;else window.location.assign(value.href);setNotice('WhatsApp opened. Review and send the message yourself.');}catch(error){popup?.close();setNotice(error instanceof Error?error.message:'WhatsApp link unavailable')}finally{setBusy(false)}};
 return <section className={'r-thread '+(embedded?'embedded':'')}><div className="r-section-top"><div><span className="r-badge"><MessagesSquare size={13}/>Booking inbox</span><h3>{booking.roomName} · {prettyDate(booking.date)}</h3><p className="r-small">Messages stay with this booking. Sessions never sends WhatsApp on your behalf.</p></div><Button type="button" variant="outline" disabled={busy} onClick={()=>void whatsapp()}><MessageCircle size={15}/>WhatsApp</Button></div><div className="r-thread-messages" aria-live="polite">{messages.length?messages.map(message=><article key={message.id} className={message.sender===data.user?.id?'mine':''}><strong>{message.sender===data.user?.id?'You':message.senderSide==='studio'?'Studio team':'Musician / band'}</strong>{message.body&&<p>{message.body}</p>}{message.attachmentMediaId&&<a href={'/api/media/'+message.attachmentMediaId} target="_blank" rel="noreferrer"><img src={'/api/media/'+message.attachmentMediaId} alt="Booking message attachment" loading="lazy"/>Open image</a>}<small>{new Date(message.createdAt).toLocaleString('en-GB',{timeZone:'Africa/Harare'})} CAT</small></article>):<Empty title="Start the conversation">Use this private thread for arrival, access and booking questions. Do not send card or bank details.</Empty>}</div>{['requested','confirmed','completed'].includes(booking.status)&&<form className="r-thread-compose" onSubmit={event=>void send(event)}><Field label="Message"><textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000} placeholder="Ask about arrival, equipment or access…"/></Field><label className="r-secondary"><ImagePlus size={15}/>{file?file.name:'Attach image'}<input className="r-visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><Button disabled={busy||(!body.trim()&&!file)}><Send size={15}/>{busy?'Sending…':'Send in Sessions'}</Button></form>}{notice&&<p className="r-small" role="status">{notice}</p>}<small className="r-muted">Thread recipient: {currentRecipient.startsWith('studio:')?'studio team':'your account'}.</small></section>;
}

export function BookingNotificationFeed({data}:{data:RegistryState}){const notifications=(data.notifications||[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,40);if(!notifications.length)return <section className="r-notification-feed"><div className="r-section-top"><div><span className="r-badge"><Bell size={13}/>In-app updates</span><h2>Booking updates</h2></div><a className="r-link" href="/notifications">Notification settings</a></div><p className="r-muted">Booking updates will appear here when the studio accepts, records a direct-payment change, sends a message, or a reminder is due.</p></section>;return <section className="r-notification-feed"><div className="r-section-top"><div><span className="r-badge"><Bell size={13}/>In-app updates</span><h2>Booking updates</h2></div><a className="r-link" href="/notifications">Notification settings</a></div>{notifications.map((notification:BookingNotification)=><article key={notification.id}><Bell size={16}/><div><p>{notification.content}</p><small>{new Date(notification.createdAt).toLocaleString('en-GB',{timeZone:'Africa/Harare'})} CAT</small></div></article>)}</section>}

export function NotificationPreferences({data,onChanged}:{data:RegistryState;onChanged?:()=>void}){
 const initial=data.notificationPreference,[emailConsent,setEmailConsent]=useState(initial?.emailConsent||false),[reminderConsent,setReminderConsent]=useState(initial?.reminderConsent||false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{setEmailConsent(initial?.emailConsent||false);setReminderConsent(initial?.reminderConsent||false)},[initial?.revision]);if(!data.emailRemindersConfigured||!data.user?.email)return null;
 const save=async()=>{setBusy(true);setNotice('');try{const response=await sessionFetch('/api/notification-preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:crypto.randomUUID(),revision:initial?.revision||0,emailConsent,reminderConsent})}),value=await response.json();if(!response.ok)throw new Error(value.error);setNotice('Email reminder preferences saved.');onChanged?.();}catch(error){setNotice(error instanceof Error?error.message:'Preferences could not be saved')}finally{setBusy(false)}};
 return <section className="r-panel r-form"><span className="r-badge"><Bell size={13}/>Optional email reminders</span><h3>Choose email reminders</h3><p className="r-small">Email is optional. In-app booking updates remain available in Sessions.</p><CheckField checked={emailConsent} onChange={setEmailConsent}>I consent to booking emails at {data.user.email}.</CheckField><CheckField checked={reminderConsent} onChange={setReminderConsent} disabled={!emailConsent}>Send a reminder around 24 hours and 2 hours before a confirmed booking.</CheckField><Button type="button" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save preferences'}</Button>{notice&&<p className="r-small" role="status">{notice}</p>}</section>;
}
