'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,CalendarDays,Minus,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Field,Choice,CheckField,type RegistryAction} from './registry-ui';
import {type RegistryState,type Studio,type StudioBooking} from '@/lib/registry';
import {localDate,addDays,timeLabel,money} from '@/lib/domain';
import {registrySlotReason} from '@/lib/registry';
import {sessionFetch} from '@/lib/supabase-browser';

type Quote={roomSubtotal:number;addOns:{id:string;name:string;price:number;quantity:number;commissionable:boolean}[];pricing:{gross:number;customerFee:number;studioFee:number;customerTotal:number;depositDue:number;policy:{payer:string}}};
export default function BookingRequestV3({studio,data,mutate,busy}:{studio:Studio;data:RegistryState;mutate:RegistryAction;busy:boolean}){
 const [roomId,setRoomId]=useState(studio.rooms[0]?.id||''),[groupSize,setGroupSize]=useState(1),[date,setDate]=useState(addDays(localDate(),1)),[start,setStart]=useState<number|null>(null),[duration,setDuration]=useState(studio.rooms[0]?.minimum||60),[occurrences,setOccurrences]=useState(1),[useLoyaltyCredit,setUseLoyaltyCredit]=useState(false),[terms,setTerms]=useState(false),[key,setKey]=useState(()=>crypto.randomUUID()),[counts,setCounts]=useState<Record<string,number>>({}),[quote,setQuote]=useState<Quote|null>(null),[quoteError,setQuoteError]=useState('');
 const room=studio.rooms.find(value=>value.id===roomId);const addOns=useMemo(()=>Object.entries(counts).filter(([,quantity])=>quantity>0).map(([id,quantity])=>({id,quantity})),[counts]);const addOnKey=JSON.stringify(addOns);
 const loyaltyBalance=(data.membershipLedger||[]).filter(entry=>entry.studioId===studio.id&&entry.customer===data.user?.id).reduce((total,entry)=>total+(entry.kind==='loyalty_redemption'?-entry.amount:entry.kind==='loyalty_credit'||entry.kind==='loyalty_reversal'?entry.amount:0),0);const creditEnabled=!!data.loyaltyCreditSetting?.enabled&&data.loyaltyCreditSetting.creditCents>0;const plannedCredit=occurrences===1&&useLoyaltyCredit&&quote?Math.min(loyaltyBalance,quote.roomSubtotal):0;
 useEffect(()=>{let active=true;if(!room){setQuote(null);return}const timer=window.setTimeout(()=>{void sessionFetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studioId:studio.id,roomId:room.id,date,duration,addOns,clientKey:key})}).then(async response=>{const body=await response.json();if(!active)return;if(!response.ok)throw new Error(body.error);setQuote(body.quote);setQuoteError('')}).catch(error=>{if(active){setQuote(null);setQuoteError(error instanceof Error?error.message:'Quote unavailable')}})},180);return()=>{active=false;window.clearTimeout(timer)}},[studio.id,room?.id,date,duration,addOnKey,key]);
 const changeRoom=(next:string)=>{const selected=studio.rooms.find(value=>value.id===next);setRoomId(next);setDuration(selected?.minimum||60);setStart(null);setCounts({});setGroupSize(1)};
 return <form className="r-panel r-form" id="real-booking" onSubmit={async event=>{event.preventDefault();if(!room||start===null)return;const values=Object.fromEntries(new FormData(event.currentTarget));const repeating=occurrences>1;try{await mutate({type:repeating?'bookSeries':'book',studioId:studio.id,roomId,date,start,duration,key,...values,size:Number(values.size),addOns,occurrences:repeating?occurrences:undefined,useLoyaltyCredit:!repeating&&useLoyaltyCredit,terms},repeating?`${occurrences} weekly requests saved together. The studio reviews each date.`:'Request saved. Wait for the studio to accept before travelling.');setKey(crypto.randomUUID());setStart(null);setCounts({});setUseLoyaltyCredit(false)}catch{}}}>
  <span className="r-badge claimed"><CalendarDays size={13}/>Accepting requests</span><h2>Make time for music.</h2><p className="r-small">All times CAT (UTC+2). A request holds the slot until the studio accepts or declines.</p>
  <Field label="Choose a room"><Choice label="Room" value={roomId} onChange={changeRoom} options={studio.rooms.map(value=>({value:value.id,label:`${value.name} · ${money(value.price)}/hr`}))}/></Field>
  <Field label="Date"><input type="date" required min={localDate()} max={addDays(localDate(),365)} value={date} onChange={event=>{setDate(event.target.value);setStart(null)}}/></Field>
  <Choice label="Repeat weekly" value={String(occurrences)} onChange={value=>{const count=Number(value);setOccurrences(count);if(count>1)setUseLoyaltyCredit(false)}} options={[{value:'1',label:'One session'},{value:'2',label:'2 weekly sessions'},{value:'3',label:'3 weekly sessions'},{value:'4',label:'4 weekly sessions'},{value:'5',label:'5 weekly sessions'},{value:'6',label:'6 weekly sessions'},{value:'7',label:'7 weekly sessions'},{value:'8',label:'8 weekly sessions'},{value:'9',label:'9 weekly sessions'},{value:'10',label:'10 weekly sessions'},{value:'11',label:'11 weekly sessions'},{value:'12',label:'12 weekly sessions'}]}/>{occurrences>1&&<p className="r-small">Sessions will validate every weekly date before saving anything. If one date is unavailable, no part of this series is created.</p>}
  <Field label="Duration"><Choice label="Duration" value={String(duration)} onChange={value=>{setDuration(Number(value));setStart(null)}} options={Array.from({length:16},(_,index)=>(index+1)*30).filter(value=>value>=(room?.minimum||30)).map(value=>({value:String(value),label:`${value} minutes`}))}/></Field>
  {room&&<div className="r-slots">{Array.from({length:Math.ceil((room.close-room.open)/30)},(_,index)=>room.open+index*30).map(value=>{const reason=registrySlotReason(studio,room,date,value,duration,(data.occupancy||[]) as StudioBooking[]);return <button type="button" key={value} disabled={!!reason} title={reason||'Request this time'} aria-pressed={start===value} className={start===value?'selected':''} onClick={()=>setStart(value)}>{timeLabel(value)}</button>})}</div>}
  {!!room?.addOns?.some(value=>value.available)&&<fieldset className="r-add-ons"><legend>Add-ons (optional)</legend>{room.addOns.filter(value=>value.available).map(addOn=>{const quantity=counts[addOn.id]||0;return <div key={addOn.id}><span><strong>{addOn.name}</strong><small>{money(addOn.price)} each</small></span><div><button type="button" aria-label={`Remove ${addOn.name}`} disabled={!quantity} onClick={()=>setCounts(current=>({...current,[addOn.id]:Math.max(0,(current[addOn.id]||0)-1)}))}><Minus size={15}/></button><output>{quantity}</output><button type="button" aria-label={`Add ${addOn.name}`} onClick={()=>setCounts(current=>({...current,[addOn.id]:Math.min(12,(current[addOn.id]||0)+1)}))}><Plus size={15}/></button></div></div>})}</fieldset>}
  <Field label="Group / customer name"><input name="name" required minLength={2} maxLength={120}/></Field><div className="r-form-grid"><Field label="Group size"><input name="size" type="number" min="1" max={room?.capacity} value={groupSize} onChange={event=>setGroupSize(Number(event.target.value))} required/></Field><Field label="Contact phone"><input name="phone" type="tel" required minLength={7} maxLength={40}/></Field></div><Field label="Session notes (optional)"><textarea name="note" maxLength={1000}/></Field>
  {quote?<div className="r-quote" aria-live="polite"><div><span>Room</span><strong>{money(quote.roomSubtotal)}</strong></div>{quote.addOns.map(line=><div key={line.id}><span>{line.name} × {line.quantity}</span><strong>{money(line.price*line.quantity)}</strong></div>)}{quote.pricing.customerFee>0&&<div><span>Sessions service fee</span><strong>{money(quote.pricing.customerFee)}</strong></div>}{quote.pricing.studioFee>0&&<div><span>Sessions fee (deducted from studio)</span><strong>{money(quote.pricing.studioFee)}</strong></div>}{plannedCredit>0&&<div><span>Sessions loyalty credit</span><strong>−{money(plannedCredit)}</strong></div>}<div className="r-quote-total"><span>{occurrences>1?'First-session total agreed with studio':'Total agreed with studio'}</span><strong>{money(quote.pricing.customerTotal-plannedCredit)}</strong></div>{occurrences>1&&<p>Each week is server-priced against its own date and saved separately in one all-or-nothing series.</p>}{quote.pricing.depositDue>0&&<p>Deposit due now: {money(quote.pricing.depositDue)}. This is part of the total, not an extra charge.</p>}</div>:<div className="r-total"><span>Calculating server quote</span><strong>{quoteError||'…'}</strong></div>}
  {creditEnabled&&loyaltyBalance>0&&<CheckField checked={useLoyaltyCredit} onChange={setUseLoyaltyCredit} disabled={occurrences>1}>Use {money(loyaltyBalance)} Sessions loyalty credit at this studio{occurrences>1?' · available for individual session requests only':''}</CheckField>}<p className="r-small">Pay the studio directly after it accepts. Sessions does not take or hold your money. Fees and add-ons shown here are a server-calculated quote and are saved with the booking.</p><CheckField checked={terms} onChange={setTerms}>I accept the studio’s terms and understand this is a request. If accepted, Sessions may add the studio, room, time, group size and booking reference to its private platform Google Calendar; my email, phone and notes are excluded.</CheckField>{data.user?<Button disabled={busy||!terms||start===null||!quote}>{occurrences>1?'Request weekly series':'Request session'}<ArrowRight size={16}/></Button>:<a className="r-primary" href={'/account?return_to='+encodeURIComponent('/studio/'+studio.id)}>Sign in to request</a>}
 </form>;
}
