'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Building2,Headphones,ReceiptText,RefreshCw,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {sessionFetch} from '@/lib/supabase-browser';

type Office='trust'|'finance'|'support'|'providers';
type AnyRecord=Record<string,any>;
const definitions={
 trust:{title:'Trust & safety',copy:'Review ownership claims and provider verification without receiving Finance or Support authority.',icon:ShieldCheck},
 finance:{title:'Finance',copy:'Review settlement exceptions and resolve disputes without access to private customer–studio messages.',icon:ReceiptText},
 support:{title:'Customer support',copy:'Resolve marketplace issues and monitor notification failures without receiving financial or verification authority.',icon:Headphones},
 providers:{title:'Provider operations',copy:'Review provider applications and onboarding readiness without becoming a studio owner.',icon:Building2},
} as const;

const endpoint=(office:Office)=>office==='finance'?'/api/settlements':`/api/corporate/${office}`;

export default function CorporateOffice({office}:{office:Office}){
 const def=definitions[office],Icon=def.icon;const[data,setData]=useState<AnyRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const response=await sessionFetch(endpoint(office),{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'Office queue unavailable');setData(value)}catch(e){setError(e instanceof Error?e.message:'Office queue unavailable')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[office]);
 const post=async(key:string,url:string,payload:unknown)=>{setBusy(key);setMessage('');try{const response=await sessionFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const value=await response.json();if(!response.ok)throw new Error(value.error||'Action failed');setMessage('Action recorded. The queue has been refreshed.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}};
 return <section className="r-width r-inner">
  <a className="r-back" href="/corporate"><ArrowLeft size={16}/>Corporate control centre</a>
  <div className="r-workspace-heading"><div><div className="r-eyebrow"><Icon size={16}/>SESSIONS CORPORATE OFFICE</div><h1>{def.title}</h1><p className="r-intro">{def.copy}</p></div><div className="r-panel"><strong>Office isolation</strong><p>Every read and mutation on this page is re-authorized by the server. Opening this URL does not grant the role.</p></div></div>
  {message&&<div className="r-panel" role="status"><strong>{message}</strong></div>}
  {loading?<div className="r-loading">Loading {def.title.toLowerCase()} queue…</div>:error?<div className="r-panel"><h2>Queue unavailable</h2><p>{error}</p><Button onClick={()=>void load()}><RefreshCw size={16}/>Retry</Button></div>:<OfficeQueue office={office} data={data||{}} busy={busy} post={post}/>} 
 </section>;
}

function DecisionForm({id,label,onSubmit,busy}:{id:string;label:string;onSubmit:(decision:'approved'|'rejected',note:string)=>void;busy:boolean}){
 const[note,setNote]=useState('');return <form className="r-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSubmit(form.get('decision') as 'approved'|'rejected',note)}}><label className="r-field"><span>Decision</span><select name="decision" defaultValue="approved"><option value="approved">Approve</option><option value="rejected">Reject</option></select></label><label className="r-field"><span>Review note</span><textarea value={note} onChange={event=>setNote(event.target.value)} minLength={20} maxLength={2000} required placeholder="Record the evidence checked and why this decision is justified."/></label><Button disabled={busy||note.trim().length<20}>{busy?'Recording…':label}</Button></form>
}

function OfficeQueue({office,data,busy,post}:{office:Office;data:AnyRecord;busy:string;post:(key:string,url:string,payload:unknown)=>Promise<void>}){
 if(office==='trust'){
  const claims=(data.claims||[]) as AnyRecord[],verifications=(data.verifications||[]) as AnyRecord[];return <><h2>Ownership claims <span className="r-count">{claims.length}</span></h2>{claims.length===0?<Empty text="No ownership claims are waiting."/>:<div className="r-studio-grid">{claims.map(item=><article className="r-panel" key={item.claim.id}><span className="r-badge">Ownership claim</span><h3>{item.studio.name}</h3><p><strong>Applicant:</strong> {item.claim.name} · {item.claim.role}</p><p><strong>Contact:</strong> {item.claim.phone}</p><p>{item.claim.evidence}</p><DecisionForm id={item.claim.id} label="Record claim decision" busy={busy===item.claim.id} onSubmit={(decision,note)=>void post(item.claim.id,'/api/corporate/trust',{type:'reviewClaim',studioId:item.studio.id,id:item.claim.id,decision,note,independentContact:true,authorityChecked:true})}/></article>)}</div>}<h2>Verification requests <span className="r-count">{verifications.length}</span></h2>{verifications.length===0?<Empty text="No studio verification requests are waiting."/>:<div className="r-studio-grid">{verifications.map(item=><article className="r-panel" key={item.verification.id}><span className="r-badge">Verification</span><h3>{item.studio.name}</h3><p><strong>Legal name:</strong> {item.verification.legalName}</p><p><strong>Evidence:</strong> {item.verification.evidenceType} · {item.verification.contactPhone}</p><p>{item.verification.evidence}</p>{item.verification.evidenceMediaId&&<a className="r-secondary" href={'/api/media/'+item.verification.evidenceMediaId} target="_blank" rel="noreferrer">Open private evidence</a>}<DecisionForm id={item.verification.id} label="Record verification decision" busy={busy===item.verification.id} onSubmit={(decision,note)=>void post(item.verification.id,'/api/corporate/trust',{type:'reviewVerification',studioId:item.studio.id,id:item.verification.id,decision,note,businessChecked:true,premisesChecked:true})}/></article>)}</div>}</>;
 }
 if(office==='providers'){
  const registrations=(data.registrations||[]) as AnyRecord[];return <><h2>Provider applications <span className="r-count">{registrations.length}</span></h2>{registrations.length===0?<Empty text="No provider applications are waiting."/>:<div className="r-studio-grid">{registrations.map(item=><article className="r-panel" key={item.id}><span className="r-badge">Provider application</span><h3>{item.name}</h3><p>{item.category} · {item.area}</p><p>{item.address}</p><p><strong>Representative:</strong> {item.representative} · {item.phone}</p><p>{item.evidence}</p><a className="r-secondary" href={item.website} target="_blank" rel="noreferrer">Review official website</a><DecisionForm id={item.id} label="Record provider decision" busy={busy===item.id} onSubmit={(decision,note)=>void post(item.id,'/api/corporate/providers',{type:'reviewRegistration',id:item.id,decision,note,independentContact:true,authorityChecked:true})}/></article>)}</div>}</>;
 }
 if(office==='support'){
  const issues=(data.issues||[]) as AnyRecord[],failed=(data.failedNotifications||[]) as AnyRecord[];return <><h2>Open marketplace issues <span className="r-count">{issues.length}</span></h2>{issues.length===0?<Empty text="No open registry issues."/>:<div className="r-studio-grid">{issues.map(item=><SupportIssue key={item.issue.id} item={item} busy={busy===item.issue.id} post={post}/>)}</div>}<h2>Failed notifications <span className="r-count">{failed.length}</span></h2>{failed.length===0?<Empty text="No failed booking notifications."/>:<div className="r-table-wrap"><table className="r-table"><thead><tr><th>Kind</th><th>Booking</th><th>Studio</th><th>Attempts</th><th>Created</th></tr></thead><tbody>{failed.map(item=><tr key={item.id}><td>{item.kind}</td><td>{item.bookingId}</td><td>{item.studioId}</td><td>{item.attempts}</td><td>{new Date(item.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</>;
 }
 const settlements=((data.settlements||[]) as AnyRecord[]).filter(item=>['disputed','proof_submitted','payment_declined','awaiting_payment'].includes(item.status));return <><div className="r-trust-row"><a href="/corporate" className="r-secondary">Corporate overview</a><a href="/registry-admin" className="r-secondary">Operations escalation</a></div><h2>Settlement attention queue <span className="r-count">{settlements.length}</span></h2>{settlements.length===0?<Empty text="No settlement records currently need Finance attention."/>:<div className="r-studio-grid">{settlements.map(item=><FinanceSettlement key={item.id} item={item} busy={busy===item.id} post={post}/>)}</div>}<div className="r-panel"><h2>Finance policy tools</h2><p>Fee policy and loyalty-credit APIs are now Finance-authorized. The dedicated policy editors can be opened from the full Operations console only when this account also has Operations authority; Finance-only accounts remain isolated here.</p></div></>;
}

function SupportIssue({item,busy,post}:{item:AnyRecord;busy:boolean;post:(key:string,url:string,payload:unknown)=>Promise<void>}){const[note,setNote]=useState('');return <article className="r-panel"><span className="r-badge">{item.issue.kind}</span><h3>{item.studio?.name||'Marketplace issue'}</h3><p>{item.issue.text}</p>{item.issue.source&&<a href={item.issue.source} target="_blank" rel="noreferrer">Review source</a>}<label className="r-field"><span>Resolution note</span><textarea value={note} onChange={e=>setNote(e.target.value)} minLength={10} maxLength={1000}/></label><Button disabled={busy||note.trim().length<10} onClick={()=>void post(item.issue.id,'/api/corporate/support',{type:'resolveIssue',id:item.issue.id,note})}>{busy?'Resolving…':'Resolve issue'}</Button></article>}
function FinanceSettlement({item,busy,post}:{item:AnyRecord;busy:boolean;post:(key:string,url:string,payload:unknown)=>Promise<void>}){const[note,setNote]=useState('');const disputed=item.status==='disputed';return <article className="r-panel"><span className="r-badge">{String(item.status).replaceAll('_',' ')}</span><h3>{item.bookingId}</h3><p><strong>Studio:</strong> {item.studioId}</p><p><strong>Customer total:</strong> US${((item.pricing?.customerTotal||0)/100).toFixed(2)} · <strong>Studio net:</strong> US${((item.pricing?.studioNet||0)/100).toFixed(2)}</p>{item.disputeReason&&<p>{item.disputeReason}</p>}{item.proofMediaId&&<a className="r-secondary" href={'/api/media/'+item.proofMediaId} target="_blank" rel="noreferrer">Open payment proof</a>}{disputed&&<><label className="r-field"><span>Resolution note</span><textarea value={note} onChange={e=>setNote(e.target.value)} minLength={20} maxLength={1000}/></label><Button disabled={busy||note.trim().length<20} onClick={()=>void post(item.id,'/api/settlements',{type:'resolveSettlementDispute',studioId:item.studioId,settlementId:item.id,revision:item.revision,key:crypto.randomUUID(),note})}>{busy?'Resolving…':'Resolve dispute'}</Button></>}</article>}
function Empty({text}:{text:string}){return <div className="r-panel"><p className="r-muted">{text}</p></div>}
