'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Building2,GitBranch,RefreshCw,ShieldCheck,UserRoundCog,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {sessionFetch} from '@/lib/supabase-browser';

type Department={id:string;code:string;name:string;parentDepartmentId:string|null;status:string;description:string};
type Position={id:string;departmentId:string;code:string;title:string;level:number;reportsToPositionId:string|null;isDepartmentHead:boolean;status:string;description:string};
type Staff={id:string;staffCode:string;positionId:string|null;status:string;displayName:string;location:string;startedAt:string|null;identityUserId?:string;workEmail?:string;employmentType?:string};
type Reporting={id:string;staffId:string;managerStaffId:string;kind:'primary'|'dotted';effectiveFrom:string};
type Delegation={id:string;principalStaffId:string;delegateStaffId:string;scope:string;status:string;startsAt:string;endsAt:string;reason:string};
type Directory={departments:Department[];positions:Position[];staff:Staff[];reporting:Reporting[];delegations:Delegation[];canManage:boolean;generatedAt:string;authorityNote:string;error?:string};

const empty:Directory={departments:[],positions:[],staff:[],reporting:[],delegations:[],canManage:false,generatedAt:'',authorityNote:''};
const staffName=(staff:Staff[],id:string)=>staff.find(item=>item.id===id)?.displayName||'Unknown staff member';

export default function CorporateOrganization(){
 const[data,setData]=useState<Directory>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const response=await sessionFetch('/api/corporate/organization',{cache:'no-store'});const value=await response.json() as Directory;if(!response.ok)throw new Error(value.error||'Organization directory unavailable');setData(value)}catch(e){setError(e instanceof Error?e.message:'Organization directory unavailable')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const positionsById=useMemo(()=>new Map(data.positions.map(item=>[item.id,item])),[data.positions]);
 const departmentsById=useMemo(()=>new Map(data.departments.map(item=>[item.id,item])),[data.departments]);
 const managerByStaff=useMemo(()=>new Map(data.reporting.filter(item=>item.kind==='primary').map(item=>[item.staffId,item.managerStaffId])),[data.reporting]);
 const activeStaff=data.staff.filter(item=>item.status==='active');
 const submit=async(action:string,form:HTMLFormElement)=>{setBusy(action);setMessage('');try{const values=Object.fromEntries(new FormData(form));const payload:any={action,...values};if(action==='createPosition'){payload.level=Number(values.level);payload.isDepartmentHead=values.isDepartmentHead==='on'}if(action==='createDelegation'){payload.startsAt=new Date(String(values.startsAt)).toISOString();payload.endsAt=new Date(String(values.endsAt)).toISOString()}const response=await sessionFetch('/api/corporate/organization',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const value=await response.json();if(!response.ok)throw new Error(value.error||'Organization change failed');form.reset();setMessage('Organization record saved. This did not change platform authority.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Organization change failed')}finally{setBusy('')}};
 if(loading)return <section data-sessions-surface="corporate" className="r-width r-inner"><div className="r-loading">Loading Sessions organization…</div></section>;
 if(error)return <section data-sessions-surface="corporate" className="r-width r-inner"><div className="r-panel"><h1>Organization unavailable</h1><p>{error}</p><Button onClick={()=>void load()}><RefreshCw size={16}/>Retry</Button></div></section>;
 return <section data-sessions-surface="corporate" className="r-width r-inner">
  <a className="r-back" href="/corporate"><ArrowLeft size={16}/>Corporate control centre</a>
  <div className="r-workspace-heading"><div><div className="r-eyebrow"><Users size={16}/>ORGANIZATION & PEOPLE</div><h1>Who runs Sessions.</h1><p className="r-intro">Departments, positions, reporting lines and acting responsibility. Company hierarchy is deliberately separate from system permissions.</p></div><div className="r-panel"><ShieldCheck size={20}/><strong>Authority boundary</strong><p>{data.authorityNote}</p></div></div>
  <div className="r-metrics"><div><span>Departments</span><strong>{data.departments.filter(item=>item.status==='active').length}</strong><Building2/></div><div><span>Active staff</span><strong>{activeStaff.length}</strong><Users/></div><div><span>Primary reporting lines</span><strong>{data.reporting.filter(item=>item.kind==='primary').length}</strong><GitBranch/></div><div><span>Active delegations</span><strong>{data.delegations.filter(item=>item.status==='active').length}</strong><UserRoundCog/></div></div>
  <section className="r-panel"><div className="r-eyebrow"><Building2 size={16}/>DEPARTMENTS</div>{data.departments.length===0?<p>No departments have been configured yet.</p>:<div className="r-studio-grid">{data.departments.map(department=>{const positions=data.positions.filter(item=>item.departmentId===department.id&&item.status==='active');const departmentStaff=activeStaff.filter(person=>person.positionId&&positions.some(position=>position.id===person.positionId));const heads=departmentStaff.filter(person=>positionsById.get(person.positionId||'')?.isDepartmentHead);return <article className="r-card" key={department.id}><span className="r-badge claimed">{department.code}</span><h3>{department.name}</h3>{department.description&&<p>{department.description}</p>}<p className="r-small"><strong>Head:</strong> {heads.map(item=>item.displayName).join(', ')||'Not assigned'}</p><p className="r-small">{positions.length} positions · {departmentStaff.length} active staff</p></article>})}</div>}</section>
  <section className="r-panel"><div className="r-eyebrow"><GitBranch size={16}/>REPORTING DIRECTORY</div>{activeStaff.length===0?<p>Add staff to begin the reporting directory.</p>:<div className="r-table-wrap"><table className="r-table"><thead><tr><th>Staff member</th><th>Position</th><th>Department</th><th>Reports to</th><th>Status</th></tr></thead><tbody>{activeStaff.map(person=>{const position=person.positionId?positionsById.get(person.positionId):undefined;const department=position?departmentsById.get(position.departmentId):undefined;const managerId=managerByStaff.get(person.id);return <tr key={person.id}><td><strong>{person.displayName}</strong><div className="r-small">{person.staffCode}</div></td><td>{position?.title||'Unassigned'}</td><td>{department?.name||'Unassigned'}</td><td>{managerId?staffName(data.staff,managerId):'Top-level / not assigned'}</td><td>{person.status}</td></tr>})}</tbody></table></div>}</section>
  {data.delegations.length>0&&<section className="r-panel"><div className="r-eyebrow"><UserRoundCog size={16}/>ACTING RESPONSIBILITY</div><div className="r-table-wrap"><table className="r-table"><thead><tr><th>Principal</th><th>Delegate</th><th>Scope</th><th>Window</th><th>Reason</th></tr></thead><tbody>{data.delegations.map(item=><tr key={item.id}><td>{staffName(data.staff,item.principalStaffId)}</td><td>{staffName(data.staff,item.delegateStaffId)}</td><td>{item.scope}</td><td>{new Date(item.startsAt).toLocaleString()} → {new Date(item.endsAt).toLocaleString()}</td><td>{item.reason}</td></tr>)}</tbody></table></div></section>}
  {data.canManage&&<><h2>Organization administration</h2><div className="r-studio-grid">
   <OrganizationForm title="Create department" action="createDepartment" busy={busy} submit={submit}><label className="r-field"><span>Code</span><input name="code" required placeholder="FIN"/></label><label className="r-field"><span>Name</span><input name="name" required placeholder="Finance"/></label><label className="r-field"><span>Parent department</span><select name="parentDepartmentId" defaultValue=""><option value="">None</option>{data.departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="r-field"><span>Description</span><textarea name="description"/></label></OrganizationForm>
   <OrganizationForm title="Create position" action="createPosition" busy={busy} submit={submit}><label className="r-field"><span>Department</span><select name="departmentId" required defaultValue=""><option value="" disabled>Select department</option>{data.departments.filter(item=>item.status==='active').map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="r-field"><span>Code</span><input name="code" required placeholder="HEAD_FIN"/></label><label className="r-field"><span>Title</span><input name="title" required placeholder="Head of Finance"/></label><label className="r-field"><span>Level</span><input name="level" type="number" min="0" max="30" defaultValue="5" required/></label><label className="r-field"><span>Reports to position</span><select name="reportsToPositionId" defaultValue=""><option value="">None</option>{data.positions.filter(item=>item.status==='active').map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="checkfield"><input name="isDepartmentHead" type="checkbox"/> Department head position</label></OrganizationForm>
   <OrganizationForm title="Add staff member" action="createStaff" busy={busy} submit={submit}><label className="r-field"><span>Trusted identity ID</span><input name="userId" required placeholder="Supabase user ID"/></label><label className="r-field"><span>Staff code</span><input name="staffCode" required placeholder="SZ-001"/></label><label className="r-field"><span>Display name</span><input name="displayName" required/></label><label className="r-field"><span>Work email</span><input name="workEmail" type="email"/></label><label className="r-field"><span>Position</span><select name="positionId" defaultValue=""><option value="">Unassigned</option>{data.positions.filter(item=>item.status==='active').map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="r-field"><span>Location</span><input name="location" placeholder="Harare / Remote"/></label><label className="r-field"><span>Employment type</span><select name="employmentType" defaultValue="employee"><option value="employee">Employee</option><option value="contractor">Contractor</option><option value="advisor">Advisor</option></select></label></OrganizationForm>
   <OrganizationForm title="Set reporting line" action="setReportingLine" busy={busy} submit={submit}><label className="r-field"><span>Staff member</span><select name="staffId" required defaultValue=""><option value="" disabled>Select staff</option>{activeStaff.map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label className="r-field"><span>Manager</span><select name="managerStaffId" required defaultValue=""><option value="" disabled>Select manager</option>{activeStaff.map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label className="r-field"><span>Relationship</span><select name="kind" defaultValue="primary"><option value="primary">Primary manager</option><option value="dotted">Dotted-line manager</option></select></label></OrganizationForm>
   <OrganizationForm title="Create acting delegation" action="createDelegation" busy={busy} submit={submit}><label className="r-field"><span>Principal</span><select name="principalStaffId" required defaultValue=""><option value="" disabled>Select principal</option>{activeStaff.map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label className="r-field"><span>Delegate</span><select name="delegateStaffId" required defaultValue=""><option value="" disabled>Select delegate</option>{activeStaff.map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label className="r-field"><span>Scope</span><select name="scope" defaultValue="department"><option value="department">Department responsibility</option><option value="position">Position responsibility</option><option value="workflow">Named workflow</option><option value="all">All organizational responsibility</option></select></label><label className="r-field"><span>Starts</span><input name="startsAt" type="datetime-local" required/></label><label className="r-field"><span>Ends</span><input name="endsAt" type="datetime-local" required/></label><label className="r-field"><span>Reason</span><textarea name="reason" required placeholder="Acting while the department head is away"/></label></OrganizationForm>
  </div></>}
  {message&&<div className="r-panel" role="status"><p>{message}</p></div>}
  <p className="r-muted">Directory generated {data.generatedAt?new Date(data.generatedAt).toLocaleString():'now'}.</p>
 </section>;
}

function OrganizationForm({title,action,busy,submit,children}:{title:string;action:string;busy:string;submit:(action:string,form:HTMLFormElement)=>Promise<void>;children:React.ReactNode}){
 return <form className="r-panel r-form" onSubmit={event=>{event.preventDefault();void submit(action,event.currentTarget)}}><h3>{title}</h3>{children}<Button disabled={!!busy}>{busy===action?'Saving…':'Save'}</Button></form>;
}
