'use client';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,BriefcaseBusiness,FileLock2,RefreshCw,Search,ShieldAlert,Upload} from 'lucide-react';
import {sessionFetch} from '@/lib/supabase-browser';

type CaseItem={id:string;reference:string;category:string;severity:string;priority:string;status:string;source:string;assignedTo:string|null;assignedTeam:string|null;bookingId:string|null;studioId:string|null;customerRef?:string;settlementId:string|null;classification:string;slaTargetAt:string|null;nextActionAt:string|null;resolutionCode:string|null;createdAt:string;updatedAt:string;resolvedAt:string|null;closedAt:string|null;revision:number;summary:string;description:string};
type CaseEvent={id:string;event:string;actor:string;visibility:string;classification:string;evidenceMediaId:string|null;createdAt:string;content:Record<string,unknown>};
type Payload={cases:CaseItem[];events:CaseEvent[];links:{id:string;objectType:string;objectId:string;createdAt:string}[];metrics:{open:number;urgent:number;critical:number;waiting:number};canAssign:boolean;canReadRestricted:boolean;error?:string};
type Staff={staffId:string;displayName:string;status:string};
const uid=()=>crypto.randomUUID();
const transitions:Record<string,string[]>={open:['triaged'],triaged:['in_progress','waiting_customer','waiting_provider','waiting_internal','resolved'],in_progress:['waiting_customer','waiting_provider','waiting_internal','resolved'],waiting_customer:['in_progress','waiting_provider','waiting_internal','resolved'],waiting_provider:['in_progress','waiting_customer','waiting_internal','resolved'],waiting_internal:['in_progress','waiting_customer','waiting_provider','resolved'],resolved:['closed'],closed:[]};
const labels:Record<string,string>={customer_support:'Customer Support',booking_operations:'Booking Operations',provider_operations:'Provider Operations',trust_safety:'Trust & Safety',finance:'Finance',general_incident:'General Incident'};

export default function CorporateCases(){
 const[list,setList]=useState<Payload|null>(null),[detail,setDetail]=useState<Payload|null>(null),[staff,setStaff]=useState<Staff[]>([]),[selected,setSelected]=useState<CaseItem|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showCreate,setShowCreate]=useState(false);
 async function loadList(){const params=new URLSearchParams();if(q)params.set('q',q);if(status)params.set('status',status);if(category)params.set('category',category);const res=await sessionFetch('/api/corporate/cases?'+params,{cache:'no-store'});const value=await res.json() as Payload;if(!res.ok)throw new Error(value.error||'Cases unavailable');setList(value);if(!selected&&value.cases[0])await select(value.cases[0]);else if(selected){const next=value.cases.find(c=>c.id===selected.id);if(next){setSelected(next);await loadDetail(next.id)}else{setSelected(null);setDetail(null)}}}
 async function loadDetail(id:string){const res=await sessionFetch('/api/corporate/cases?case='+encodeURIComponent(id),{cache:'no-store'});const value=await res.json() as Payload;if(!res.ok)throw new Error(value.error||'Case unavailable');setDetail(value);if(value.cases[0])setSelected(value.cases[0])}
 async function select(item:CaseItem){setSelected(item);await loadDetail(item.id)}
 useEffect(()=>{void Promise.all([loadList(),sessionFetch('/api/corporate/staff-lifecycle',{cache:'no-store'}).then(async r=>{if(r.ok){const v=await r.json() as {staff:Staff[]};setStaff(v.staff.filter(s=>s.status==='active'))}})]).catch(e=>setError(e instanceof Error?e.message:'Cases unavailable'))},[]);
 async function mutate(payload:Record<string,unknown>,refresh=true){setBusy(true);setError('');try{const res=await sessionFetch('/api/corporate/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,idempotencyKey:uid()})});const value=await res.json() as {error?:string;caseId?:string};if(!res.ok)throw new Error(value.error||'Case change failed');if(refresh){await loadList();if(value.caseId)await loadDetail(value.caseId);else if(selected)await loadDetail(selected.id)}return value}catch(e){setError(e instanceof Error?e.message:'Case change failed');return null}finally{setBusy(false)}}
 return <main className="p5-shell" data-sessions-surface="corporate" data-p5="cases">
  <header className="p5-heading"><div><a href="/corporate" className="p5-back"><ArrowLeft size={16}/>Corporate control centre</a><span className="p5-kicker"><BriefcaseBusiness size={16}/>INCIDENTS & CASES</span><h1>Structured operational accountability.</h1><p>Cases coordinate work across Support, Booking Operations, Provider Operations, Trust & Safety and Finance without copying canonical marketplace records.</p></div><div className="p5-heading-actions"><button className="p5-button secondary" onClick={()=>void loadList()}><RefreshCw size={16}/>Refresh</button><button className="p5-button" onClick={()=>setShowCreate(true)}>New case</button></div></header>
  {error&&<div className="p5-alert" role="alert"><AlertTriangle size={18}/>{error}</div>}
  {list&&<section className="p5-metrics"><Metric label="Open" value={list.metrics.open}/><Metric label="Urgent" value={list.metrics.urgent}/><Metric label="Critical" value={list.metrics.critical}/><Metric label="Waiting" value={list.metrics.waiting}/></section>}
  <section className="p5-toolbar"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Case, booking, studio…" onKeyDown={e=>{if(e.key==='Enter')void loadList()}}/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['open','triaged','in_progress','waiting_customer','waiting_provider','waiting_internal','resolved','closed'].map(v=><option key={v}>{v}</option>)}</select><button className="p5-button" onClick={()=>void loadList()}>Apply</button></section>
  <div className="p5-master-detail"><section className="p5-queue"><div className="p5-table-wrap"><table className="p5-table"><thead><tr><th>Case</th><th>Category</th><th>Status</th><th>Priority</th><th>Next action</th></tr></thead><tbody>{(list?.cases||[]).map(item=><tr key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>void select(item)}><td><strong>{item.reference}</strong><small>{item.summary}</small></td><td>{labels[item.category]||item.category}<small>{item.classification}</small></td><td><Status value={item.status}/><small>{item.assignedTeam||item.assignedTo||'Unassigned'}</small></td><td><Status value={item.priority}/><small>{item.severity} severity</small></td><td>{item.nextActionAt?new Date(item.nextActionAt).toLocaleString():'—'}<small>{item.slaTargetAt?'SLA '+new Date(item.slaTargetAt).toLocaleString():'No SLA'}</small></td></tr>)}</tbody></table></div><div className="p5-card-list">{(list?.cases||[]).map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>void select(item)}><span><strong>{item.reference}</strong><small>{labels[item.category]} · {item.summary}</small></span><Status value={item.status}/><span><small>{item.assignedTeam||'Unassigned'}</small><b>{item.priority}</b></span></button>)}</div>{list?.cases.length===0&&<div className="p5-empty">No cases match this queue.</div>}</section><aside className="p5-detail">{selected&&detail?<CaseDetail item={selected} events={detail.events} links={detail.links} staff={staff} canAssign={detail.canAssign} canReadRestricted={detail.canReadRestricted} busy={busy} mutate={mutate}/>:<div className="p5-empty">Select a case to inspect its timeline and controls.</div>}</aside></div>
  {showCreate&&<CreateCase busy={busy} close={()=>setShowCreate(false)} create={async payload=>{const value=await mutate({action:'create',...payload});if(value)setShowCreate(false)}}/>}
 </main>;
}

function CaseDetail({item,events,links,staff,canAssign,canReadRestricted,busy,mutate}:{item:CaseItem;events:CaseEvent[];links:Payload['links'];staff:Staff[];canAssign:boolean;canReadRestricted:boolean;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<any>}){
 const[note,setNote]=useState(''),[resolution,setResolution]=useState('resolved'),[reason,setReason]=useState('');const targets=transitions[item.status]||[];
 async function upload(file:File){const form=new FormData();form.set('file',file);form.set('purpose','case_evidence');const res=await sessionFetch('/api/upload',{method:'POST',body:form});const value=await res.json() as {id?:string;error?:string};if(!res.ok||!value.id)throw new Error(value.error||'Evidence upload failed');await mutate({action:'evidence',caseId:item.id,mediaId:value.id,note:'Evidence uploaded from the case workspace.'})}
 return <div className="p5-detail-card"><div className="p5-case-title"><span className="p5-kicker"><ShieldAlert size={15}/>{item.reference}</span>{item.classification!=='internal'&&<span className="p5-restricted"><FileLock2 size={14}/>{item.classification}</span>}</div><h2>{item.summary}</h2><p>{item.description}</p><dl className="p5-facts"><div><dt>Category</dt><dd>{labels[item.category]}</dd></div><div><dt>Status</dt><dd><Status value={item.status}/></dd></div><div><dt>Priority / severity</dt><dd>{item.priority} / {item.severity}</dd></div><div><dt>Assignment</dt><dd>{item.assignedTo||item.assignedTeam||'Unassigned'}</dd></div><div><dt>Booking</dt><dd>{item.bookingId||'—'}</dd></div><div><dt>Studio</dt><dd>{item.studioId||'—'}</dd></div><div><dt>SLA target</dt><dd>{item.slaTargetAt?new Date(item.slaTargetAt).toLocaleString():'—'}</dd></div><div><dt>Revision</dt><dd>{item.revision}</dd></div></dl>
  <section className="p5-subsection"><h3>Workflow</h3><div className="p5-transition-grid">{targets.map(target=><button className="p5-button secondary" disabled={busy} key={target} onClick={()=>{const resolutionCode=target==='resolved'||target==='closed'?window.prompt('Resolution code (required):',resolution)||'':undefined;const why=window.prompt(`Reason for ${target.replaceAll('_',' ')}:`,reason)||'';if(why.trim())void mutate({action:'transition',caseId:item.id,to:target,revision:item.revision,reason:why,resolutionCode})}}>{target.replaceAll('_',' ')}</button>)}{['resolved','closed'].includes(item.status)&&<button className="p5-button secondary" disabled={busy} onClick={()=>{const why=window.prompt('Reason for reopening this case:')||'';if(why.trim().length>=10)void mutate({action:'reopen',caseId:item.id,revision:item.revision,reason:why})}}>Reopen case</button>}</div></section>
  {canAssign&&<section className="p5-subsection"><h3>Assignment</h3><div className="p5-inline-form"><select defaultValue={item.assignedTo||''} key={'person'+item.revision} onChange={e=>void mutate({action:'assign',caseId:item.id,revision:item.revision,assignedTo:e.target.value||null,assignedTeam:item.assignedTeam,reason:'Assignment updated from case workspace.'})}><option value="">No individual</option>{staff.map(s=><option key={s.staffId} value={s.staffId}>{s.displayName}</option>)}</select><select defaultValue={item.assignedTeam||''} key={'team'+item.revision} onChange={e=>void mutate({action:'assign',caseId:item.id,revision:item.revision,assignedTo:item.assignedTo,assignedTeam:e.target.value||null,reason:'Team assignment updated from case workspace.'})}><option value="">No team</option><option value="marketplace_operations">Marketplace Operations</option><option value="customer_support">Customer Support</option><option value="provider_operations">Provider Operations</option><option value="trust_safety">Trust & Safety</option><option value="finance">Finance</option><option value="governance">Governance</option></select></div></section>}
  <section className="p5-subsection"><h3>Next action & SLA</h3><div className="p5-inline-form"><label>Next action<input type="datetime-local" defaultValue={item.nextActionAt?item.nextActionAt.slice(0,16):''} key={'next'+item.revision} onBlur={e=>void mutate({action:'setSla',caseId:item.id,revision:item.revision,nextActionAt:e.target.value?new Date(e.target.value).toISOString():null,slaTargetAt:item.slaTargetAt,reason:'Next action updated from case workspace.'})}/></label><label>SLA target<input type="datetime-local" defaultValue={item.slaTargetAt?item.slaTargetAt.slice(0,16):''} key={'sla'+item.revision} onBlur={e=>void mutate({action:'setSla',caseId:item.id,revision:item.revision,nextActionAt:item.nextActionAt,slaTargetAt:e.target.value?new Date(e.target.value).toISOString():null,reason:'SLA target updated from case workspace.'})}/></label></div></section>
  <section className="p5-subsection"><h3>Case note</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write an attributable case note. Customer/provider visibility is explicit, never inferred."/><div className="p5-inline-actions"><button className="p5-button" disabled={busy||note.trim().length<2} onClick={()=>void mutate({action:'note',caseId:item.id,note,visibility:'internal',classification:'internal'}).then(()=>setNote(''))}>Add internal note</button></div></section>
  {canReadRestricted&&<section className="p5-subsection"><h3>Restricted evidence</h3><label className="p5-upload"><Upload size={17}/><span>Upload JPEG, PNG or WebP evidence up to 5 MB<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file).catch(err=>window.alert(err instanceof Error?err.message:'Evidence upload failed'))}}/></span></label></section>}
  {links.length>0&&<section className="p5-subsection"><h3>Linked canonical records</h3><ul className="p5-links">{links.map(link=><li key={link.id}><strong>{link.objectType}</strong><span>{link.objectId}</span></li>)}</ul></section>}
  <section className="p5-subsection"><h3>Timeline</h3><ol className="p5-timeline">{events.map(event=><li key={event.id}><span><strong>{event.event.replaceAll('.',' ')}</strong><small>{new Date(event.createdAt).toLocaleString()} · {event.actor} · {event.visibility}</small></span>{event.content.note&&<p>{String(event.content.note)}</p>}{event.evidenceMediaId&&<a href={'/api/media/'+event.evidenceMediaId} target="_blank">View restricted evidence</a>}</li>)}</ol></section>
 </div>;
}

function CreateCase({busy,close,create}:{busy:boolean;close:()=>void;create:(p:Record<string,unknown>)=>Promise<void>}){const[category,setCategory]=useState('booking_operations');return <div className="p5-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="p5-modal" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void create({category:f.get('category'),severity:f.get('severity'),priority:f.get('priority'),classification:f.get('classification'),source:'staff',bookingId:f.get('bookingId')||null,studioId:f.get('studioId')||null,customer:f.get('customer')||null,settlementId:f.get('settlementId')||null,summary:f.get('summary'),description:f.get('description'),slaTargetAt:f.get('slaTargetAt')?new Date(String(f.get('slaTargetAt'))).toISOString():null})}}><span className="p5-kicker">NEW CASE</span><h2>Create an operational case</h2><label>Category<select name="category" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="p5-form-grid"><label>Severity<select name="severity" defaultValue="medium">{['low','medium','high','critical'].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select name="priority" defaultValue="normal">{['low','normal','high','urgent'].map(v=><option key={v}>{v}</option>)}</select></label><label>Classification<select name="classification" defaultValue="internal"><option value="internal">Internal</option><option value="restricted">Restricted</option><option value="confidential">Confidential</option></select></label><label>SLA target<input name="slaTargetAt" type="datetime-local"/></label></div><label>Summary<input name="summary" required minLength={5} maxLength={240}/></label><label>Description<textarea name="description" required minLength={5} maxLength={5000}/></label><div className="p5-form-grid"><label>Booking ID<input name="bookingId"/></label><label>Studio ID<input name="studioId"/></label><label>Customer user ID<input name="customer"/></label><label>Settlement ID<input name="settlementId"/></label></div><div className="p5-modal-actions"><button type="button" className="p5-button secondary" onClick={close}>Cancel</button><button className="p5-button" disabled={busy}>{busy?'Creating…':'Create case'}</button></div></form></div>}
function Metric({label,value}:{label:string;value:number}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Status({value}:{value:string}){return <span className={`p5-status s-${value.replaceAll('_','-')}`}>{value.replaceAll('_',' ')}</span>}
