'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,ClipboardCheck,KeyRound,RefreshCw,ShieldAlert,ShieldCheck,UserCog} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {sessionFetch} from '@/lib/supabase-browser';

type Review={id:string;title:string;status:'open'|'completed'|'cancelled';createdBy:string;createdAt:string;dueAt:string|null;completedAt:string|null;snapshotCount:number};
type Item={id:string;reviewId:string;userId:string;role:string;decision:'pending'|'retain'|'revoke';remediationStatus:'not_required'|'pending'|'completed'|'failed';reviewer:string|null;reviewedAt:string|null;remediatedAt:string|null;snapshotGrantedBy:string|null;snapshotGrantedAt:string|null;note:string};
type Data={reviews:Review[];selectedReviewId:string|null;items:Item[];error?:string};
type Privileged={assuranceLevel:'aal1'|'aal2'|null;eligible:boolean;privileged:{id:string;purpose:string;expiresAt:string}|null;error?:string};
const empty:Data={reviews:[],selectedReviewId:null,items:[]};

export default function CorporateAccessReviews(){
 const[data,setData]=useState<Data>(empty),[privileged,setPrivileged]=useState<Privileged|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const load=async(reviewId?:string)=>{setLoading(true);setError('');try{const query=reviewId?`?reviewId=${encodeURIComponent(reviewId)}`:'';const [reviewsResponse,privilegedResponse]=await Promise.all([sessionFetch('/api/corporate/access-reviews'+query,{cache:'no-store'}),sessionFetch('/api/corporate/privileged',{cache:'no-store'})]);const reviewsValue=await reviewsResponse.json() as Data;const privilegedValue=await privilegedResponse.json() as Privileged;if(!reviewsResponse.ok)throw new Error(reviewsValue.error||'Access reviews unavailable');setData(reviewsValue);setPrivileged(privilegedResponse.ok?privilegedValue:null)}catch(e){setError(e instanceof Error?e.message:'Access reviews unavailable')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const selected=useMemo(()=>data.reviews.find(review=>review.id===data.selectedReviewId)||null,[data]);const pending=data.items.filter(item=>item.decision==='pending').length;const revoke=data.items.filter(item=>item.decision==='revoke').length;const outstanding=data.items.filter(item=>item.decision==='revoke'&&item.remediationStatus!=='completed').length;const privilegedReady=!!privileged?.privileged;
 const mutate=async(payload:Record<string,unknown>,key:string)=>{setBusy(key);setMessage('');try{const response=await sessionFetch('/api/corporate/access-reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const value=await response.json();if(!response.ok)throw new Error(value.error||'Access review change failed');setMessage('Access review updated.');await load(payload.reviewId as string||data.selectedReviewId||value.reviewId)}catch(e){setMessage(e instanceof Error?e.message:'Access review change failed')}finally{setBusy('')}};
 if(loading)return <section className="r-width r-inner"><div className="r-loading">Loading Access & Security…</div></section>;
 if(error)return <section className="r-width r-inner"><div className="r-panel"><h1>Access & Security unavailable</h1><p>{error}</p><Button onClick={()=>void load()}><RefreshCw size={16}/>Retry</Button></div></section>;
 return <section className="r-width r-inner c4-module">
  <a className="r-back" href="/corporate"><ArrowLeft size={16}/>Corporate control centre</a>
  <div className="r-workspace-heading"><div><div className="r-eyebrow"><ClipboardCheck size={16}/>ACCESS & SECURITY</div><h1>Review platform authority.</h1><p className="r-intro">Authorized governance staff can inspect access-review state. Every mutation remains a separate privileged action: eligible administrator, AAL2 assurance, current 15-minute privileged session and auditable outcome.</p></div><div className="r-panel"><KeyRound size={20}/><strong>Privileged mutation window</strong><p>{privilegedReady?`Active until ${new Date(privileged!.privileged!.expiresAt).toLocaleString()}`:'Not active for this identity'}</p></div></div>
  <div className="r-trust-row"><span><ShieldCheck/>Trusted source snapshot</span><span><UserCog/>Named reviewer</span><span><CheckCircle2/>Decision ≠ remediation</span></div>
  {!privilegedReady&&<div className="r-panel"><ShieldAlert size={20}/><h3>Read-only security view</h3><p>You may inspect governance state because this identity has security-read authority. Creating reviews, recording decisions, remediating access and completing a review require explicit privileged-administrator eligibility plus the current production AAL2 elevation window.</p>{privileged&&<a className="r-primary" href="/corporate#role-control">Open privileged controls</a>}</div>}
  <div className="r-studio-grid"><form className="r-panel r-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const raw=String(form.get('dueAt')||'');void mutate({action:'create',title:form.get('title'),dueAt:raw?new Date(raw).toISOString():null},'create')}}><div className="r-eyebrow"><ClipboardCheck size={16}/>NEW REVIEW</div><label className="r-field"><span>Review title</span><input name="title" required minLength={4} maxLength={120} placeholder="Quarterly corporate platform access review"/></label><label className="r-field"><span>Due date</span><input name="dueAt" type="datetime-local"/></label><Button disabled={!privilegedReady||!!busy}>{busy==='create'?'Creating snapshot…':'Create authority snapshot'}</Button><p className="r-small">The snapshot is sourced from active managed `platform_role_assignments`; it does not grant or copy authority into D1.</p></form>
   <div className="r-panel"><div className="r-eyebrow"><ShieldCheck size={16}/>REVIEWS</div>{data.reviews.length===0?<p>No access reviews yet.</p>:<div className="r-form">{data.reviews.map(review=><button type="button" className={review.id===data.selectedReviewId?'r-secondary active':'r-secondary'} key={review.id} onClick={()=>void load(review.id)}><strong>{review.title}</strong><span>{review.status} · {review.snapshotCount} assignments</span></button>)}</div>}</div></div>
  {selected&&<><div className="r-workspace-heading"><div><h2>{selected.title}</h2><p className="r-muted">Snapshot created {new Date(selected.createdAt).toLocaleString()}{selected.dueAt?` · due ${new Date(selected.dueAt).toLocaleString()}`:''}.</p></div><span className={'r-badge '+(selected.status==='completed'?'claimed':'')}>{selected.status.toUpperCase()}</span></div>
   <div className="r-metrics c4-metrics"><div><span>Snapshot</span><strong>{selected.snapshotCount}</strong><ClipboardCheck/></div><div><span>Pending decisions</span><strong>{pending}</strong><ShieldAlert/></div><div><span>Revoke decisions</span><strong>{revoke}</strong><UserCog/></div><div><span>Remediation outstanding</span><strong>{outstanding}</strong><KeyRound/></div></div>
   <section className="r-panel c4-data-panel"><div className="r-eyebrow"><ShieldCheck size={16}/>AUTHORITY SNAPSHOT</div>{data.items.length===0?<p>This review contains no managed platform-role assignments.</p>:<div className="r-table-wrap"><table className="r-table c4-table"><thead><tr><th>User ref</th><th>Role</th><th>Granted</th><th>Decision</th><th>Remediation</th><th>Actions</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td data-label="User ref"><strong>{item.userId}</strong><div className="r-small">Granted by {item.snapshotGrantedBy||'unknown'}</div></td><td data-label="Role">{item.role.replaceAll('_',' ')}</td><td data-label="Granted">{item.snapshotGrantedAt?new Date(item.snapshotGrantedAt).toLocaleString():'Unknown'}</td><td data-label="Decision">{item.decision}</td><td data-label="Remediation">{item.remediationStatus}</td><td data-label="Actions">{selected.status==='open'?<div className="r-actions"><Button variant="outline" disabled={!privilegedReady||!!busy} onClick={()=>void mutate({action:'decide',itemId:item.id,decision:'retain',note:''},item.id+':retain')}>Retain</Button><Button variant="outline" disabled={!privilegedReady||!!busy} onClick={()=>void mutate({action:'decide',itemId:item.id,decision:'revoke',note:''},item.id+':revoke')}>Revoke</Button>{item.decision==='revoke'&&item.remediationStatus!=='completed'&&<Button disabled={!privilegedReady||!!busy} onClick={()=>void mutate({action:'remediate',itemId:item.id},item.id+':remediate')}>{item.remediationStatus==='failed'?'Retry remediation':'Remediate'}</Button>}</div>:<span className="r-small">Review closed</span>}</td></tr>)}</tbody></table></div>}</section>
   {selected.status==='open'&&<section className="r-panel"><h3>Completion gate</h3><p>{pending>0?'Every assignment still needs a retain or revoke decision.':outstanding>0?'All decisions are recorded, but revoke decisions still require successful remediation.':'All decisions and remediation are complete. The review can be closed.'}</p><Button disabled={!privilegedReady||!!busy||pending>0||outstanding>0} onClick={()=>void mutate({action:'complete',reviewId:selected.id},'complete')}>Complete access review</Button></section>}</>}
  {message&&<div className="r-panel" role="status"><p>{message}</p></div>}
 </section>;
}
