'use client';
import {useEffect,useState} from 'react';
import {Activity,BarChart3,BookOpenCheck,Building2,CheckCircle2,ClipboardCheck,Headphones,KeyRound,Landmark,ReceiptText,RefreshCw,ShieldAlert,ShieldCheck,UserCog,Users,UsersRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {sessionFetch} from '@/lib/supabase-browser';
import {visibleCorporateModules,type CorporateModuleId} from '@/lib/corporate-control-plane';

type Overview={
 roles:string[];permissions:string[];generatedAt:string;
 marketplace?:{studios:number;bookable:number;pendingClaims:number;pendingVerifications:number};
 providers?:{pendingRegistrations:number;activeStaff:number};
 finance?:{disputed:number;awaitingPayment:number;invoices:number};
 support?:{openRegistryIssues:number;failedNotifications:number};
 controlPlane?:{bookings:number;customers:number;activeMemberships:number;openSignals:number};
 error?:string;
};
type PrivilegedSession={id:string;purpose:string;createdAt:string;expiresAt:string};
type PrivilegedState={assuranceLevel:'aal1'|'aal2'|null;eligible:boolean;privileged:PrivilegedSession|null;error?:string};
const moduleIcons:Record<CorporateModuleId,typeof ShieldCheck>={organization:Users,bookings:BookOpenCheck,customers:UsersRound,providers:Building2,memberships:UsersRound,incidents:Activity,finance:ReceiptText,support:Headphones,trust:ShieldCheck,analytics:BarChart3,audit:ClipboardCheck,access:UserCog};

export default function CorporateWorkspace(){
 const[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const[privileged,setPrivileged]=useState<PrivilegedState|null>(null),[privilegedBusy,setPrivilegedBusy]=useState(false),[privilegedMessage,setPrivilegedMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const response=await sessionFetch('/api/corporate/overview',{cache:'no-store'});const value=await response.json() as Overview;if(!response.ok)throw new Error(value.error||'Corporate overview unavailable');setData(value)}catch(e){setError(e instanceof Error?e.message:'Corporate overview unavailable')}finally{setLoading(false)}};
 const loadPrivileged=async()=>{setPrivilegedMessage('');try{const response=await sessionFetch('/api/corporate/privileged',{cache:'no-store'});const value=await response.json() as PrivilegedState;if(!response.ok)throw new Error(value.error||'Privileged administration state unavailable');setPrivileged(value)}catch(e){setPrivileged(null);setPrivilegedMessage(e instanceof Error?e.message:'Privileged administration state unavailable')}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(data?.permissions.includes('platform:roles.manage'))void loadPrivileged()},[data]);
 if(loading)return <section data-sessions-surface="corporate" className="r-width r-inner"><div className="r-loading">Loading corporate authority…</div></section>;
 if(error)return <section data-sessions-surface="corporate" className="r-width r-inner"><div className="r-panel"><h1>Corporate console unavailable</h1><p>{error}</p><Button onClick={()=>void load()}><RefreshCw size={16}/>Retry</Button></div></section>;
 const permissions=new Set(data?.permissions||[]),roles=data?.roles||[],modules=visibleCorporateModules(permissions);
 const canOpenOperations=permissions.has('claims:review')&&permissions.has('settlements:review')&&permissions.has('support:read')&&permissions.has('providers:oversight');
 const privilegedReady=!!privileged?.privileged;
 const changePrivileged=async(action:'activate'|'revoke',purpose='')=>{setPrivilegedBusy(true);setPrivilegedMessage('');try{const response=await sessionFetch('/api/corporate/privileged',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='activate'?{action,purpose}:{action})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Privileged administration change failed');setPrivilegedMessage(action==='activate'?'Privileged administration is active for this identity session.':'Privileged administration was revoked.');await loadPrivileged()}catch(e){setPrivilegedMessage(e instanceof Error?e.message:'Privileged administration change failed')}finally{setPrivilegedBusy(false)}};
 return <section data-sessions-surface="corporate" className="r-width r-inner">
  <div className="r-workspace-heading"><div><div className="r-eyebrow"><Landmark size={16}/>SESSIONS CORPORATE</div><h1>Platform control centre.</h1><p className="r-intro">One authority plane for the marketplace and the company operating it. Navigation is generated from this account’s assigned permissions; customer, provider and corporate views remain projections of the same production records.</p></div><div className="r-panel"><strong>Signed-in authority</strong><p>{roles.map(role=>role.replaceAll('_',' ')).join(' · ')||'No corporate role'}</p><p className="r-small">{modules.length} corporate modules assigned</p></div></div>
  <div className="r-trust-row"><span><ShieldCheck/>Deny by default</span><span><Users/>Named staff identities</span><span><CheckCircle2/>Org chart ≠ RBAC</span><span><Landmark/>One source of truth</span></div>
  {data?.controlPlane&&<div className="r-metrics"><div><span>Bookings</span><strong>{data.controlPlane.bookings}</strong><BookOpenCheck/></div><div><span>Customers</span><strong>{data.controlPlane.customers}</strong><UsersRound/></div><div><span>Active memberships</span><strong>{data.controlPlane.activeMemberships}</strong><UsersRound/></div><div><span>Open signals</span><strong>{data.controlPlane.openSignals}</strong><Activity/></div></div>}
  {data?.marketplace&&<div className="r-metrics"><div><span>Marketplace studios</span><strong>{data.marketplace.studios}</strong><Building2/></div><div><span>Bookable studios</span><strong>{data.marketplace.bookable}</strong><CheckCircle2/></div><div><span>Pending claims</span><strong>{data.marketplace.pendingClaims}</strong><ShieldCheck/></div><div><span>Verification queue</span><strong>{data.marketplace.pendingVerifications}</strong><ShieldCheck/></div></div>}
  <div className="c4-section-heading"><div><h2>Your corporate modules</h2><p className="r-small">Only modules this account is authorized to open are rendered.</p></div></div><div className="r-studio-grid c4-module-grid">{modules.map(module=>{const Icon=moduleIcons[module.id];return <article className="r-panel" key={module.id}><Icon size={25}/><span className="r-badge claimed">Assigned</span><h3>{module.title}</h3><p>{module.description}</p><a className="r-primary" href={module.href}>Open {module.shortTitle}</a></article>})}</div>
  {canOpenOperations&&<section className="r-panel"><div className="r-eyebrow"><Landmark size={16}/>CROSS-MARKETPLACE OPERATIONS</div><h2>General Operations console</h2><p>This account has the combined Trust, Finance, Support and Provider Operations authority required for cross-marketplace operational handling. This legacy combined view remains available while the control plane is migrated module by module.</p><a className="r-secondary" href="/registry-admin">Open combined Operations console</a></section>}
  <div className="r-metrics">{data?.providers&&<><div><span>Provider registrations</span><strong>{data.providers.pendingRegistrations}</strong><Building2/></div><div><span>Active provider staff</span><strong>{data.providers.activeStaff}</strong><Users/></div></>}{data?.finance&&<><div><span>Settlement disputes</span><strong>{data.finance.disputed}</strong><ReceiptText/></div><div><span>Payment records needing attention</span><strong>{data.finance.awaitingPayment}</strong><ReceiptText/></div></>}{data?.support&&<><div><span>Open registry issues</span><strong>{data.support.openRegistryIssues}</strong><Headphones/></div><div><span>Failed notifications</span><strong>{data.support.failedNotifications}</strong><Headphones/></div></>}</div>
  {permissions.has('platform:roles.manage')&&<section className="r-panel" id="role-control"><div className="r-eyebrow"><UserCog size={16}/>SUPER ADMINISTRATION</div><h2>Privileged authority control</h2><p>Role administration is a two-gate action: the account must already be Super Admin, and this exact production identity session must have AAL2 multi-factor assurance plus a current 15-minute privileged window.</p>
   <div className="r-trust-row"><span><KeyRound/>Authentication assurance: <strong>{privileged?.assuranceLevel?.toUpperCase()||'Unavailable'}</strong></span><span><ShieldCheck/>Privileged window: <strong>{privilegedReady?'Active':'Inactive'}</strong></span></div>
   {privileged?.privileged?<div className="r-panel"><span className="r-badge claimed">ELEVATED</span><h3>Privileged session active</h3><p><strong>Purpose:</strong> {privileged.privileged.purpose}</p><p className="r-small">Expires {new Date(privileged.privileged.expiresAt).toLocaleString()}. It is bound to the current identity-provider session; another elevation replaces it.</p><Button variant="outline" disabled={privilegedBusy} onClick={()=>void changePrivileged('revoke')}><ShieldAlert size={16}/>{privilegedBusy?'Revoking…':'End privileged session'}</Button></div>:privileged?.eligible?<form className="r-form r-panel" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void changePrivileged('activate',String(form.get('purpose')||''))}}><h3>Activate a 15-minute privileged window</h3><label className="r-field"><span>Purpose</span><textarea name="purpose" required minLength={8} maxLength={300} placeholder="Review and change corporate platform-role assignments"/></label><Button disabled={privilegedBusy}><KeyRound size={16}/>{privilegedBusy?'Activating…':'Activate privileged administration'}</Button></form>:<div className="r-panel"><ShieldAlert size={20}/><h3>AAL2 is required</h3><p>Complete multi-factor authentication with the production identity provider, then reload this console. Preview identities cannot be elevated, and Sessions does not simulate MFA.</p></div>}
   {privilegedMessage&&<p role="status">{privilegedMessage}</p>}
   <div className="r-panel"><h3>Access governance</h3><p>Review the authoritative role inventory, record retain/revoke decisions and require verified remediation before an access review can close.</p><a className="r-secondary" href="/corporate/access">Open access reviews</a></div>
   <h2>Assign platform authority</h2><p>Use the authenticated Supabase user UUID. Organization titles and reporting lines do not grant these roles. Authority changes remain unavailable until the privileged window above is active.</p><form className="r-form" onSubmit={async event=>{event.preventDefault();if(!privilegedReady){setMessage('Activate a current AAL2 privileged administration session first.');return}setBusy(true);setMessage('');const form=new FormData(event.currentTarget);try{const response=await sessionFetch('/api/corporate/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:form.get('userId'),role:form.get('role'),enabled:form.get('action')==='grant'})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Role update failed');setMessage(`${String(form.get('role')).replaceAll('_',' ')} ${form.get('action')==='grant'?'granted':'revoked'}.`)}catch(e){setMessage(e instanceof Error?e.message:'Role update failed')}finally{setBusy(false)}}}><fieldset disabled={busy||!privilegedReady}><label className="r-field"><span>Target user UUID</span><input name="userId" required pattern="[0-9a-fA-F-]{36}" placeholder="00000000-0000-0000-0000-000000000000"/></label><label className="r-field"><span>Platform role</span><select name="role" defaultValue="support_agent"><option value="support_agent">Customer support</option><option value="trust_safety">Trust & safety</option><option value="finance_admin">Finance administrator</option><option value="operations_admin">Marketplace operations</option><option value="corporate_admin">Corporate administrator</option><option value="super_admin">Super administrator</option><option value="provider_owner">Provider owner</option><option value="provider_manager">Provider manager</option><option value="provider_staff">Provider staff</option></select></label><label className="r-field"><span>Action</span><select name="action" defaultValue="grant"><option value="grant">Grant role</option><option value="revoke">Revoke role</option></select></label><Button>{busy?'Updating authority…':'Apply authority change'}</Button></fieldset>{!privilegedReady&&<p className="r-small">Role controls are locked until privileged administration is active.</p>}{message&&<p role="status">{message}</p>}</form></section>}
  <p className="r-muted">Generated {data?.generatedAt?new Date(data.generatedAt).toLocaleString():'now'}. Sensitive customer–studio messages are not included in this overview.</p>
 </section>;
}
