'use client';
import {useCallback,useEffect,useState} from 'react';
import {Plus,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Field,Choice,Empty} from './registry-ui';
import {sessionFetch} from '@/lib/supabase-browser';

type Policy={id:string;scope:'global'|'room';studioId?:string;roomId?:string;status:'active'|'retired';effectiveFrom:string;effectiveUntil?:string;revision:number;policy:{payer:string;musicianBps:number;studioBps:number;basis:string;source:string}};
const percent=(bps:number)=>`${(bps/100).toFixed(2).replace(/\.00$/,'')}%`;
export default function FeePolicyOperations(){
 const [policies,setPolicies]=useState<Policy[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[scope,setScope]=useState<'global'|'room'>('global'),[payer,setPayer]=useState('studio'),[basis,setBasis]=useState('room_subtotal'),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const response=await sessionFetch('/api/fee-policies',{cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error);setPolicies(body.policies);setError('')}catch(value){setError(value instanceof Error?value.message:'Fee policies are unavailable')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form);setSaving(true);try{const bps=Math.round(Number(values.get('feePercent'))*100);const payload={type:'create',key:crypto.randomUUID(),scope,studioId:scope==='room'?String(values.get('studioId')):undefined,roomId:scope==='room'?String(values.get('roomId')):undefined,payer,musicianBps:payer==='studio'?0:payer==='split'?bps:bps,studioBps:payer==='musician'?0:payer==='split'?bps:bps,basis,effectiveFrom:String(values.get('effectiveFrom')),effectiveUntil:String(values.get('effectiveUntil'))||undefined};const response=await sessionFetch('/api/fee-policies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),body=await response.json();if(!response.ok)throw new Error(body.error);form.reset();await load()}catch(value){setError(value instanceof Error?value.message:'Could not save fee policy')}finally{setSaving(false)}};
 const retire=async(policy:Policy)=>{if(policy.id==='founding-pilot-zero-v1')return;setSaving(true);try{const response=await sessionFetch('/api/fee-policies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'retire',key:crypto.randomUUID(),id:policy.id,revision:policy.revision})}),body=await response.json();if(!response.ok)throw new Error(body.error);await load()}catch(value){setError(value instanceof Error?value.message:'Could not retire fee policy')}finally{setSaving(false)}};
 return <section><div className="r-notice"><RefreshCw size={20}/><span>Commercial terms are configuration, not code. The founding-studio pilot stays at 0% until Operations creates an effective-dated policy. A policy is snapshotted into every quote and never rewrites a past booking.</span></div>{error&&<p className="r-error" role="alert">{error}</p>}<form className="r-panel r-form" onSubmit={submit}><h2>Schedule a fee policy</h2><div className="r-form-grid"><Choice label="Scope" value={scope} onChange={value=>setScope(value as 'global'|'room')} options={[{value:'global',label:'All future rooms'},{value:'room',label:'One studio room override'}]}/><Choice label="Who pays the Sessions fee?" value={payer} onChange={setPayer} options={[{value:'studio',label:'Studio pays'},{value:'musician',label:'Musician pays'},{value:'split',label:'Split equally'}]}/><Choice label="Fee basis" value={basis} onChange={setBasis} options={[{value:'room_subtotal',label:'Room subtotal only'},{value:'room_plus_addons',label:'Room + commissionable add-ons'}]}/><Field label={payer==='split'?'Fee per side (%)':'Fee (%)'}><input name="feePercent" type="number" min="0.01" max="25" step="0.01" required/></Field><Field label="Effective from"><input name="effectiveFrom" type="date" required/></Field><Field label="Effective until (optional)"><input name="effectiveUntil" type="date"/></Field>{scope==='room'&&<><Field label="Studio ID"><input name="studioId" placeholder="e.g. onevibe-studiox" required/></Field><Field label="Room ID"><input name="roomId" placeholder="Room ID from profile" required/></Field></>}</div><Button disabled={saving}><Plus size={16}/>Schedule policy</Button></form>{loading?<div className="r-loading">Loading policy history…</div>:!policies.length?<Empty title="No policy records">The 0% founding-pilot fallback will be used until a policy is created.</Empty>:<div className="r-registry-table">{policies.map(policy=><article key={policy.id}><div><span className={'r-badge '+(policy.status==='active'?'claimed':'')}>{policy.status} · {policy.scope}</span><h3>{policy.id==='founding-pilot-zero-v1'?'Founding studio pilot':`${policy.scope==='room'?'Room override':'Global policy'} · ${policy.policy.payer}`}</h3><p>{policy.effectiveFrom}{policy.effectiveUntil?` to ${policy.effectiveUntil}`:' onward'} · fee {policy.policy.payer==='split'?`${percent(policy.policy.musicianBps)} each side`:percent(policy.policy.musicianBps||policy.policy.studioBps)} · {policy.policy.basis.replaceAll('_',' ')}</p>{policy.studioId&&<small>{policy.studioId} / {policy.roomId}</small>}</div>{policy.status==='active'&&policy.id!=='founding-pilot-zero-v1'&&<Button variant="outline" disabled={saving} onClick={()=>void retire(policy)}>Retire policy</Button>}</article>)}</div>}</section>;
}
