'use client';
import {useState} from 'react';
import {ArrowRight,AudioLines,Building2,LockKeyhole,MessageCircle,ShieldCheck,Smartphone,UserRound,Users} from 'lucide-react';
import {AuthSignIn} from './production-auth';
import {sessionFetch} from '@/lib/supabase-browser';
import type {OnboardingSnapshot,WorkspaceContext} from '@/lib/onboarding-server';

type GatewayResult=OnboardingSnapshot&{returnPath?:string;continuationConsumed?:boolean;error?:string};
type Props={authenticated:boolean;initialSnapshot:OnboardingSnapshot|null;returnTo:string;continuationToken?:string|null};
const safe=(value:string)=>value.startsWith('/')&&!value.startsWith('//')?value:'/mobile';
const key=()=>crypto.randomUUID();

export default function OnboardingGateway({authenticated,initialSnapshot,returnTo,continuationToken=null}:Props){
 const[snapshot,setSnapshot]=useState(initialSnapshot),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const target=safe(returnTo);
 async function mutate(payload:Record<string,unknown>){setBusy(true);setError('');try{const response=await sessionFetch('/api/onboarding?return_to='+encodeURIComponent(target),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const value=await response.json() as GatewayResult;if(!response.ok)throw new Error(value.error||'Sessions could not save that step.');setSnapshot(value);return value}catch(reason){setError(reason instanceof Error?reason.message:'Sessions could not save that step.');return null}finally{setBusy(false)}}
 const authReturn=continuationToken?`/welcome?continue=${encodeURIComponent(continuationToken)}`:`/welcome?return_to=${encodeURIComponent(target)}`;
 if(!authenticated)return <Landing returnTo={authReturn}/>;
 if(!snapshot)return <main className="onb-shell"><Brand/><section className="onb-card"><h1>We could not load your Sessions profile.</h1><p>Your host access succeeded, but the Sessions onboarding state is unavailable. No authority has been granted.</p><a className="onb-primary" href="/welcome">Try again</a></section></main>;
 if(snapshot.nextStep==='restricted')return <Restricted snapshot={snapshot}/>;
 return <main className="onb-shell" data-sessions-surface="onboarding"><Brand/><div className="onb-layout"><aside className="onb-story"><span className="onb-kicker">ONE SESSIONS IDENTITY</span><h1>Your music, studios and workspaces stay connected.</h1><p>Use one verified identity. Sessions decides which workspaces you may enter from trusted studio membership and staff assignments — never from a self-selected admin role.</p><div className="onb-trust"><span><ShieldCheck size={18}/>Privacy by design</span><span><LockKeyhole size={18}/>MFA-aware access</span><span><Smartphone size={18}/>Built for mobile first</span></div></aside><section className="onb-card">{error&&<div className="onb-error" role="alert">{error}</div>}{snapshot.nextStep==='profile'?<ProfileStep snapshot={snapshot} busy={busy} mutate={mutate}/>:snapshot.nextStep==='consent'?<ConsentStep snapshot={snapshot} busy={busy} mutate={mutate}/>:<WorkspaceStep snapshot={snapshot} busy={busy} target={target} continuationToken={continuationToken} mutate={mutate}/>}</section></div></main>;
}

function Landing({returnTo}:{returnTo:string}){return <main className="onb-shell onb-landing" data-sessions-surface="onboarding-public"><Brand/><div className="onb-layout"><aside className="onb-story"><span className="onb-kicker">SESSIONS · ZIMBABWE</span><h1>Your music needs a place.</h1><p>Find rehearsal space, manage your studio or enter the Sessions operating company through one secure identity.</p><div className="onb-role-preview"><span><UserRound/>Find & book a studio</span><span><Building2/>Manage a studio</span><span><Users/>Sessions team access</span></div><small>Corporate access is invitation-only. Choosing a workspace never grants authority.</small></aside><section><AuthSignIn returnTo={returnTo}/><div className="onb-legal">By continuing you can review <a href="/legal/terms">Terms</a> and <a href="/privacy">Privacy</a> before activation. <a href="/help">Need help?</a></div></section></div></main>}
function Brand(){return <header className="onb-brand"><span><AudioLines size={21}/></span><strong>SESSIONS</strong><i>.</i></header>}

function ProfileStep({snapshot,busy,mutate}:{snapshot:OnboardingSnapshot;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<GatewayResult|null>}){const[name,setName]=useState(snapshot.profile.displayName),[locale,setLocale]=useState<'en-ZW'|'sn-ZW'|'nd-ZW'>((snapshot.profile.locale as 'en-ZW'|'sn-ZW'|'nd-ZW')||'en-ZW');return <form className="onb-form" onSubmit={event=>{event.preventDefault();void mutate({action:'completeProfile',displayName:name,market:'ZW',locale})}}><Progress current={1}/><span className="onb-kicker">YOUR PROFILE</span><h2>How should Sessions address you?</h2><p>We only ask for what the marketplace needs. Your verified sign-in identities stay managed by the identity provider.</p><label>Display name<input value={name} onChange={event=>setName(event.target.value)} autoComplete="name" required minLength={2} maxLength={100}/></label><label>Language<select value={locale} onChange={event=>setLocale(event.target.value as 'en-ZW'|'sn-ZW'|'nd-ZW')}><option value="en-ZW">English (Zimbabwe)</option><option value="sn-ZW">Shona</option><option value="nd-ZW">Ndebele</option></select></label><IdentitySummary snapshot={snapshot}/><button className="onb-primary" disabled={busy}>{busy?'Saving…':'Continue'}<ArrowRight size={17}/></button></form>}
function ConsentStep({snapshot,busy,mutate}:{snapshot:OnboardingSnapshot;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<GatewayResult|null>}){const[terms,setTerms]=useState(snapshot.consents.terms),[privacy,setPrivacy]=useState(snapshot.consents.privacy),[marketing,setMarketing]=useState(snapshot.consents.marketing);async function submit(event:React.FormEvent){event.preventDefault();if(!terms||!privacy)return;for(const [consentType,granted] of [['terms',terms],['privacy',privacy],['marketing',marketing]] as const)await mutate({action:'recordConsent',consentType,granted,idempotencyKey:key(),channel:'pwa'})}return <form className="onb-form" onSubmit={submit}><Progress current={2}/><span className="onb-kicker">PRIVACY & AGREEMENTS</span><h2>You control what Sessions uses.</h2><p>Required service terms are separate from optional marketing. Consent is stored with its document version and timestamp.</p><label className="onb-check"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I agree to the <a href="/legal/terms" target="_blank">Sessions Terms</a>. <b>Required</b></span></label><label className="onb-check"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/><span>I acknowledge the <a href="/privacy" target="_blank">Privacy Notice</a>. <b>Required</b></span></label><label className="onb-check optional"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span>Send me product/news updates. <b>Optional</b></span></label><button className="onb-primary" disabled={busy||!terms||!privacy}>{busy?'Recording…':'Activate my Sessions account'}<ArrowRight size={17}/></button></form>}

function WorkspaceStep({snapshot,busy,target,continuationToken,mutate}:{snapshot:OnboardingSnapshot;busy:boolean;target:string;continuationToken:string|null;mutate:(p:Record<string,unknown>)=>Promise<GatewayResult|null>}){
 const providerJourney=snapshot.journeys.find(j=>j.journey==='provider');
 async function finalTarget(fallback:string){if(!continuationToken)return fallback;const continuation=await mutate({action:'consumeContinuation',token:continuationToken});return continuation?.returnPath||fallback}
 async function choose(context:WorkspaceContext){const value=await mutate({action:'setLastContext',contextType:context.type,contextId:context.id});if(!value)return;const fallback=context.type==='corporate'?'/corporate':context.type==='provider'?'/manage':target;window.location.assign(await finalTarget(fallback))}
 async function intention(journey:'provider'|'corporate'){const value=await mutate({action:'setIntention',journey});if(!value)return;if(journey==='provider')window.location.assign('/studios?claim=1');else window.location.assign('/corporate')}
 return <div className="onb-form"><Progress current={3}/><span className="onb-kicker">CHOOSE YOUR SPACE</span><h2>How are you using Sessions today?</h2><p>These are contexts on one identity, not separate accounts. Only server-authorized workspaces can be opened.</p><div className="onb-contexts">{snapshot.contexts.map(context=><button key={`${context.type}:${context.id}`} disabled={busy||context.status!=='active'} onClick={()=>void choose(context)}><span className="onb-context-icon">{context.type==='personal'?<UserRound/>:context.type==='provider'?<Building2/>:<Users/>}</span><span><strong>{context.label}</strong><small>{context.type==='personal'?'Book rehearsal space and manage your sessions.':context.type==='provider'?'Authorized studio workspace.':'Sessions company workspace.'}</small></span><ArrowRight/></button>)}</div><div className="onb-divider"><span>Need another context?</span></div><button className="onb-secondary" disabled={busy} onClick={()=>void intention('provider')}><Building2/><span><strong>Manage a studio</strong><small>{providerJourney?`Application: ${providerJourney.status.replaceAll('_',' ')}`:'Claim an existing sourced studio or register a new one.'}</small></span><ArrowRight/></button><button className="onb-secondary" disabled={busy} onClick={()=>void intention('corporate')}><ShieldCheck/><span><strong>Sessions team member</strong><small>Invitation and staff assignment required. No self-service admin access.</small></span><ArrowRight/></button>{snapshot.identity.phone&&<WhatsApp snapshot={snapshot} busy={busy} mutate={mutate}/>}<IdentitySummary snapshot={snapshot}/></div>
}
function WhatsApp({snapshot,busy,mutate}:{snapshot:OnboardingSnapshot;busy:boolean;mutate:(p:Record<string,unknown>)=>Promise<GatewayResult|null>}){const[enabled,setEnabled]=useState(snapshot.consents.whatsapp);return <div className="onb-whatsapp"><MessageCircle size={20}/><span><strong>WhatsApp updates</strong><small>Use your verified {snapshot.identity.phone} for booking/service messages. This is a communication preference, not a login factor.</small></span><button disabled={busy} onClick={()=>{const next=!enabled;setEnabled(next);void mutate({action:'setWhatsAppPreference',phone:snapshot.identity.phone,optedIn:next,idempotencyKey:key(),channel:'pwa'})}}>{enabled?'On':'Off'}</button></div>}
function IdentitySummary({snapshot}:{snapshot:OnboardingSnapshot}){const label=snapshot.identity.assuranceLevel==='aal2'?'MFA / AAL2':'Standard session';return <div className="onb-identity"><ShieldCheck size={18}/><span><strong>Verified Sessions identity</strong><small>{snapshot.identity.email||snapshot.identity.phone||snapshot.identity.userId} · {label} · Session …{snapshot.identity.sessionId.slice(-8)}</small></span></div>}
function Progress({current}:{current:number}){return <div className="onb-progress" aria-label={`Onboarding step ${current} of 3`}>{[1,2,3].map(step=><span key={step} className={step<=current?'active':''}/>)}</div>}
function Restricted({snapshot}:{snapshot:OnboardingSnapshot}){return <main className="onb-shell"><Brand/><section className="onb-card onb-restricted"><LockKeyhole size={34}/><span className="onb-kicker">ACCOUNT ACCESS</span><h1>{snapshot.profile.status==='deletion_pending'?'Deletion request pending':'This Sessions context is restricted.'}</h1><p>Your identity still exists, but this personal context cannot enter the marketplace right now. Provider or corporate contexts are evaluated independently and never recreated by account recovery.</p><a className="onb-secondary-link" href="/help">Contact Sessions support</a></section></main>}
