'use client';
import {useState} from 'react';
import {ShieldCheck,Search,SlidersHorizontal,Info,CheckCircle2,ArrowUpRight,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Field,Empty,type Mutate} from './sessions';
import {money,prettyDate,type AppState} from '@/lib/domain';
export function AdminPortal({state,mutate,busy,navigate}:{state:AppState;mutate:Mutate;busy:boolean;navigate:(p:string)=>void}){const[tab,setTab]=useState('inventory');const[query,setQuery]=useState('');const[fee,setFee]=useState(state.feeBps/100);const[confirm,setConfirm]=useState<{type:string;id:string;message:string}|null>(null);const action=(p:Record<string,unknown>,m?:string)=>void mutate(p,m).catch(()=>{});return <section className="page-width inner-page operations-page"><div className="eyebrow">MARKETPLACE OPERATIONS · DEMO</div><h1>Trust is part of the session.</h1><p className="page-intro">Review inventory, trace bookings and keep marketplace rules transparent.</p><div className="portal-demo-note"><ShieldCheck size={17}/>Isolated demo operations. These controls affect only your sample workspace, never another user or a real provider.</div><Tabs value={tab} onValueChange={setTab}><TabsList className="portal-tabs"><TabsTrigger value="inventory">Inventory & verification</TabsTrigger><TabsTrigger value="bookings">Bookings & payments</TabsTrigger><TabsTrigger value="incidents">Incidents {state.reports.filter(r=>r.status==='open').length>0&&<span className="count">{state.reports.filter(r=>r.status==='open').length}</span>}</TabsTrigger><TabsTrigger value="reviews">Reviews</TabsTrigger><TabsTrigger value="settings">Rules & access</TabsTrigger></TabsList></Tabs>
 {tab==='inventory'&&<div className="panel"><div className="panel-title"><div><h2>Music-ready inventory</h2><p>Check the sample provider and room record. Demo verification does not guarantee safety.</p></div><span>{state.rooms.filter(r=>r.verified).length}/{state.rooms.length} demo checked</span></div><Table><TableHeader><TableRow><TableHead>Room / provider</TableHead><TableHead>Type</TableHead><TableHead>Verification</TableHead><TableHead>Listing status</TableHead><TableHead>Review actions</TableHead></TableRow></TableHeader><TableBody>{state.rooms.map(r=><TableRow key={r.id}><TableCell><button className="table-link" onClick={()=>navigate('/space/'+r.id)}>{r.name}</button><small>{r.venue} · {r.area}</small></TableCell><TableCell>{r.category}</TableCell><TableCell><span className={'status '+(r.verified?'confirmed':'pending_approval')}>{r.verification}</span></TableCell><TableCell>{r.active?'Listed':'Suspended'}</TableCell><TableCell><div className="table-actions"><Button variant="outline" size="sm" disabled={busy} onClick={()=>action({type:'verify',id:r.id},'Demo verification updated')}>{r.verified?'Remove demo check':'Mark demo checked'}</Button><Button variant="ghost" size="sm" onClick={()=>setConfirm({type:'suspend',id:r.id,message:r.active?'Suspend this sample room from discovery? Existing reservations are preserved and can be managed separately.':'Restore this sample room to discovery?'})}>{r.active?'Suspend':'Restore'}</Button></div></TableCell></TableRow>)}</TableBody></Table></div>}
 {tab==='bookings'&&<div className="panel"><div className="panel-title"><div><h2>Every booking has a paper trail.</h2><p>USD amounts, explicit booking states and separate payment/refund states.</p></div><div className="lookup"><Search size={16}/><input placeholder="Find reference, room or group" aria-label="Look up booking" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{state.bookings.length?<Table><TableHeader><TableRow><TableHead>Reference</TableHead><TableHead>Session</TableHead><TableHead>Booking</TableHead><TableHead>Payment</TableHead><TableHead>Total</TableHead><TableHead>Refund</TableHead></TableRow></TableHeader><TableBody>{state.bookings.filter(b=>(b.id+b.roomName+b.groupName).toLowerCase().includes(query.toLowerCase())).map(b=><TableRow key={b.id}><TableCell><button className="table-link" onClick={()=>navigate('/booking/'+b.id)}>{b.id}</button></TableCell><TableCell>{b.roomName}<small>{prettyDate(b.date)} · {b.groupName}</small></TableCell><TableCell>{b.status.replaceAll('_',' ')}</TableCell><TableCell>{b.payment.replaceAll('_',' ')} · demo</TableCell><TableCell>{money(b.total)}</TableCell><TableCell>{money(b.refund)}</TableCell></TableRow>)}</TableBody></Table>:<Empty title="No bookings to inspect yet." description="Complete the musician booking flow to create a traceable demo transaction."/>}</div>}
 {tab==='incidents'&&<div className="panel"><h2>Take every concern seriously.</h2><p>Reports from the booking detail page arrive in this persistent demo queue. No external support messages are sent.</p>{state.reports.length?state.reports.map(r=><article className="incident-card" key={r.id}><div><AlertCircle size={22}/><div><span className={'status '+(r.status==='open'?'pending_approval':'confirmed')}>{r.status}</span><button className="table-link" onClick={()=>navigate('/booking/'+r.bookingId)}>{r.bookingId}</button><p>{r.reason}</p><small>{new Date(r.createdAt).toLocaleString()}</small></div></div>{r.status==='open'&&<Button disabled={busy} variant="outline" onClick={()=>action({type:'resolve',id:r.id},'Demo incident resolved')}>Mark resolved</Button>}</article>):<Empty title="No open concerns." description="Any incident or dispute reported on a demo booking will appear here for review."/>}</div>}
 {tab==='reviews'&&<div className="panel"><h2>Reviews backed by completed bookings.</h2><p>Moderation hides a review from discovery and room details without deleting its record.</p>{state.bookings.some(b=>b.review)?state.bookings.filter(b=>b.review).map(b=><article className="incident-card" key={b.id}><div><div><strong>{b.groupName} · {b.roomName}</strong><span className="status">{b.review!.rating}/5 · {b.review!.hidden?'Hidden':'Published'}</span><p>{b.review!.text}</p><small>{b.id} · Completed demo booking</small></div></div><Button disabled={busy} variant="outline" onClick={()=>action({type:'moderateReview',id:b.id},'Review visibility updated')}>{b.review!.hidden?'Restore review':'Hide review'}</Button></article>):<Empty title="No reviews yet." description="A completed demo booking is required before the musician can review a room."/>}</div>}
 {tab==='settings'&&<div className="profile-layout"><form className="panel stack-form" onSubmit={e=>{e.preventDefault();action({type:'fee',feeBps:Math.round(fee*100)},'Service fee updated for future bookings')}}><SlidersHorizontal size={25}/><h2>Configurable service fee</h2><p>The sample starts at 10% as a planning assumption. This setting applies to future bookings only; existing receipts keep their original amounts.</p><Field label="Platform service fee (%)"><input required type="number" min="0" max="30" step="0.1" value={fee} onChange={e=>setFee(Number(e.target.value))}/></Field><Button disabled={busy}>Save service fee</Button><div className="info-box"><Info size={17}/>Provider hourly prices stay independently controlled by each provider. This fee is added transparently at checkout.</div></form><div className="panel"><h2>Access & integration status</h2><div className="integration-status"><span>Workspace identity<strong>ChatGPT sign-in</strong></span><span>Public email / SMS login<strong>Not connected</strong></span><span>Saved marketplace state<strong>D1 persistence</strong></span><span>Room photo uploads<strong>R2 storage</strong></span><span>Payment / payout rails<strong>Simulated</strong></span><span>Currency<strong>USD · ZiG-ready model</strong></span><span>Search interpretation<strong>Rules-based demo</strong></span><span>Notifications<strong>Manual share only</strong></span></div><p>All roles here are demo personas for the same signed-in owner. A public launch needs real organisation memberships, administrator roles, verification procedures and production payment integrations.</p>{state.user&&<div className="info-box"><UsersIcon/>{state.user.email}<br/>Current demo owner</div>}</div></div>}
 <AlertDialog open={!!confirm} onOpenChange={o=>!o&&setConfirm(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Update listing availability?</AlertDialogTitle><AlertDialogDescription>{confirm?.message}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Go back</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{if(confirm)action({type:confirm.type,id:confirm.id},'Listing updated');setConfirm(null)}}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>}
function UsersIcon(){return <ShieldCheck size={20}/>}
