'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,KeyRound,LogOut,Mail,RefreshCw,ShieldCheck,Smartphone,Trash2} from 'lucide-react';
import QRCode from 'qrcode';
import {Button} from '@/components/ui/button';
import {Field} from './registry-ui';
import {bootstrapServerSession,clearServerSession,getAuthConfig,getSupabaseBrowser,registerBrowserDevice,type PublicAuthConfig} from '@/lib/supabase-browser';
import {normalizeZimbabwePhone,isSixDigitOtp} from '@/lib/identity-core';

declare global{interface Window{turnstile?:{render:(container:HTMLElement,options:{sitekey:string;callback:(token:string)=>void;'expired-callback':()=>void;'error-callback':()=>void})=>string;remove:(id:string)=>void}}}

function Captcha({config,onToken}:{config:PublicAuthConfig;onToken:(token:string)=>void}){
 const container=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  if(config.captchaProvider!=='turnstile'||!config.captchaSiteKey||!container.current)return;
  let widget='';let cancelled=false;
  const render=()=>{if(cancelled||!container.current||!window.turnstile)return;widget=window.turnstile.render(container.current,{sitekey:config.captchaSiteKey!,callback:onToken,'expired-callback':()=>onToken(''),'error-callback':()=>onToken('')})};
  const existing=document.querySelector<HTMLScriptElement>('script[data-sessions-turnstile]');
  if(window.turnstile)render();else if(existing)existing.addEventListener('load',render,{once:true});else{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.dataset.sessionsTurnstile='1';script.addEventListener('load',render,{once:true});document.head.appendChild(script)}
  return()=>{cancelled=true;if(widget&&window.turnstile)window.turnstile.remove(widget)};
 },[config.captchaProvider,config.captchaSiteKey,onToken]);
 if(config.captchaProvider!=='turnstile'||!config.captchaSiteKey)return null;
 return <div ref={container} className="r-captcha" aria-label="Bot protection check"/>;
}

const safeReturn=(value:string)=>value.startsWith('/')&&!value.startsWith('//')?value:'/account';
const completionUrl=(returnTo:string)=>typeof window==='undefined'?'/auth/complete':new URL(`/auth/complete?return_to=${encodeURIComponent(safeReturn(returnTo))}`,window.location.origin).toString();

export function AuthSignIn({returnTo}:{returnTo:string}){
 const[config,setConfig]=useState<PublicAuthConfig|null>(null),[channel,setChannel]=useState<'phone'|'email'>('phone'),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[normalized,setNormalized]=useState(''),[otp,setOtp]=useState(''),[step,setStep]=useState<'entry'|'otp'|'email_sent'>('entry'),[captcha,setCaptcha]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[wait,setWait]=useState(0);
 useEffect(()=>{void getAuthConfig().then(value=>{setConfig(value);if(!value.phoneEnabled&&value.emailEnabled)setChannel('email')}).catch(()=>setError('Sign-in configuration is unavailable.'))},[]);
 useEffect(()=>{if(!wait)return;const timer=window.setInterval(()=>setWait(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[wait]);
 const captchaReady=!config?.captchaProvider||!!captcha;
 async function requestPhone(e:React.FormEvent){e.preventDefault();setError('');let value='';try{value=normalizeZimbabwePhone(phone)}catch(reason){setError(reason instanceof Error?reason.message:'Enter a valid phone number.');return}setBusy(true);try{const client=await getSupabaseBrowser();if(!client)throw new Error('Phone sign-in is not open yet.');const{error}=await client.auth.signInWithOtp({phone:value,options:{captchaToken:captcha||undefined}});if(error)throw error;setNormalized(value);setStep('otp');setWait(60)}catch(reason){setError(reason instanceof Error?reason.message:'We could not send the code. Try again later.')}finally{setBusy(false)}}
 async function requestEmail(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const client=await getSupabaseBrowser();if(!client)throw new Error('Email sign-in is not open yet.');const{error}=await client.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:completionUrl(returnTo),captchaToken:captcha||undefined,shouldCreateUser:true}});if(error)throw error;setStep('email_sent');setWait(60)}catch(reason){setError(reason instanceof Error?reason.message:'We could not send the email. Try again later.')}finally{setBusy(false)}}
 async function verifyCode(e:React.FormEvent){e.preventDefault();setError('');if(!isSixDigitOtp(otp)){setError('Enter the six-digit code.');return}setBusy(true);try{const client=await getSupabaseBrowser();if(!client)throw new Error('Phone sign-in is not open yet.');const{error}=await client.auth.verifyOtp({phone:normalized,token:otp,type:'sms'});if(error)throw error;await registerBrowserDevice();await bootstrapServerSession();window.dispatchEvent(new Event('sessions-auth-changed'));window.location.assign(safeReturn(returnTo))}catch(reason){setError(reason instanceof Error?reason.message:'The code was not accepted. Request a new one.')}finally{setBusy(false)}}
 async function oauth(provider:'google'|'apple'){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)throw new Error(`${provider==='google'?'Google':'Apple'} sign-in is not open yet.`);const{error}=await client.auth.signInWithOAuth({provider,options:{redirectTo:completionUrl(returnTo)}});if(error)throw error}catch(reason){setError(reason instanceof Error?reason.message:'Social sign-in could not start.');setBusy(false)}}
 if(!config)return <div className="r-panel r-auth-panel"><span className="r-loading">Sign in to continue · checking secure sign-in…</span>{error&&<p className="r-error" role="alert">{error}</p>}</div>;
 if(config.mode==='chatgpt')return <div className="r-panel r-auth-panel"><Smartphone size={28}/><h3>Sessions private UAT</h3><p>The host is currently owner-restricted. ChatGPT access only opens this UAT deployment; it is not the production Sessions identity authority.</p><a className="r-primary" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(returnTo)} target="_top">Continue to private UAT<ArrowRight size={16}/></a></div>;
 if(!config.enabled||(!config.phoneEnabled&&!config.emailEnabled&&!config.googleEnabled&&!config.appleEnabled))return <div className="r-panel r-auth-panel"><ShieldCheck size={28}/><h3>Sessions accounts are not open yet</h3><p>The identity boundary is installed, but providers remain closed until their live Supabase configuration and delivery tests pass.</p></div>;
 return <div className="r-panel r-form r-auth-panel" data-sessions-auth="native"><ShieldCheck size={28}/><h3>Sign in or create your Sessions account</h3><p>One identity follows you across your personal account, studio workspaces and Sessions staff access.</p>{error&&<p className="r-error" role="alert">{error}</p>}
 {step==='entry'&&<><div className="r-auth-channel" role="tablist" aria-label="Sign-in method">{config.phoneEnabled&&<button type="button" className={channel==='phone'?'active':''} onClick={()=>setChannel('phone')}><Smartphone size={16}/>Phone</button>}{config.emailEnabled&&<button type="button" className={channel==='email'?'active':''} onClick={()=>setChannel('email')}><Mail size={16}/>Email</button>}</div>{channel==='phone'&&config.phoneEnabled?<form className="r-form" onSubmit={requestPhone}><Field label="Zimbabwe mobile number" hint="We normalize local numbers to +263. A +263 number is a contact identity, not proof of citizenship."><input type="tel" autoComplete="tel" inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="077 123 4567" required/></Field><Captcha config={config} onToken={setCaptcha}/><Button disabled={busy||!captchaReady}>{busy?'Sending…':'Send six-digit code'}</Button></form>:config.emailEnabled?<form className="r-form" onSubmit={requestEmail}><Field label="Email address"><input type="email" autoComplete="email" inputMode="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com" required/></Field><Captcha config={config} onToken={setCaptcha}/><Button disabled={busy||!captchaReady}>{busy?'Sending…':'Send secure sign-in email'}</Button></form>:null}</>}
 {step==='otp'&&<form className="r-form" onSubmit={verifyCode}><span className="r-badge"><CheckCircle2 size={14}/>Code sent to {normalized}</span><Field label="Six-digit code"><input value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" maxLength={6} required/></Field><Button disabled={busy||!isSixDigitOtp(otp)}>{busy?'Checking…':'Verify and continue'}</Button><button type="button" className="r-link" disabled={busy||wait>0} onClick={()=>{setStep('entry');setOtp('')}}>{wait?`Request another code in ${wait}s`:'Use another number'}</button></form>}
 {step==='email_sent'&&<div className="r-auth-confirm"><Mail size={24}/><strong>Check your email</strong><p>Open the secure Sessions link on this device to finish sign-in. The link returns you to the journey you were trying to continue.</p><button type="button" className="r-link" disabled={wait>0} onClick={()=>setStep('entry')}>{wait?`Send another email in ${wait}s`:'Use another email'}</button></div>}
 {(config.googleEnabled||config.appleEnabled)&&step==='entry'&&<><div className="r-auth-divider"><span>or</span></div>{config.googleEnabled&&<Button type="button" variant="outline" disabled={busy} onClick={()=>{void oauth('google')}}>Continue with Google</Button>}{config.appleEnabled&&<Button type="button" variant="outline" disabled={busy} onClick={()=>{void oauth('apple')}}>Continue with Apple</Button>}</>}
 </div>;
}

type Device={session_id:string;device_name:string;platform:string;created_at:string;last_seen_at:string;revoked_at:string|null};
type Factor={id:string;friendly_name?:string;status:string;created_at:string;updated_at:string;factor_type:string};
export function AccountSecurity({userId,contact}:{userId:string;contact:string}){
 const[devices,setDevices]=useState<Device[]>([]),[factors,setFactors]=useState<Factor[]>([]),[aal,setAal]=useState<{currentLevel:string|null;nextLevel:string|null}>({currentLevel:null,nextLevel:null}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deletion,setDeletion]=useState(false),[qr,setQr]=useState(''),[pendingFactor,setPendingFactor]=useState(''),[mfaCode,setMfaCode]=useState(''),[stepUpFactor,setStepUpFactor]=useState(''),[stepUpCode,setStepUpCode]=useState(''),[newEmail,setNewEmail]=useState(''),[newPhone,setNewPhone]=useState('');
 async function load(){const client=await getSupabaseBrowser();if(!client)return;await registerBrowserDevice();const[{data:deviceData,error:deviceError},{data:factorData,error:factorError},{data:aalData,error:aalError}]=await Promise.all([client.from('device_sessions').select('session_id,device_name,platform,created_at,last_seen_at,revoked_at').order('last_seen_at',{ascending:false}),client.auth.mfa.listFactors(),client.auth.mfa.getAuthenticatorAssuranceLevel()]);if(deviceError)throw deviceError;if(factorError)throw factorError;if(aalError)throw aalError;setDevices((deviceData||[]) as Device[]);setFactors(((factorData?.totp||[]) as unknown as Factor[]));setAal({currentLevel:aalData.currentLevel,nextLevel:aalData.nextLevel})}
 useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:'Security controls unavailable.'))},[]);
 async function signOut(scope:'local'|'others'|'global'){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.auth.signOut({scope});if(error)throw error;if(scope==='others')await load();else{await clearServerSession();window.location.assign('/welcome')}}catch(reason){setError(reason instanceof Error?reason.message:'Sign-out failed.')}finally{setBusy(false)}}
 async function revoke(sessionId:string){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.rpc('revoke_device',{target_session_id:sessionId});if(error)throw error;await load()}catch(reason){setError(reason instanceof Error?reason.message:'Device revocation failed.')}finally{setBusy(false)}}
 async function enrollMfa(){setBusy(true);setError('');setNotice('');try{const client=await getSupabaseBrowser();if(!client)throw new Error('MFA is unavailable.');const{data,error}=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'Sessions authenticator'});if(error)throw error;setPendingFactor(data.id);setQr(await QRCode.toDataURL(data.totp.uri,{margin:1,width:220}));setMfaCode('')}catch(reason){setError(reason instanceof Error?reason.message:'MFA enrollment could not start.')}finally{setBusy(false)}}
 async function verifyEnrollment(){if(!pendingFactor||!isSixDigitOtp(mfaCode))return;setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)throw new Error('MFA is unavailable.');const{error}=await client.auth.mfa.challengeAndVerify({factorId:pendingFactor,code:mfaCode});if(error)throw error;await client.auth.refreshSession();await bootstrapServerSession();setQr('');setPendingFactor('');setMfaCode('');setNotice('Authenticator verified. This session is now eligible for AAL2 privileged workflows.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'The authenticator code was not accepted.')}finally{setBusy(false)}}
 async function stepUp(){if(!stepUpFactor||!isSixDigitOtp(stepUpCode))return;setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)throw new Error('MFA is unavailable.');const{error}=await client.auth.mfa.challengeAndVerify({factorId:stepUpFactor,code:stepUpCode});if(error)throw error;await client.auth.refreshSession();await bootstrapServerSession();setStepUpCode('');setNotice('MFA verification completed for this session.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'MFA verification failed.')}finally{setBusy(false)}}
 async function removeFactor(factorId:string){setBusy(true);setError('');try{if(aal.currentLevel!=='aal2'&&factors.some(f=>f.status==='verified'))throw new Error('Verify MFA for this session before removing a factor.');const client=await getSupabaseBrowser();if(!client)throw new Error('MFA is unavailable.');const{error}=await client.auth.mfa.unenroll({factorId});if(error)throw error;setNotice('Authenticator removed. Review your remaining recovery methods.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'MFA factor could not be removed.')}finally{setBusy(false)}}
 async function updateRecovery(kind:'email'|'phone'){setBusy(true);setError('');setNotice('');try{if(factors.some(f=>f.status==='verified')&&aal.currentLevel!=='aal2')throw new Error('Verify MFA for this session before changing a recovery identity.');const client=await getSupabaseBrowser();if(!client)throw new Error('Account recovery controls are unavailable.');const attributes=kind==='email'?{email:newEmail.trim().toLowerCase()}:{phone:normalizeZimbabwePhone(newPhone)};const{error}=await client.auth.updateUser(attributes);if(error)throw error;setNotice(kind==='email'?'Check the new email address to confirm the change. Your current authority is not copied to another account.':'Complete the provider verification sent to the new phone. WhatsApp consent remains separate.');if(kind==='email')setNewEmail('');else setNewPhone('')}catch(reason){setError(reason instanceof Error?reason.message:'Recovery identity change could not start.')}finally{setBusy(false)}}
 async function requestDeletion(){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.from('account_deletion_requests').insert({user_id:userId});if(error)throw error;setDeletion(true);await client.auth.signOut({scope:'global'});await clearServerSession()}catch(reason){setError(reason instanceof Error?reason.message:'Deletion request could not be saved.')}finally{setBusy(false)}}
 const verified=factors.filter(f=>f.status==='verified');
 return <div className="r-account-security">{error&&<p className="r-error" role="alert">{error}</p>}{notice&&<p className="r-notice" role="status">{notice}</p>}
  <div className="r-panel"><ShieldCheck size={24}/><h2>Multi-factor authentication</h2><p>Current assurance: <strong>{aal.currentLevel||'unknown'}</strong>. TOTP secrets remain with Supabase/authenticator enrollment and are never written to Sessions D1.</p>{verified.length?<div className="r-device-list">{verified.map(factor=><div key={factor.id}><KeyRound size={18}/><span><strong>{factor.friendly_name||'Authenticator app'}</strong><small>Verified · added {new Date(factor.created_at).toLocaleDateString()}</small></span><Button variant="ghost" disabled={busy} onClick={()=>void removeFactor(factor.id)}>Remove</Button></div>)}</div>:<p className="r-muted">No verified authenticator is enrolled yet.</p>}
   {verified.length>0&&aal.currentLevel!=='aal2'&&<div className="r-form"><Field label="Verify existing authenticator" hint="Required before privileged administration and sensitive recovery changes."><select value={stepUpFactor} onChange={e=>setStepUpFactor(e.target.value)}><option value="">Choose authenticator</option>{verified.map(f=><option key={f.id} value={f.id}>{f.friendly_name||'Authenticator'}</option>)}</select></Field><Field label="Six-digit authenticator code"><input inputMode="numeric" autoComplete="one-time-code" value={stepUpCode} onChange={e=>setStepUpCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></Field><Button disabled={busy||!stepUpFactor||!isSixDigitOtp(stepUpCode)} onClick={()=>void stepUp()}>Verify MFA</Button></div>}
   {!pendingFactor?<Button variant="outline" disabled={busy} onClick={()=>void enrollMfa()}><KeyRound size={16}/>Add authenticator</Button>:<div className="r-form r-mfa-enroll"><strong>Scan with your authenticator app</strong>{qr&&<img src={qr} width="220" height="220" alt="Authenticator QR code"/>}<p>After scanning, enter the current six-digit code. Closing this step abandons the unverified factor.</p><Field label="Six-digit code"><input inputMode="numeric" autoComplete="one-time-code" value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></Field><div className="r-button-row"><Button disabled={busy||!isSixDigitOtp(mfaCode)} onClick={()=>void verifyEnrollment()}>Verify authenticator</Button><Button variant="outline" type="button" onClick={()=>{setPendingFactor('');setQr('');setMfaCode('')}}>Cancel</Button></div></div>}
  </div>
  <div className="r-panel"><Smartphone size={24}/><h2>Recovery identities</h2><p>Signed in as {contact}. Changes require provider verification; Sessions never auto-merges another account or transfers studio/corporate authority from a matching email or phone.</p><div className="r-form"><Field label="New recovery email"><input type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} autoComplete="email" placeholder="new@example.com"/></Field><Button variant="outline" disabled={busy||!newEmail.includes('@')} onClick={()=>void updateRecovery('email')}><Mail size={16}/>Verify new email</Button><Field label="New Zimbabwe phone"><input type="tel" value={newPhone} onChange={e=>setNewPhone(e.target.value)} autoComplete="tel" placeholder="077 123 4567"/></Field><Button variant="outline" disabled={busy||newPhone.trim().length<7} onClick={()=>void updateRecovery('phone')}><Smartphone size={16}/>Verify new phone</Button></div><p className="r-small">If all sign-in factors are lost, recovery is a support-reviewed identity process. Recovery restores the person’s identity only after verification; it does not recreate revoked employment or provider memberships.</p></div>
  <div className="r-panel"><h2>Devices & sessions</h2><p>Revoking a device blocks its token from Sessions APIs; the short-lived server page session expires with the same verified Supabase access token.</p><div className="r-device-list">{devices.map(device=><div key={device.session_id}><Smartphone size={18}/><span><strong>{device.device_name}</strong><small>Last used {new Date(device.last_seen_at).toLocaleString()} · {device.revoked_at?'Revoked':'Active'}</small></span>{!device.revoked_at&&<Button variant="ghost" disabled={busy} onClick={()=>{void revoke(device.session_id)}}>Revoke</Button>}</div>)}</div><div className="r-button-row"><Button variant="outline" disabled={busy} onClick={()=>{void signOut('local')}}><LogOut size={15}/>Sign out here</Button><Button variant="outline" disabled={busy} onClick={()=>{void signOut('others')}}>Sign out other devices</Button></div></div>
  <div className="r-panel"><Trash2 size={24}/><h2>Delete your account</h2><p>This first records a deletion request so D1 bookings, claims and R2 files can be handled consistently. Operations must complete the deletion audit before the Supabase identity is removed.</p>{deletion?<p className="r-notice">Deletion request recorded. You have been signed out.</p>:<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Request deletion of your Sessions account and sign out everywhere?'))void requestDeletion()}}>Request account deletion</Button>}</div>
 </div>;
}
