'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,LogOut,ShieldCheck,Smartphone,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Field} from './registry-ui';
import {getAuthConfig,getSupabaseBrowser,registerBrowserDevice,type PublicAuthConfig} from '@/lib/supabase-browser';
import {normalizeZimbabwePhone,isSixDigitOtp} from '@/lib/identity-core';

declare global{interface Window{turnstile?:{render:(container:HTMLElement,options:{sitekey:string;callback:(token:string)=>void;'expired-callback':()=>void;'error-callback':()=>void})=>string;remove:(id:string)=>void}}}

function Captcha({config,onToken}:{config:PublicAuthConfig;onToken:(token:string)=>void}){
 const container=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  if(config.captchaProvider!=='turnstile'||!config.captchaSiteKey||!container.current)return;
  let widget='';let cancelled=false;
  const render=()=>{if(cancelled||!container.current||!window.turnstile)return;widget=window.turnstile.render(container.current,{sitekey:config.captchaSiteKey!,callback:onToken,'expired-callback':()=>onToken(''),'error-callback':()=>onToken('')})};
  const existing=document.querySelector<HTMLScriptElement>('script[data-sessions-turnstile]');
  if(window.turnstile)render();else if(existing)existing.addEventListener('load',render,{once:true});else{const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.defer=true;script.dataset.sessionsTurnstile='1';script.addEventListener('load',render,{once:true});document.head.appendChild(script)}
  return()=>{cancelled=true;if(widget&&window.turnstile)window.turnstile.remove(widget)};
 },[config.captchaProvider,config.captchaSiteKey,onToken]);
 if(config.captchaProvider!=='turnstile'||!config.captchaSiteKey)return null;
 return <div ref={container} className="r-captcha" aria-label="Bot protection check"/>;
}

export function AuthSignIn({returnTo}:{returnTo:string}){
 const[config,setConfig]=useState<PublicAuthConfig|null>(null),[phone,setPhone]=useState(''),[normalized,setNormalized]=useState(''),[otp,setOtp]=useState(''),[step,setStep]=useState<'phone'|'otp'>('phone'),[captcha,setCaptcha]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[wait,setWait]=useState(0);
 useEffect(()=>{void getAuthConfig().then(setConfig).catch(()=>setError('Sign-in configuration is unavailable.'))},[]);
 useEffect(()=>{if(!wait)return;const timer=window.setInterval(()=>setWait(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[wait]);
 const readyForPhone=!!config?.phoneEnabled&&(!config.captchaProvider||!!captcha);
 async function requestCode(e:React.FormEvent){e.preventDefault();setError('');let value='';try{value=normalizeZimbabwePhone(phone)}catch(reason){setError(reason instanceof Error?reason.message:'Enter a valid phone number.');return}setBusy(true);try{const client=await getSupabaseBrowser();if(!client)throw new Error('Phone sign-in is not open yet.');const{error}=await client.auth.signInWithOtp({phone:value,options:{captchaToken:captcha||undefined}});if(error)throw error;setNormalized(value);setStep('otp');setWait(60)}catch(reason){setError(reason instanceof Error?reason.message:'We could not send the code. Try again later.')}finally{setBusy(false)}}
 async function verifyCode(e:React.FormEvent){e.preventDefault();setError('');if(!isSixDigitOtp(otp)){setError('Enter the six-digit code.');return}setBusy(true);try{const client=await getSupabaseBrowser();if(!client)throw new Error('Phone sign-in is not open yet.');const{error}=await client.auth.verifyOtp({phone:normalized,token:otp,type:'sms'});if(error)throw error;await registerBrowserDevice();window.dispatchEvent(new Event('sessions-auth-changed'));window.location.assign(returnTo.startsWith('/')&&!returnTo.startsWith('//')?returnTo:'/account')}catch(reason){setError(reason instanceof Error?reason.message:'The code was not accepted. Request a new one.')}finally{setBusy(false)}}
 async function google(){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)throw new Error('Google sign-in is not open yet.');const redirectTo=new URL(returnTo.startsWith('/')&&!returnTo.startsWith('//')?returnTo:'/account',window.location.origin).toString();const{error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error}catch(reason){setError(reason instanceof Error?reason.message:'Google sign-in could not start.');setBusy(false)}}
 if(!config)return <div className="r-panel r-auth-panel"><span className="r-loading">Sign in to continue · checking secure sign-in…</span>{error&&<p className="r-error" role="alert">{error}</p>}</div>;
 if(config.mode==='chatgpt')return <div className="r-panel r-auth-panel"><Smartphone size={28}/><h3>Private preview sign-in</h3><p>This checkpoint still uses workspace access. Public Supabase identity is present in code but remains disabled until its providers are configured.</p><a className="r-primary" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(returnTo)} target="_top">Continue with ChatGPT<ArrowRight size={16}/></a></div>;
 if(!config.enabled||(!config.phoneEnabled&&!config.googleEnabled))return <div className="r-panel r-auth-panel"><ShieldCheck size={28}/><h3>Public accounts are not open yet</h3><p>The real identity boundary is installed, but sign-in stays hidden until SMS protection and at least one provider pass a live integration test.</p></div>;
 return <div className="r-panel r-form r-auth-panel"><ShieldCheck size={28}/><h3>Sign in to Sessions</h3><p>Use your verified phone number. Your claims, studio access and bookings stay tied to this account.</p>{error&&<p className="r-error" role="alert">{error}</p>}{step==='phone'?<form className="r-form" onSubmit={requestCode}><Field label="Zimbabwe mobile number" hint="We normalize local numbers to +263. Standard SMS charges may apply."><input type="tel" autoComplete="tel" inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="077 123 4567" required/></Field><Captcha config={config} onToken={setCaptcha}/><Button disabled={busy||!readyForPhone}>{busy?'Sending…':'Send six-digit code'}</Button></form>:<form className="r-form" onSubmit={verifyCode}><span className="r-badge"><CheckCircle2 size={14}/>Code sent to {normalized}</span><Field label="Six-digit code"><input value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" maxLength={6} required/></Field><Button disabled={busy||!isSixDigitOtp(otp)}>{busy?'Checking…':'Verify and continue'}</Button><button type="button" className="r-link" disabled={busy||wait>0} onClick={()=>{setStep('phone');setOtp('')}}>{wait?`Request another code in ${wait}s`:'Use another number'}</button></form>}{config.googleEnabled&&<><div className="r-auth-divider"><span>or</span></div><Button type="button" variant="outline" disabled={busy} onClick={()=>{void google()}}>Continue with Google</Button></>}</div>;
}

type Device={session_id:string;device_name:string;platform:string;created_at:string;last_seen_at:string;revoked_at:string|null};
export function AccountSecurity({userId,contact}:{userId:string;contact:string}){
 const[devices,setDevices]=useState<Device[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deletion,setDeletion]=useState(false);
 async function load(){const client=await getSupabaseBrowser();if(!client)return;await registerBrowserDevice();const{data,error}=await client.from('device_sessions').select('session_id,device_name,platform,created_at,last_seen_at,revoked_at').order('last_seen_at',{ascending:false});if(error)throw error;setDevices((data||[]) as Device[])}
 useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:'Session list unavailable.'))},[]);
 async function signOut(scope:'local'|'others'|'global'){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.auth.signOut({scope});if(error)throw error;if(scope==='others')await load();else window.location.assign('/')}catch(reason){setError(reason instanceof Error?reason.message:'Sign-out failed.')}finally{setBusy(false)}}
 async function revoke(sessionId:string){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.rpc('revoke_device',{target_session_id:sessionId});if(error)throw error;await load()}catch(reason){setError(reason instanceof Error?reason.message:'Device revocation failed.')}finally{setBusy(false)}}
 async function requestDeletion(){setBusy(true);setError('');try{const client=await getSupabaseBrowser();if(!client)return;const{error}=await client.from('account_deletion_requests').insert({user_id:userId});if(error)throw error;setDeletion(true);await client.auth.signOut({scope:'global'})}catch(reason){setError(reason instanceof Error?reason.message:'Deletion request could not be saved.')}finally{setBusy(false)}}
 return <div className="r-account-security"><div className="r-panel"><h2>Devices & sessions</h2><p>Signed in as {contact}. Revoking a device blocks its token from Sessions APIs; Supabase access tokens can remain valid until their short expiry.</p>{error&&<p className="r-error" role="alert">{error}</p>}<div className="r-device-list">{devices.map(device=><div key={device.session_id}><Smartphone size={18}/><span><strong>{device.device_name}</strong><small>Last used {new Date(device.last_seen_at).toLocaleString()} · {device.revoked_at?'Revoked':'Active'}</small></span>{!device.revoked_at&&<Button variant="ghost" disabled={busy} onClick={()=>{void revoke(device.session_id)}}>Revoke</Button>}</div>)}</div><div className="r-button-row"><Button variant="outline" disabled={busy} onClick={()=>{void signOut('local')}}><LogOut size={15}/>Sign out here</Button><Button variant="outline" disabled={busy} onClick={()=>{void signOut('others')}}>Sign out other devices</Button></div></div><div className="r-panel"><Trash2 size={24}/><h2>Delete your account</h2><p>This first records a deletion request so D1 bookings, claims and R2 files can be handled consistently. Operations must complete the deletion audit before the Supabase identity is removed.</p>{deletion?<p className="r-notice">Deletion request recorded. You have been signed out.</p>:<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Request deletion of your Sessions account and sign out everywhere?'))void requestDeletion()}}>Request account deletion</Button>}</div></div>;
}
