'use client';
import {ArrowLeft,ArrowRight,Building2,CheckCircle2,Clock3,FileCheck2,ShieldCheck,Store,Users} from 'lucide-react';
import type {OnboardingSnapshot} from '@/lib/onboarding-server';

type Claim={id:string;studioId:string;studioName:string;status:string;createdAt:string;note:string};type Registration={id:string;name:string;status:string;createdAt:string;note:string};type Verification={id:string;studioId:string;studioName:string;status:string;createdAt:string;note:string};type Membership={studioId:string;name:string;role:string;status:string;bookingEnabled:boolean};
export default function ProviderOnboarding({snapshot,claims,registrations,verifications,memberships}:{snapshot:OnboardingSnapshot;claims:Claim[];registrations:Registration[];verifications:Verification[];memberships:Membership[]}){
 const applications=[...claims.map(v=>({...v,kind:'claim' as const,name:v.studioName})),...registrations.map(v=>({...v,kind:'registration' as const,studioId:'',studioName:v.name}))];
 const hasApplication=applications.length>0,hasApprovedApplication=claims.some(v=>v.status==='approved')||registrations.some(v=>v.status==='approved'),hasMembership=memberships.length>0,verified=memberships.some(v=>['verified','bookable'].includes(v.status)),bookable=memberships.some(v=>v.status==='bookable'&&v.bookingEnabled);
 const steps=[
  {title:'Identity & agreements',done:snapshot.profile.status==='active',detail:'Your verified Sessions identity and required service agreements.'},
  {title:'Studio application',done:hasApprovedApplication,current:!hasApprovedApplication,detail:hasApplication?'A claim or registration is in the review workflow.':'Claim a sourced studio or register a studio that is not listed.'},
  {title:'Provider verification',done:verified,current:hasApprovedApplication&&!verified,detail:'Sessions independently reviews ownership/business and premises evidence.'},
  {title:'Organization access',done:hasMembership,current:verified&&!hasMembership,detail:'Provider authority appears only from an approved organization membership.'},
  {title:'Marketplace readiness',done:bookable,current:hasMembership&&!bookable,detail:'Complete rooms, location, rules and availability before accepting booking requests.'},
 ];
 return <main className="prov-onb" data-sessions-surface="provider-onboarding"><header><a href="/account"><ArrowLeft size={16}/>Account</a><span className="prov-kicker"><Building2 size={15}/>PROVIDER ONBOARDING</span><h1>Bring your studio onto Sessions.</h1><p>One reviewed path from identity to a bookable workspace. Starting an application does not grant studio authority.</p></header><div className="prov-grid"><section className="prov-steps"><h2>Your progress</h2>{steps.map((step,index)=><article key={step.title} className={step.done?'done':step.current?'current':''}><span>{step.done?<CheckCircle2/>:step.current?<Clock3/>:<span>{index+1}</span>}</span><div><strong>{step.title}</strong><p>{step.detail}</p></div></article>)}</section><aside className="prov-actions"><div className="prov-card royal"><Store size={24}/><span className="prov-kicker">START / CONTINUE</span><h2>{hasApplication?'Continue your studio application':'Choose how your studio enters Sessions'}</h2><p>If the studio already has a sourced profile, claim it. If it is missing, register it for review.</p><a href="/studios?claim=1">Claim an existing studio<ArrowRight size={16}/></a><a href="/register">Register a new studio<ArrowRight size={16}/></a></div>{hasMembership&&<div className="prov-card"><Users size={23}/><span className="prov-kicker">AUTHORIZED WORKSPACES</span>{memberships.map(item=><a className="prov-workspace" href="/manage" key={item.studioId}><span><strong>{item.name}</strong><small>{item.role} · {item.status}{item.bookingEnabled?' · booking enabled':''}</small></span><ArrowRight size={16}/></a>)}</div>}<div className="prov-card"><ShieldCheck size={23}/><strong>Authority boundary</strong><p>Claims, registrations and verification requests are applications. Only an active organization membership unlocks provider management. A rejected or suspended provider journey never converts itself into access.</p></div></aside></div>
 {applications.length>0&&<section className="prov-history"><span className="prov-kicker"><FileCheck2 size={15}/>APPLICATION HISTORY</span><div className="prov-history-grid">{applications.map(item=><article key={`${item.kind}:${item.id}`}><span className={`prov-status ${item.status}`}>{item.status.replaceAll('_',' ')}</span><h3>{item.name}</h3><p>{item.kind==='claim'?'Ownership claim':'New studio registration'}</p>{item.note&&<small>{item.note}</small>}</article>)}</div></section>}
 {verifications.length>0&&<section className="prov-history"><span className="prov-kicker"><ShieldCheck size={15}/>VERIFICATION HISTORY</span><div className="prov-history-grid">{verifications.map(item=><article key={item.id}><span className={`prov-status ${item.status}`}>{item.status}</span><h3>{item.studioName}</h3><p>Provider verification</p>{item.note&&<small>{item.note}</small>}</article>)}</div></section>}
 </main>;
}
