'use client';
import {useState} from 'react';
import {CheckCircle2,Music2,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {PLANNER_EQUIPMENT,type PlannerEquipment,type RoomEquipmentMap} from '@/lib/discovery';
import {sessionFetch} from '@/lib/supabase-browser';

type Room={id:string;name:string};
export default function RoomEquipmentManager({studioId,studioName,rooms,initial,initialRevision}:{studioId:string;studioName:string;rooms:Room[];initial:RoomEquipmentMap;initialRevision:number}){
 const[equipment,setEquipment]=useState<RoomEquipmentMap>(initial);const[revision,setRevision]=useState(initialRevision);const[saving,setSaving]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');
 const toggle=(roomId:string,item:PlannerEquipment)=>setEquipment(current=>{const values=current[roomId]||[],next=values.includes(item)?values.filter(value=>value!==item):[...values,item];return {...current,[roomId]:next}});
 const save=async(roomId:string)=>{setSaving(roomId);setMessage('');setError('');try{const response=await sessionFetch('/api/room-equipment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studioId,roomId,revision,equipment:equipment[roomId]||[]})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Unable to save room equipment');setRevision(value.revision);setMessage(`${rooms.find(room=>room.id===roomId)?.name||'Room'} equipment saved.`)}catch(value){setError(value instanceof Error?value.message:'Unable to save room equipment')}finally{setSaving('')}};
 return <section className="r-width r-inner"><div className="r-eyebrow"><ShieldCheck size={15}/>OWNER-CONFIRMED ROOM INVENTORY</div><h1>{studioName} · room equipment</h1><p className="r-intro">Confirm equipment for each individual room. Sessions AI and booking discovery use only these room-specific selections for equipment matching; the older studio-wide equipment description is never treated as proof for a room.</p><div className="r-notice"><Music2 size={18}/><span>Only select gear that is normally available in that room. Temporary hires and equipment shared between rooms should remain unselected unless the provider can reliably guarantee it for the booked room.</span></div>{rooms.length===0?<div className="r-empty"><Music2 size={24}/><h2>Add a room first</h2><p>Room equipment can only be confirmed after the room exists in your studio profile.</p><a className="r-primary" href={`/manage/${studioId}?tab=profile`}>Configure rooms</a></div>:<div className="r-form">{rooms.map(room=><article className="r-panel" key={room.id}><div className="r-section-top"><div><span className="r-badge">Room-specific truth</span><h2>{room.name}</h2></div><span className="r-small">{(equipment[room.id]||[]).length} selected</span></div><div className="r-choice-grid" role="group" aria-label={`${room.name} equipment`}>{PLANNER_EQUIPMENT.map(item=>{const checked=(equipment[room.id]||[]).includes(item);return <button key={item} type="button" role="checkbox" aria-checked={checked} className={checked?'r-chip active':'r-chip'} onClick={()=>toggle(room.id,item)}>{checked&&<CheckCircle2 size={14}/>}<span>{item}</span></button>})}</div><div className="r-button-row"><Button disabled={!!saving} onClick={()=>void save(room.id)}>{saving===room.id?'Saving…':'Save room equipment'}</Button></div></article>)}</div>}{message&&<p role="status" className="r-notice"><CheckCircle2 size={17}/>{message}</p>}{error&&<p role="alert" className="r-error">{error}</p>}<div className="r-button-row"><a className="r-secondary" href={`/manage/${studioId}?tab=profile`}>Back to profile & rooms</a><a className="r-secondary" href={`/studio/${studioId}`}>View public studio profile</a></div></section>;
}
