'use client';
import {useEffect,useState} from 'react';
import {Sparkles,ArrowRight,CalendarDays,Users,Wallet,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Field,Choice,CheckField,Empty} from './registry-ui';
import {SignIn} from './registry';
import type {RegistryState} from '@/lib/registry';
import type {PlannerInput,PlanOption} from '@/lib/discovery';
import {localDate,addDays,money,timeLabel,prettyDate} from '@/lib/domain';
export default function SessionPlanner({data}:{data:RegistryState}){
 const[aiReady,setAiReady]=useState(false),[mode,setMode]=useState('guided'),[prompt,setPrompt]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[input,setInput]=useState<PlannerInput>({date:addDays(localDate(),1),start:null,duration:60,size:1,budget:null,area:'',service:'',flexDays:0});
 const[result,setResult]=useState<{mode:string;input:PlannerInput;options:PlanOption[];notice:string;unknownPriceCount:number;checkedAt:string}|null>(null);
 useEffect(()=>{let active=true;fetch('/api/planner').then(r=>r.json()).then(v=>{if(active)setAiReady(!!v.aiReady)}).catch(()=>{});return()=>{active=false}},[]);
 const update=(p:Partial<PlannerInput>)=>{setInput(v=>({...v,...p}));setResult(null)};
 return <section className="r-width r-inner x-planner"><div className="r-eyebrow"><Sparkles size={16}/>YOUR SESSION PLANNER</div><h1>A little less planning.<br/>A lot more playing.</h1><p className="r-intro">Set your budget, bring your people, find a time that works. Every match uses the studio’s published rooms and current calendar.</p><div className="x-planner-layout"><form className="r-panel r-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/planner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,prompt,consent,input})});const value=await r.json();if(!r.ok)throw new Error(value.error);setResult(value);setInput(value.input)}catch(e){setError(e instanceof Error?e.message:'Planning unavailable')}finally{setBusy(false)}}}>
 <Tabs value={mode} onValueChange={v=>{setMode(v);setResult(null)}}><TabsList className="x-mode"><TabsTrigger value="guided">Guided planner</TabsTrigger><TabsTrigger value="ai" disabled={!aiReady}><Sparkles size={15}/>AI assistant</TabsTrigger></TabsList></Tabs>{!aiReady&&<p className="r-small">AI is not connected yet. The guided planner works now; its results are calculated, not AI-generated.</p>}
 {mode==='ai'&&<><Field label="Tell us what you have in mind"><textarea value={prompt} onChange={e=>{setPrompt(e.target.value);setResult(null)}} maxLength={1500} required placeholder="A 2-hour rehearsal this Saturday for 6 people in the CBD, up to $40 total…"/></Field><CheckField checked={consent} onChange={setConsent}>Send this text to OpenAI to interpret my requirements. I will leave out private information.</CheckField><p className="r-small">Your text is sent without your account, precise location or booking history. Review the interpreted fields below. AI never submits bookings.</p></>}
 <div className="r-form-grid"><Field label="Preferred date · CAT"><input type="date" required min={localDate()} max={addDays(localDate(),365)} value={input.date} onChange={e=>update({date:e.target.value})}/></Field><Field label="Start time · CAT (optional)"><input type="time" step="1800" value={input.start===null?'':`${Math.floor(input.start/60).toString().padStart(2,'0')}:${(input.start%60).toString().padStart(2,'0')}`} onChange={e=>update({start:e.target.value?e.target.value.split(':').reduce((a,n,i)=>a+Number(n)*(i===0?60:1),0):null})}/></Field><Choice label="Duration" value={String(input.duration)} onChange={v=>update({duration:Number(v)})} options={[30,60,90,120,180,240,480].map(n=>({value:String(n),label:`${n} minutes`}))}/><Field label="People"><input type="number" min="1" max="200" required value={input.size} onChange={e=>update({size:Number(e.target.value)})}/></Field><Field label="Total budget · USD (optional)"><input type="number" min="1" max="100000" step="0.01" value={input.budget===null?'':input.budget/100} onChange={e=>update({budget:e.target.value?Math.round(Number(e.target.value)*100):null})}/></Field><Choice label="Date flexibility" value={String(input.flexDays)} onChange={v=>update({flexDays:Number(v)})} options={[{value:'0',label:'Exact date'},{value:'2',label:'Up to 2 days later'},{value:'7',label:'Up to 7 days later'}]}/></div><Field label="Neighbourhood (optional)"><input value={input.area} onChange={e=>update({area:e.target.value})} maxLength={80} placeholder="Harare CBD, Greendale…"/></Field><Choice label="Service" value={input.service||'any'} onChange={v=>update({service:v==='any'?'':v})} options={['any','Rehearsal','Recording','Lessons','Podcasts'].map(v=>({value:v,label:v==='any'?'Any service':v}))}/>
 {error&&<p className="r-error" role="alert">{error}</p>}{data.user?<Button disabled={busy||(mode==='ai'&&!consent)}>{busy?'Checking studio calendars…':mode==='ai'?'Interpret & find sessions':'Find sessions within budget'}<ArrowRight size={16}/></Button>:<SignIn path="/planner"/>}</form>
 <div className="x-plan-results" aria-live="polite">{result?<><span className="r-badge claimed"><CheckCircle2 size={14}/>{result.mode==='ai'?'AI interpreted · calendar checked':'Guided search · calendar checked'}</span><h2>{result.options.length?'Your possible sessions':'No confirmed matches yet'}</h2><p>{prettyDate(result.input.date)}{result.input.flexDays?` + ${result.input.flexDays} days`:''} · {result.input.duration} minutes · {result.input.size} people · {result.input.budget===null?'any budget':money(result.input.budget)+' maximum'}</p><p className="r-small">{result.notice}</p>{result.options.map((o,i)=><article className="r-panel x-option" key={`${o.studioId}-${o.roomId}-${o.date}-${o.start}`}><span className="r-small">OPTION {i+1}</span><h3>{o.studioName}</h3><p>{o.roomName} · up to {o.capacity} people</p><p><CalendarDays size={15}/>{prettyDate(o.date)} · {timeLabel(o.start)} CAT</p><strong className="x-option-price">{money(o.price)} <small>total</small></strong>{o.discount>0&&<p className="r-small">{money(o.basePrice)} − {money(o.discount)} active membership discount</p>}<a className="r-primary" href={'/studio/'+o.studioId+'?'+new URLSearchParams({room:o.roomId,date:o.date,start:String(o.start),duration:String(o.duration),size:String(o.size)})+'#real-booking'}>Review & request<ArrowRight size={15}/></a></article>)}{!result.options.length&&<Empty title="Try a wider search">Try another area, a smaller group, a different date or a higher budget. {result.unknownPriceCount} studios have no published rates, so we cannot promise they fit your budget. <a href="/">Browse and contact those studios</a>.</Empty>}</>:<div className="x-planner-guide"><Sparkles size={36}/><h2>Make room for your next idea.</h2><div><Wallet/><p><strong>A budget that stays yours.</strong>We calculate the full room price, including any active membership discount.</p></div><div><Users/><p><strong>Enough space for everyone.</strong>Only rooms that fit your group make the shortlist.</p></div><div><CalendarDays/><p><strong>A time you can actually request.</strong>Opening hours, reset buffers and existing bookings are checked together.</p></div><p className="r-small">The registry is still being claimed. Studios with missing rates or closed calendars cannot appear as bookable matches.</p></div>}</div></div></section>;
}
