'use client';
import {useState} from 'react';
import {Building2,ShieldCheck,CheckCircle2,ArrowRight,MapPin,Users,Heart,CreditCard} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Field,CheckField,Choice,Empty,type RegistryAction} from './registry-ui';
import {SignIn} from './registry';
import type {RegistryState,Studio} from '@/lib/registry';
export default function StudioRegistration({data,mutate,busy}:{data:RegistryState;mutate:RegistryAction;busy:boolean}){
 const[step,setStep]=useState(0),[query,setQuery]=useState(''),[consent,setConsent]=useState(false),[category,setCategory]=useState('Recording studio');
 const[memory,setMemory]=useState<Record<string,string>>({});const mine=(data.registrations||[]).filter(r=>r.applicant===data.user?.email.toLowerCase());
 return <section className="r-width r-inner x-onboarding"><div className="r-eyebrow"><Building2 size={16}/>FOR STUDIO OWNERS</div><h1>Your space belongs here.</h1><p className="r-intro">One account. A separate, secure workspace for every studio you own. Claim an existing profile or register a missing studio.</p><div className="r-steps x-registration-steps"><span className={step===0?'active':''}>1 · Find your studio</span><span className={step===1?'active':''}>2 · Business details</span><span className={step===2?'active':''}>3 · Review & submit</span></div>
 {step===0&&<div className="r-panel r-form"><h2>Is your studio already listed?</h2><Field label="Studio name"><input placeholder="Search the existing registry first…" value={query} onChange={e=>setQuery(e.target.value)}/></Field><div className="x-register-matches">{data.studios.filter(s=>!s.hidden&&s.name.toLowerCase().includes(query.toLowerCase())).map(s=><a key={s.id} className="r-contact" href={'/studio/'+s.id}><span><strong>{s.name}</strong><small>{s.address}</small></span><span>{s.status==='claimed'?'View profile':'Claim profile'}<ArrowRight size={15}/></span></a>)}</div><div className="r-button-row"><Button onClick={()=>setStep(1)}>My studio is missing — register it</Button><a className="r-link" href="/account">Studio login & application status</a></div><p className="r-small">Registration does not bypass ownership verification. Do not create a second listing for a studio already here.</p></div>}
 {step===1&&(data.user?<form className="r-panel r-form" onSubmit={e=>{e.preventDefault();setMemory(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);setStep(2)}}><h2>Tell us about your studio</h2><p>Business details become public only after review. Your name, sign-in email and ownership evidence stay private to you and the reviewer.</p><div className="r-form-grid"><Field label="Studio name"><input name="name" defaultValue={memory.name} required minLength={3} maxLength={120}/></Field><Field label="Neighbourhood"><input name="area" defaultValue={memory.area} required minLength={2} maxLength={80}/></Field></div><Field label="Full visitor address"><input name="address" defaultValue={memory.address} required minLength={10} maxLength={300} placeholder="Room / floor, building, street number and name, Harare"/></Field><Choice label="Studio type" value={category} onChange={setCategory} options={['Recording studio','Rehearsal studio','Music institution','Production facility']}/><Field label="Studio description"><textarea name="description" defaultValue={memory.description} required minLength={30} maxLength={2000}/></Field><Field label="Existing official website or business social profile"><input name="website" type="url" pattern="https://.*" defaultValue={memory.website} required maxLength={1000}/></Field><Field label="Public studio phone"><input name="phone" type="tel" defaultValue={memory.phone} required minLength={7} maxLength={40}/></Field><Field label="Your full name and role"><input name="representative" defaultValue={memory.representative} required minLength={2} maxLength={120}/></Field><Field label="How can we independently verify your authority?" hint="Use an existing public business channel. Never include passwords, ID documents or bank details."><textarea name="evidence" defaultValue={memory.evidence} required minLength={30} maxLength={2000}/></Field><div className="r-button-row"><Button type="button" variant="outline" onClick={()=>setStep(0)}>Back to search</Button><Button>Review application<ArrowRight size={16}/></Button></div></form>:<SignIn path="/register"/>)}
 {step===2&&<div className="r-panel r-form"><span className="r-badge"><ShieldCheck size={14}/>Independent review required</span><h2>Check your registration</h2><dl className="x-review"><dt>Studio</dt><dd>{memory.name} · {category}</dd><dt>Address</dt><dd>{memory.address}</dd><dt>Public contact</dt><dd>{memory.phone}<br/>{memory.website}</dd><dt>Representative</dt><dd>{memory.representative} · {data.user?.email}</dd></dl><p>{memory.description}</p><CheckField checked={consent} onChange={setConsent}>I am authorised to register this studio, the public details are accurate, and I consent to independent review. I understand that no management access is granted until approval.</CheckField><div className="r-button-row"><Button variant="outline" onClick={()=>setStep(1)}>Edit details</Button><Button disabled={busy||!consent} onClick={()=>{void mutate({type:'registerStudio',...memory,category,consent},'Registration submitted. Track its independent review below.').then(()=>{setStep(0);setMemory({});setConsent(false)}).catch(()=>{})}}>Submit for review</Button></div></div>}
 {mine.length>0&&<div><h2>Your studio registrations</h2>{mine.map(r=><div className="r-panel" key={r.id}><span className="r-badge">{r.status}</span><h3>{r.name}</h3><p>{r.note||'Awaiting independent review. No booking or management access has been granted yet.'}</p>{r.studioId&&<a className="r-primary" href={'/onboarding/'+r.studioId}>Set up your studio<ArrowRight size={16}/></a>}</div>)}</div>}<p className="r-small">Applications are saved after submission. You can return later using the same sign-in account. Details in an unsubmitted form are not saved if you leave this page.</p></section>;
}
export function OnboardingChecklist({studio:s,data,onStep}:{studio:Studio;data:RegistryState;onStep?:(tab:string)=>void}){
 const steps=[{title:'Ownership verified',detail:'Your authority was reviewed independently.',done:s.status==='claimed',icon:ShieldCheck,tab:'profile'},{title:'Visitor address & confirmed pin',detail:'Help near-me search find the actual entrance.',done:!!s.location&&s.address.length>=10,icon:MapPin,tab:'profile'},{title:'Rooms, capacities & prices',detail:'Give every room a safe group limit and a USD hourly price.',done:!!s.rooms.length,icon:Building2,tab:'profile'},{title:'Introduce your team',detail:'Staff accept their own invitations and control their visibility. Optional.',done:data.staff.some(m=>m.studioId===s.id),icon:Users,tab:'team'},{title:'Memberships for regulars',detail:'Choose discounts, fees and priority-review benefits. Optional.',done:!!s.memberPlans?.some(p=>p.active),icon:Heart,tab:'memberships'},{title:'Open your calendar',detail:'Review rules, hours and contact details, then enable booking requests.',done:s.bookingEnabled,icon:CheckCircle2,tab:'profile'}];
 return <div className="r-panel x-checklist"><div className="r-section-top"><div><h2>Your studio launch checklist</h2><p>{steps.filter(s=>s.done).length} of {steps.length} steps complete, including optional steps. Each save is kept in your studio workspace.</p></div><span className="r-badge">{s.bookingEnabled?'Taking requests':'Setup in progress'}</span></div><div className="x-checklist-grid">{steps.map(({title,detail,done,icon:Icon,tab})=><button type="button" key={title} className={done?'done':''} onClick={()=>onStep?onStep(tab):window.location.assign('/manage/'+s.id+'?tab='+tab)}><span>{done?<CheckCircle2 size={22}/>:<Icon size={22}/>}</span><div><strong>{title}</strong><p>{detail}</p></div><ArrowRight size={16}/></button>)}</div><a className="r-link" href={'/subscriptions?studio='+s.id}><CreditCard size={16}/>Review platform subscriptions & payment setup</a></div>;
}
export function StudioOnboarding({data,path}:{data:RegistryState;path:string}){const id=path.split('/')[2],s=data.studios.find(s=>s.id===id);return <section className="r-width r-inner"><h1>{s?.name||'Studio onboarding'}</h1>{!data.user?<SignIn path={path}/>:!s||!data.ownerIds.includes(id)?<Empty title="Verified studio owner access required">Find your studio and claim it first. <a href="/register">Start registration or claim</a>.</Empty>:<OnboardingChecklist studio={s} data={data}/>}</section>}
export function RegistrationReviews({data,mutate,busy}:{data:RegistryState;mutate:RegistryAction;busy:boolean}){
 const[selected,setSelected]=useState(''),[contact,setContact]=useState(false),[authority,setAuthority]=useState(false),[decision,setDecision]=useState('approved');const rows=data.registrations||[];
 return <div><h2>New studio registrations</h2>{!rows.length?<Empty title="No new registrations">Owners of missing studios can apply at Register studio.</Empty>:rows.map(r=><div className="r-panel" key={r.id}><span className="r-badge">{r.status}</span><h3>{r.name}</h3><p>{r.address}</p><p>{r.representative} · {r.applicant} · {r.phone}</p><a className="r-link" href={r.website} target="_blank" rel="noreferrer">Submitted business source</a><p className="r-preline">{r.evidence}</p>{r.note&&<p>{r.note}</p>}{r.status==='pending'&&r.applicant!==data.user?.email.toLowerCase()&&(selected!==r.id?<Button onClick={()=>{setSelected(r.id);setContact(false);setAuthority(false)}}>Review registration</Button>:<form className="r-form" onSubmit={async e=>{e.preventDefault();try{await mutate({type:'reviewRegistration',id:r.id,decision,note:new FormData(e.currentTarget).get('note'),independentContact:contact,authorityChecked:authority},'Registration review recorded');setSelected('')}catch{}}}><Choice label="Decision" value={decision} onChange={setDecision} options={[{value:'approved',label:'Approve and create claimed studio'},{value:'rejected',label:'Reject / request better evidence'}]}/><Field label="Review reason visible to applicant"><textarea name="note" required minLength={20} maxLength={2000}/></Field><CheckField checked={contact} onChange={setContact}>I checked an independent public business channel and searched for duplicate listings.</CheckField><CheckField checked={authority} onChange={setAuthority}>I assessed the applicant’s authority and recorded my evidence-based decision.</CheckField><Button disabled={busy||!contact||!authority}>Save decision</Button></form>)}{r.applicant===data.user?.email.toLowerCase()&&r.status==='pending'&&<p className="r-small">A separate operator must review your own application.</p>}</div>)}</div>;
}
