'use client';
import {useCallback,useEffect,useState} from 'react';
import {CreditCard,ShieldCheck,ArrowRight,Check,RefreshCw,ExternalLink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Field,Choice,CheckField,Empty} from './registry-ui';
import {SignIn} from './registry';
import type {RegistryState} from '@/lib/registry';
import {money} from '@/lib/domain';
type Billing={amount:number|null;mode:string;merchant:string;support:string;providers:{id:string;name:string;recurring:boolean;ready:boolean}[];account:{provider:string;status:string;paidUntil:string;mode:string}|null;checkouts:{id:string;provider:string;status:string;url?:string;amount:number;mode:string;createdAt:string}[]};
const initial:Billing={amount:null,mode:'test',merchant:'',support:'',providers:[{id:'stripe',name:'Stripe',recurring:true,ready:false},{id:'paypal',name:'PayPal',recurring:true,ready:false},{id:'paynow',name:'Paynow · mobile money & cards',recurring:false,ready:false}],account:null,checkouts:[]};
export default function StudioSubscriptions({data}:{data:RegistryState}){
 const owned=data.studios.filter(s=>data.ownerIds.includes(s.id));const[studioId,setStudioId]=useState(''),[billing,setBilling]=useState(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[provider,setProvider]=useState('stripe'),[error,setError]=useState(''),[key,setKey]=useState('');
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('studio');setStudioId(owned.some(s=>s.id===id)?id!:owned[0]?.id||'');setKey(crypto.randomUUID())},[data.ownerIds.join(',')]);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/billing'+(studioId?'?studio='+encodeURIComponent(studioId):''));const v=await r.json();if(!r.ok)throw new Error(v.error);setBilling(v)}catch(e){setError(e instanceof Error?e.message:'Billing unavailable')}finally{setLoading(false)}},[studioId]);useEffect(()=>{void refresh()},[refresh]);
 const act=async(action:string,id?:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,studioId,provider,id:id||key,consent})});const v=await r.json();if(!r.ok)throw new Error(v.error);if(v.url)window.location.assign(v.url);else await refresh()}catch(e){setError(e instanceof Error?e.message:'Payment action unavailable');await refresh()}finally{setBusy(false)}};
 const selected=billing.providers.find(p=>p.id===provider),active=!!billing.account?.paidUntil&&new Date(billing.account.paidUntil).getTime()>Date.now();
 return <section className="r-width r-inner x-subscriptions"><div className="r-eyebrow"><CreditCard size={16}/>PLANS & PAYMENTS</div><h1>Built for your studio.<br/>Clear about every payment.</h1><p className="r-intro">A studio membership rewards musicians. A platform subscription supports your studio workspace. These are separate agreements.</p><div className="x-subscription-cards"><article className="r-panel"><span className="r-badge claimed">Available now</span><h2>Studio Registry</h2><strong className="x-option-price">Free</strong><p>Your place in Harare’s music community.</p><ul>{['Sourced studio profile and map search','Ownership claim and independent review','Owner workspace, team profiles and bookings','Studio loyalty membership tools'].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul><a className="r-secondary" href="/register">Claim or register your studio<ArrowRight size={16}/></a></article><article className="r-panel x-subscription-featured"><span className="r-badge">{billing.providers.some(p=>p.ready)?billing.mode==='test'?'Test checkout':'Platform subscription':'Payment setup required'}</span><h2>Sessions Studio</h2><strong className="x-option-price">{billing.amount?money(billing.amount):'Price not set'}{billing.amount&&<small> / month</small>}</strong><p>Optional support for the hosted studio workspace. No extra features are paywalled in this release.</p><ul><li><Check size={16}/>One subscription per verified studio</li><li><Check size={16}/>Hosted checkout; no card data stored by Sessions</li><li><Check size={16}/>Provider-verified payment status</li><li><Check size={16}/>Manage recurring agreements with the provider</li></ul><p className="r-small">Stripe and PayPal renew monthly if enabled. Paynow buys a 30-day term with manual renewal, at the displayed term price. A subscription does not verify ownership or reserve rehearsal time.</p></article></div>
 <div className="r-panel r-form"><div className="r-section-top"><div><h2>Choose how to pay</h2><p>{loading?'Checking payment configuration…':billing.providers.some(p=>p.ready)?`Gateway mode: ${billing.mode}. ${billing.mode==='test'?'Test transactions do not move real money.':''}`:'No gateway is connected for checkout. No charge can be made here yet.'}</p></div><ShieldCheck size={28}/></div><RadioGroup className="x-gateways" aria-label="Payment gateway" value={provider} onValueChange={v=>{setProvider(v);setConsent(false);setKey(crypto.randomUUID())}}>{billing.providers.map(p=><label key={p.id} className={provider===p.id?'selected':''}><RadioGroupItem value={p.id} aria-label={p.name}/><CreditCard size={24}/><strong>{p.name}</strong><span>{p.recurring?'Monthly recurring':'30 days · manual renewal'}</span><small>{loading?'Checking…':p.ready?billing.mode==='test'?'Ready for test checkout':'Configured for checkout':'Setup required'}</small></label>)}</RadioGroup><p className="r-small">Payment methods offered inside a provider’s checkout depend on its merchant account, country, currency and approvals. Paynow is the local gateway adapter; no mobile-money method is promised until that account enables it.</p>
 {!data.user?<SignIn path="/subscriptions"/>:!owned.length?<Empty title="Claim your studio first">Only a verified studio owner can purchase or manage its platform subscription. <a href="/register">Claim or register a studio</a>.</Empty>:<><Choice label="Studio subscription" value={studioId||owned[0].id} onChange={v=>{setStudioId(v);setConsent(false);setKey(crypto.randomUUID())}} options={owned.map(s=>({value:s.id,label:s.name}))}/>{billing.account&&<div className="r-notice"><CreditCard size={20}/><div><strong>{active?'Paid term active':'No current paid term'} · {billing.account.provider} · {billing.account.mode}</strong><p>Status: {billing.account.status}{billing.account.paidUntil?' · term ends '+new Date(billing.account.paidUntil).toLocaleDateString('en-GB'):''}</p>{billing.account.provider!=='paynow'&&<Button variant="outline" disabled={busy} onClick={()=>void act('portal')}>Manage / cancel with provider<ExternalLink size={14}/></Button>}</div></div>}
 <div className="x-payment-review"><h3>Before you continue</h3><p>{billing.amount?`${money(billing.amount)} USD ${selected?.recurring?'each month until cancelled':'for 30 days, paid once'}.`:'The subscription amount has not been configured.'} Studio room bookings and loyalty membership fees are not included.</p>{billing.merchant&&<p>Merchant: {billing.merchant} · Support: {billing.support}</p>}<p className="r-small">Review the provider’s final amount and payment agreement before paying. Manage recurring renewals through the provider; cancellation and any refund request must be handled with the merchant. Returning from checkout does not activate a subscription. Sessions verifies status with the provider.</p><CheckField checked={consent} onChange={setConsent}>I understand the displayed price, {selected?.recurring?'monthly automatic renewal':'one-time 30-day term'}, and that this payment supports this studio’s platform workspace.</CheckField><Button disabled={busy||loading||!selected?.ready||!billing.amount||!consent||!studioId||active||billing.checkouts.some(c=>['pending','creating'].includes(c.status))} onClick={()=>void act('checkout')}>{selected?.ready?`Continue to ${selected.name}`:'Checkout unavailable · setup required'}<ArrowRight size={16}/></Button></div>
 {billing.checkouts.length>0&&<div><h3>Payment requests & history</h3><p className="r-small">Returning from a provider is not proof of payment. Refresh the request to verify its status. Pending checkouts prevent accidental duplicate subscriptions.</p>{billing.checkouts.map(c=><div className="x-checkout-row" key={c.id}><div><strong>{c.provider} · {money(c.amount)} · {c.mode}</strong><p>{c.status} · {c.createdAt.slice(0,10)}</p><small>{c.id}</small>{c.status==='creating'&&<p className="r-small">The outcome needs operator reconciliation. Do not create or pay for a duplicate request.</p>}</div><div className="r-button-row">{c.url&&<a href={c.url} className="r-secondary">Resume checkout</a>}<Button variant="outline" disabled={busy} onClick={()=>void act('refresh',c.id)}><RefreshCw size={15}/>Verify status</Button></div></div>)}</div>}</>}{error&&<p className="r-error" role="alert">{error}</p>}</div>
 <div className="r-notice"><ShieldCheck size={21}/><div><strong>Merchant setup comes before live billing.</strong><p>Stripe account/mode selection, approved pricing, secure gateway credentials and reachable verified webhooks are still required. This site’s private access must be considered before enabling provider callbacks. Do not paste keys into profile fields or chat.</p><div className="r-button-row"><a href="https://stripe.com/global" target="_blank" rel="noreferrer">Stripe country availability</a><a href="https://developer.paypal.com/docs/subscriptions/" target="_blank" rel="noreferrer">PayPal subscriptions</a><a href="https://developers.paynow.co.zw/docs/paynow/integration_generation/" target="_blank" rel="noreferrer">Paynow merchant setup</a></div></div></div></section>;
}
