import {z} from 'zod';
import {getProductionUser} from '@/app/chatgpt-auth';
import {database} from '@/db/store';
import {isRegistryUserOperator} from '@/db/registry-store';
import {ensureFoundingPilot,readFeePolicies,validatePolicy,type FeePolicyRecord} from '@/lib/commerce-server';

const text=z.string().trim();const id=text.min(1).max(100);const day=text.regex(/^\d{4}-\d{2}-\d{2}$/);
const createSchema=z.object({type:z.literal('create'),key:z.string().uuid(),scope:z.enum(['global','room']),studioId:id.optional(),roomId:id.optional(),payer:z.enum(['musician','studio','split']),musicianBps:z.number().int().min(0).max(2500),studioBps:z.number().int().min(0).max(2500),basis:z.enum(['room_subtotal','room_plus_addons']),effectiveFrom:day,effectiveUntil:day.optional()}).superRefine((value,ctx)=>{if(value.scope==='room'&&(!value.studioId||!value.roomId))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Room policies require studioId and roomId'});if(value.scope==='global'&&(value.studioId||value.roomId))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Global policies cannot target a room'});if(value.effectiveUntil&&value.effectiveUntil<value.effectiveFrom)ctx.addIssue({code:z.ZodIssueCode.custom,message:'Effective end must not precede effective start'});});
const retireSchema=z.object({type:z.literal('retire'),key:z.string().uuid(),id,revision:z.number().int().min(0)});
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
class Fault extends Error{constructor(message:string,public status:number){super(message)}}
const intervalsOverlap=(aFrom:string,aUntil:string|undefined,bFrom:string,bUntil:string|undefined)=>aFrom<=(bUntil||'9999-12-31')&&bFrom<=(aUntil||'9999-12-31');
async function operationsUser(){const user=await getProductionUser();if(!user)return null;if(!isRegistryUserOperator(user))throw new Fault('Operations role required',403);return user;}
export async function GET(){try{if(!await operationsUser())return response({error:'Sign in to Sessions to continue'},401);return response({policies:await readFeePolicies()})}catch(error){return response({error:error instanceof Error?error.message:'Unable to load fee policies'},403)}}
export async function POST(req:Request){try{
 const origin=req.headers.get('Origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Cross-origin request rejected'},403);
 const user=await operationsUser();if(!user)return response({error:'Sign in to Sessions to continue'},401);if(Number(req.headers.get('content-length')||0)>12000)return response({error:'Request too large'},413);
 const raw=await req.text();if(raw.length>12000)return response({error:'Request too large'},413);const payload=z.union([createSchema,retireSchema]).parse(JSON.parse(raw));await ensureFoundingPilot();const db=database();const now=new Date().toISOString();
 const duplicate=await db.prepare('SELECT content FROM fee_policy_events WHERE actor=? AND idempotency_key=?').bind(user.id,payload.key).first();if(duplicate)return response({...JSON.parse(duplicate.content),duplicate:true});
 if(payload.type==='create'){
  validatePolicy(payload);const existing=(await db.prepare("SELECT * FROM fee_policies WHERE status='active' AND id!='founding-pilot-zero-v1' AND scope=? AND COALESCE(studio_id,'')=COALESCE(?, '') AND COALESCE(room_id,'')=COALESCE(?, '')").bind(payload.scope,payload.studioId||null,payload.roomId||null).all()).results as any[];
  if(existing.some(row=>intervalsOverlap(payload.effectiveFrom,payload.effectiveUntil,row.effective_from,row.effective_until||undefined)))return response({error:'This policy overlaps an active policy for the same scope'},409);
  const policy:FeePolicyRecord={id:'FEE-'+crypto.randomUUID(),scope:payload.scope,studioId:payload.studioId,roomId:payload.roomId,status:'active',effectiveFrom:payload.effectiveFrom,effectiveUntil:payload.effectiveUntil,revision:0,policy:{id:'',version:0,payer:payload.payer,musicianBps:payload.musicianBps,studioBps:payload.studioBps,basis:payload.basis,depositsExcluded:true,effectiveFrom:payload.effectiveFrom,source:'configured_policy'},createdAt:now,createdBy:user.id};policy.policy.id=policy.id;
  const result={ok:true,policy};await db.batch([db.prepare('INSERT INTO fee_policies(id,scope,studio_id,room_id,status,effective_from,effective_until,revision,content) VALUES(?,?,?,?,?,?,?,?,?)').bind(policy.id,policy.scope,policy.studioId||null,policy.roomId||null,policy.status,policy.effectiveFrom,policy.effectiveUntil||null,0,JSON.stringify(policy)),db.prepare('INSERT INTO fee_policy_events(id,policy_id,actor,event,idempotency_key,created_at,content) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),policy.id,user.id,'created',payload.key,now,JSON.stringify(result))]);return response(result);
 }
 if(payload.id==='founding-pilot-zero-v1')return response({error:'The founding-pilot fallback cannot be retired'},409);
 const row=await db.prepare('SELECT * FROM fee_policies WHERE id=?').bind(payload.id).first();if(!row)return response({error:'Fee policy not found'},404);if(row.revision!==payload.revision)return response({error:'This policy has changed. Refresh and try again.'},409);if(row.status!=='active')return response({error:'This policy is already retired'},409);
 const policy={...JSON.parse(row.content),status:'retired',revision:row.revision+1};const result={ok:true,policy};await db.batch([db.prepare('UPDATE fee_policies SET status=?,revision=revision+1,content=? WHERE id=? AND revision=?').bind('retired',JSON.stringify(policy),payload.id,payload.revision),db.prepare('INSERT INTO fee_policy_events(id,policy_id,actor,event,idempotency_key,created_at,content) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),payload.id,user.id,'retired',payload.key,now,JSON.stringify(result))]);return response(result);
}catch(error){const message=error instanceof z.ZodError?error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`).join('; '):error instanceof Error?error.message:'Unable to save fee policy';return response({error:message},error instanceof Fault?error.status:400)}}
