import React,{useMemo,useState} from 'react';
import {FlatList,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useRouter} from 'expo-router';
import {DESIGN_TOKENS} from '@sessions/product-core';
import {EmptyState,Field,LinkButton,Screen} from '../../src/native-ui';
import {StudioCard} from '../../src/product-components';
import {UAT_STUDIOS} from '../../src/uat-data';
import {useOnlineState} from '../../src/network';

const c=DESIGN_TOKENS.color;
const FILTERS=[['all','All'],['bookable','Bookable'],['rehearsal','Rehearsal'],['recording','Recording'],['drums','Drums'],['pa','PA'],['backup','Backup power']];
export default function SearchScreen(){
  const router=useRouter();const{online}=useOnlineState();const[query,setQuery]=useState('');const[filter,setFilter]=useState('all');const[minCapacity,setMinCapacity]=useState('');
  const visible=useMemo(()=>UAT_STUDIOS.filter(studio=>{const haystack=`${studio.name} ${studio.area} ${studio.category} ${studio.services.join(' ')} ${studio.equipment.join(' ')}`.toLowerCase();if(query&&!haystack.includes(query.toLowerCase()))return false;if(filter==='bookable'&&!studio.bookable)return false;if(filter==='backup'&&!studio.backupPower)return false;if(filter==='drums'&&!studio.equipment.some(v=>v.toLowerCase().includes('drum')))return false;if(filter==='pa'&&!studio.equipment.some(v=>v.toLowerCase()==='pa'))return false;if(['rehearsal','recording'].includes(filter)&&!studio.services.some(v=>v.toLowerCase().includes(filter)))return false;const capacity=Math.max(0,...studio.rooms.map(room=>room.capacity||0));if(Number(minCapacity)>0&&capacity<Number(minCapacity))return false;return true}),[filter,minCapacity,query]);
  return <Screen scroll={false} offline={!online} contentStyle={styles.root}><View style={styles.header}><View style={styles.top}><Text style={styles.title}>Search music spaces</Text><LinkButton onPress={()=>router.push('/planner')}>AI planner</LinkButton></View><Field label="Search" accessibilityLabel="Search studios, areas, equipment and services" value={query} onChangeText={setQuery} returnKeyType="search" autoCapitalize="none" placeholder="Studio, area, drums, PA…"/><Field label="Minimum group size" keyboardType="number-pad" value={minCapacity} onChangeText={setMinCapacity} placeholder="e.g. 6"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{FILTERS.map(([value,label])=><Pressable accessibilityRole="button" accessibilityState={{selected:filter===value}} key={value} onPress={()=>setFilter(value)} style={[styles.chip,filter===value&&styles.chipActive]}><Text style={[styles.chipText,filter===value&&styles.chipTextActive]}>{label}</Text></Pressable>)}</ScrollView></View><FlatList data={visible} keyExtractor={item=>item.id} renderItem={({item})=><StudioCard compact studio={item} onPress={()=>router.push(`/studio/${item.id}`)}/>} contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled" ListEmptyComponent={<EmptyState title="No matching rooms" body="Change the area, equipment, capacity or booking filter. AI can also turn a natural-language rehearsal brief into editable requirements."/>}/></Screen>;
}

const styles=StyleSheet.create({root:{paddingHorizontal:0},header:{paddingHorizontal:18,paddingTop:12,backgroundColor:c.canvas},top:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},title:{fontSize:27,fontWeight:'900',letterSpacing:-.8,color:c.ink},chips:{gap:8,paddingVertical:13,paddingRight:18},chip:{minHeight:44,paddingHorizontal:15,borderRadius:999,borderWidth:1,borderColor:c.line,backgroundColor:c.white,alignItems:'center',justifyContent:'center'},chipActive:{backgroundColor:c.ink,borderColor:c.ink},chipText:{fontSize:13,fontWeight:'800',color:c.ink},chipTextActive:{color:c.white},list:{paddingHorizontal:18,paddingTop:8,paddingBottom:110}});
