import type {MemberPlan,StudioMember,Registration} from './discovery';
import {type Room, type Booking, slotReason} from './domain';
import type {SettlementPricingSnapshot,AddOnLine} from './commerce';
import type {BookingSeries,LoyaltyCreditSetting,MembershipLedgerEntry} from './retention';
export type Source={title:string;url:string;checked:string;kind:'Official website'|'Official social profile'|'Public directory';note?:string};
export type PublicLocation={lat:number;lng:number;precision:'building'|'street'|'venue';address:string;source:Source};
export type StudioRoomAddOn={id:string;name:string;price:number;commissionable:boolean;available:boolean};
export type StudioRoom={id:string;name:string;price:number;capacity:number;open:number;close:number;days:number[];buffer:number;minimum:number;deposit?:number;addOns?:StudioRoomAddOn[];photos?:string[]};
export type StudioStatus='unclaimed'|'claimed'|'pending_verification'|'verified'|'bookable';
export type Studio={id:string;name:string;area:string;address:string;category:string;services:string[];description:string;website:string;phone:string;email:string;sources:Source[];status:StudioStatus;bookingEnabled:boolean;rooms:StudioRoom[];equipment:string;rules:string;location:{lat:number;lng:number}|null;publicLocation?:PublicLocation;revision:number;memberPlans?:MemberPlan[];updatedAt?:string;verifiedAt?:string;notice?:string;hidden?:boolean};
export type Staff={id:string;studioId:string;name:string;title:string;bio:string;skills:string;role:'manager'|'staff';status:'invited'|'active';inviteContact?:string;email?:string;public:boolean;joinedAt?:string};
export type Claim={id:string;studioId:string;applicant:string;name:string;role:string;phone:string;evidence:string;status:'pending'|'approved'|'rejected';code:string;createdAt:string;note?:string;reviewedAt?:string;reviewedBy?:string};
export type VerificationRequest={id:string;studioId:string;applicant:string;legalName:string;evidenceType:'official_channel'|'registration'|'premises';registrationNumber?:string;contactPhone:string;evidence:string;evidenceMediaId?:string;status:'pending'|'approved'|'rejected';createdAt:string;note?:string;reviewedAt?:string;reviewedBy?:string};
export type StudioBooking={id:string;studioId:string;roomId:string;roomName:string;customer:string;name:string;phone:string;date:string;start:number;duration:number;size:number;note:string;staffId:string;status:'requested'|'confirmed'|'completed'|'declined'|'cancelled';price:number;basePrice?:number;discount?:number;membershipId?:string;priority?:boolean;seriesId?:string;seriesIndex?:number;seriesCount?:number;loyaltyCreditCents?:number;pricing?:SettlementPricingSnapshot;addOns?:AddOnLine[];quotedAt?:string;createdAt:string};
export type SettlementStatus='awaiting_payment'|'proof_submitted'|'payment_declined'|'settled_off_platform'|'disputed'|'cancelled';
export type SettlementMethod='ecocash'|'bank_transfer'|'cash'|'other';
export type StudioSettlement={id:string;bookingId:string;studioId:string;customer:string;status:SettlementStatus;revision:number;pricing:SettlementPricingSnapshot;createdAt:string;updatedAt:string;proofMediaId?:string;proofMethod?:SettlementMethod;proofSubmittedAt?:string;proofNote?:string;declineReason?:string;settledAt?:string;settledMonth?:string;settledMethod?:SettlementMethod;settledBy?:string;disputeReason?:string;disputedAt?:string;resolutionNote?:string};
export type StudioInvoice={id:string;studioId:string;period:string;status:'issued';currency:'USD';gross:number;platformFee:number;studioNet:number;settlementIds:string[];issuedAt:string;issuedBy:string};
export type RegistryIssue={id:string;studioId:string;kind:'correction'|'suggestion'|'removal';text:string;source:string;status:'open'|'resolved';createdAt:string;reporter:string};
export type RegistryUser={id:string;displayName:string;email:string|null;phone:string|null;roles?:string[];method?:string;sessionId?:string};
export type RegistryState={memberships?:StudioMember[];membershipLedger?:MembershipLedgerEntry[];loyaltyCreditSetting?:LoyaltyCreditSetting;bookingSeries?:BookingSeries[];registrations?:Registration[];verifications?:VerificationRequest[];settlements?:StudioSettlement[];invoices?:StudioInvoice[];studios:Studio[];staff:Staff[];claims:Claim[];bookings:StudioBooking[];issues:RegistryIssue[];managedIds:string[];ownerIds:string[];invitations:Staff[];myStaff:Staff[];occupancy?:Pick<StudioBooking,'studioId'|'roomId'|'date'|'start'|'duration'|'status'>[];operator:boolean;user:RegistryUser|null};
const checked='2026-08-31';
const source=(title:string,url:string,kind:Source['kind']='Official website',note?:string):Source=>({title,url,kind,checked,note});
const seed=(id:string,name:string,area:string,address:string,category:string,services:string[],description:string,sources:Source[],contact:Partial<Pick<Studio,'website'|'phone'|'email'|'notice'>>={}):Studio=>({id,name,area,address,category,services,description,sources,website:'',phone:'',email:'',...contact,status:'unclaimed',bookingEnabled:false,rooms:[],equipment:'',rules:'',location:null,revision:0});
export const studioSeeds:Studio[]=[
 seed('onevibe-studiox','OneVibe Studiox','Harare CBD','Room 707, 7th Floor, Dolphin House, corner Kwame Nkrumah Avenue & Leopold Takawira Street, Harare','Rehearsal studio',['Rehearsal','Recording','Lessons','Podcasts'],'A multimedia studio advertising rehearsal rooms, recording, instrumental lessons and voice-over services.',[source('OneVibe contact page','https://onevibestudiox.com/contacts/'),source('OneVibe studio profile','https://soundbetter.com/profiles/724967-onevibe-studiox','Official social profile')],{website:'https://onevibestudiox.com/',phone:'+263716852722',email:'bookings@onevibestudiox.com'}),
 seed('soundlab-rehearsal','SoundLab Rehearsal Studio','Harare CBD','Room 714, 7th Floor, Dolphin House, corner Takawira & Kwame Nkrumah, Harare','Rehearsal studio',['Rehearsal','Live sessions'],'A rehearsal studio advertising space for bands, choirs and artists at Dolphin House.',[source('SoundLab business profile','https://www.instagram.com/soundlabrehearsal/','Official social profile'),source('SoundLab Facebook page','https://www.facebook.com/p/SoundLab-Rehearsal-Studio-61572042416671/','Official social profile')],{website:'https://www.instagram.com/soundlabrehearsal/',phone:'+263780094433'}),
 seed('kulcha-houz-studio-b','Kulcha Houz · Studio B','Harare','47 Lawley Avenue, Harare','Rehearsal studio',['Rehearsal','Recording'],'A rehearsal and recording location listed on Lawley Avenue. Branch details still need confirmation by its operator.',[source('Kulcha Houz website','https://www.kulchahouzstudios.com/'),source('OneVibe Harare studio guide','https://onevibestudiox.com/top-rehearsal-studios-in-harare-zimbabwe-2026-guide/','Public directory','Address is from a third-party guide; confirm before visiting.')],{website:'https://www.kulchahouzstudios.com/',phone:'+263772225551'}),
 seed('bridgenorth-studios','Bridgenorth Studios','Greendale','Bridgenorth Road, Greendale, Harare','Recording studio',['Recording','Mixing','Residential'],'A recording studio with two studios and residential facilities, represented in the Miloco studio directory.',[source('Bridgenorth introduction','https://milocostudios.com/studios/bridgenorth-studios/intro/'),source('Bridgenorth location','https://milocostudios.com/studios/bridgenorth-studios/location-and-map/'),source('Bridgenorth booking contact','https://milocostudios.com/studios/bridgenorth-studios/contact-us/')],{website:'https://milocostudios.com/studios/bridgenorth-studios/intro/',email:'bookings@miloco.co.uk',notice:'Public booking contact is Miloco. Rehearsal hire has not been confirmed.'}),
 seed('monolio-studios','Monolio Studios','Harare','Harare, Zimbabwe · street address awaiting confirmation','Recording studio',['Recording','Music production'],'An independent Harare recording studio publicly associated with musician and producer Clive “Mono” Mukundu.',[source('Mono Mukundu studio profile','https://www.youtube.com/@Monomukundu/shorts','Official social profile'),source('Monolio artist profile','https://www.reverbnation.com/monoliostudio/song/30768004-mono-mukundu-gwenyagitare','Official social profile')],{website:'https://www.youtube.com/@Monomukundu',notice:'Street address and current public booking contact need owner confirmation.'}),
 seed('jp-studios','JP Studios','Harare','31 Herbert Chitepo Avenue, Harare','Recording studio',['Recording','Music production'],'A music recording studio listed publicly in Harare. Contact and location information are awaiting owner confirmation.',[source('JP Studios business page','https://www.facebook.com/jpstudiosmtm/','Official social profile','Source spells the street “Hebert Chitepo”. Current address not independently verified.')],{website:'https://www.facebook.com/jpstudiosmtm/',phone:'+263782819877',email:'jahpstudios@gmail.com'}),
 seed('zimbabwe-college-of-music','Zimbabwe College of Music','Harare CBD','C3 Civic Centre, Rotten Row, Harare','Music institution',['Recording','Music education'],'A music college with an advertised recording studio. Public hire terms and access require confirmation with the college.',[source('College contact page','https://zcm.co.zw/contact-us/'),source('College recording studio announcement','https://www.facebook.com/www.zcm.co.zw/posts/this-is-the-zimbabwe-college-of-music-recording-studio-for-more-information-cont/859826352825388/','Official social profile')],{website:'https://zcm.co.zw/',email:'registry@zcm.co.zw',phone:'+263242749076'}),
 seed('chillspot-recordz','Chillspot Recordz','Mbare','Mbare, Harare · exact visitor entrance awaiting confirmation','Recording studio',['Recording','Music production'],'A Harare recording studio associated with Zimdancehall. Confirm visitor arrangements directly before travelling.',[source('Chillspot business listing','https://www.glartent.com/ZW/Harare/567605379951479/CHILL-SPOT-Recordz','Public directory'),source('Fantan Chillspot official page','https://www.facebook.com/fantanchillspot/videos/christmas-day-2025-was-one-for-the-books-the-chillspot-family-would-like-to-than/4207535849561433/','Official social profile')],{website:'https://www.facebook.com/fantanchillspot/',notice:'Neighbourhood only. A public directory address has not been verified as a visitor entrance.'}),
 seed('spirit-media','Spirit Media','Harare','Harare, Zimbabwe · street address awaiting confirmation','Recording studio',['Recording','Music production'],'A Harare media organisation whose website lists recording studio and music production services.',[source('Spirit Media website','https://spiritmedia.co.zw/'),source('Spirit Media contact page','https://www.spiritmedia.co.zw/pages/contact.php')],{website:'https://spiritmedia.co.zw/',phone:'+263772739442',email:'info@spiritmedia.co.zw'}),
 seed('metro-studios','Metro Studios / Metro Systems','Msasa','9 Williams Way, Msasa, Harare','Recording studio',['Recording','PA systems'],'A publicly listed studio and sound-systems business in Msasa. Its current recording offer and address need reconfirmation.',[source('Metro Systems business directory','https://thedirectory.co.zw/company.cfm?companyid=2942','Public directory'),source('Metro Studios address listing','https://www.africanadvice.com/1189739/Companies_And_Businesses/Zimbabwe/Metro_Studios/','Public directory')],{notice:'Directory information may be stale. Current operation and address need confirmation.'}),
 seed('loft-events-studios','Loft Events & Studios','Avenues','6th Street & Selous Avenue, Harare','Rehearsal studio',['Rehearsal'],'A creative space advertising music rehearsal facilities in the Avenues area. Entrance and services need operator confirmation.',[source('Loft rehearsal announcement','https://www.instagram.com/loft_events_and_studios_/reel/DcNjtOcMKaE/','Official social profile')],{website:'https://www.instagram.com/loft_events_and_studios_/'}),
 seed('znfpc-audio-visual','ZNFPC Audio Visual Unit','Southerton','Spilhaus Centre, 1 Swissway, Southerton, Harare','Production facility',['Audio production','Video production'],'An institutional audio-visual production facility at the ZNFPC headquarters. Music rehearsal access has not been established.',[source('ZNFPC Audio Visual Unit','https://www.znfpc.org.zw/audio-visual-unit/')],{website:'https://www.znfpc.org.zw/audio-visual-unit/',notice:'Institutional production facility; do not assume public rehearsal hire is available.'})
];
// Public-source locations are discovery aids, never owner-confirmed entrance pins.
// Bind each to the researched address so an address correction invalidates stale geometry.
const publicPins:Record<string,Omit<PublicLocation,'address'>>={
 'onevibe-studiox':{lat:-17.829165,lng:31.045351,precision:'building',source:source('Dolphin House building coordinates','https://skyscraperpage.com/forum/showthread.php?p=10620319','Public directory','Building-level point, corroborated against a public business geolocation listing. Room 707 and its entrance are not verified.')},
 'soundlab-rehearsal':{lat:-17.829165,lng:31.045351,precision:'building',source:source('Dolphin House building coordinates','https://skyscraperpage.com/forum/showthread.php?p=10620319','Public directory','Shared building point, not the Room 714 entrance. Confirm access with the studio.')},
 'bridgenorth-studios':{lat:-17.7956655,lng:31.1331544,precision:'street',source:source('Miloco public location and map','https://milocostudios.com/studios/bridgenorth-studios/location-and-map/','Official website','The representative’s map link resolves to Bridgenorth Road, not a numbered property. This is a street-level approximation, not the studio entrance.')},
 'zimbabwe-college-of-music':{lat:-17.833014682,lng:31.037836921,precision:'venue',source:source('College of Music public Waze listing','https://www.waze.com/live-map/directions/college-of-music-harare?to=place.w.20317782.203439961.3805353','Public directory','Public campus point near the college’s listed Civic Centre address. The recording-room entrance and public hire access are unconfirmed.')}
};
for(const s of studioSeeds){if(publicPins[s.id])s.publicLocation={...publicPins[s.id],address:s.address};}
export const kulchaAddressCorrection={id:'kulcha-houz-studio-b',previous:'47 Lawley Avenue, Harare',address:'47 Lawley Avenue, Belvedere, Harare',area:'Belvedere',source:source('Kulcha Houz official business profile','https://www.facebook.com/p/Kulcha-Houz-Studio-100068628488954/','Official social profile','The studio’s public profile lists the Belvedere address. Visitor entrance still needs confirmation.')};
const kulcha=studioSeeds.find(s=>s.id===kulchaAddressCorrection.id)!;
Object.assign(kulcha,{address:kulchaAddressCorrection.address,area:kulchaAddressCorrection.area});
kulcha.sources=[kulchaAddressCorrection.source,...kulcha.sources];
export function studioPin(s:Studio,includeApproximate=true){
 if(s.location)return {...s.location,approximate:false,precision:'entrance' as const};
 const p=s.publicLocation;
 return includeApproximate&&p&&p.address===s.address?{...p,approximate:true}:null;
}
export function pinDescription(s:Studio){const p=studioPin(s);return !p?'Map search · no researched coordinates':p.approximate?`Approximate ${p.precision} location · entrance unconfirmed`:'Owner-confirmed entrance coordinates';}
export const emptyRegistry:RegistryState={studios:studioSeeds,staff:[],claims:[],verifications:[],settlements:[],invoices:[],bookings:[],issues:[],managedIds:[],ownerIds:[],invitations:[],myStaff:[],operator:false,user:null};
export const mapQuery=(s:Studio)=>{const p=studioPin(s);return p?`${p.lat},${p.lng}`:`${s.name}, ${s.address.split('·')[0].trim()}`;};
export const mapUrl=(s:Studio)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(mapQuery(s))}`;
export function asRoom(s:Studio,r:StudioRoom):Room{return {id:r.id,name:r.name,venue:s.name,area:s.area,description:s.description,category:s.category,price:r.price,capacity:r.capacity,equipment:[],backup:false,parking:false,accessible:false,instant:false,verified:['verified','bookable'].includes(s.status),active:s.bookingEnabled&&s.status==='bookable',image:r.photos?.[0]||'',photos:r.photos||[],minimum:r.minimum,deposit:r.deposit||0,buffer:r.buffer,cancellation:24,hours:Object.fromEntries(Array.from({length:7},(_,i)=>[String(i),r.days.includes(i)?[r.open,r.close]:null])),rules:s.rules,address:s.address,contact:s.phone,checkin:'Arrange with the studio',restricted:'',verification:['verified','bookable'].includes(s.status)?'Operations-verified studio':'Owner-managed profile'};}
export function registrySlotReason(s:Studio,r:StudioRoom,date:string,start:number,duration:number,bookings:StudioBooking[]){const occupied=bookings.filter(b=>b.studioId===s.id&&!['cancelled','declined'].includes(b.status)).map(b=>({...b,status:'confirmed'}) as unknown as Booking);return slotReason(asRoom(s,r),date,start,duration,occupied,[]);}
