import React from 'react';
import {ScrollView,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {DESIGN_TOKENS} from '@sessions/product-core';
import {Body,Card,Eyebrow,EmptyState,Notice,PrimaryButton,Screen,Section,Small,Title} from '../../src/native-ui';
import {StudioArtwork,money} from '../../src/product-components';
import {UAT_DATA_NOTICE,UAT_STUDIOS} from '../../src/uat-data';
import {useOnlineState} from '../../src/network';

const c=DESIGN_TOKENS.color;
export default function StudioDetail(){const{id}=useLocalSearchParams();const router=useRouter();const insets=useSafeAreaInsets();const{online}=useOnlineState();const studio=UAT_STUDIOS.find(item=>item.id===id);if(!studio)return <Screen><EmptyState title="Studio unavailable" body="This listing is not present in the current Sessions projection."/></Screen>;const capacity=Math.max(0,...studio.rooms.map(room=>room.capacity||0));return <Screen scroll={false} offline={!online}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{paddingBottom:120}}><StudioArtwork studio={studio}/><View style={styles.body}><Eyebrow>{studio.bookable?'BOOKABLE THROUGH SESSIONS':'PROFILE ONLY'}</Eyebrow><Title>{studio.name}</Title><Body style={{marginTop:5}}>{studio.area}, Harare · {studio.category}</Body><View style={styles.summary}><View style={styles.summaryCell}><Eyebrow>FROM</Eyebrow><Text style={styles.value}>{studio.rate?`${money(studio.rate)}/hr`:'—'}</Text></View><View style={styles.summaryCell}><Eyebrow>CAPACITY</Eyebrow><Text style={styles.value}>{capacity||'—'}</Text></View><View style={[styles.summaryCell,{borderRightWidth:0}]}><Eyebrow>RATING</Eyebrow><Text style={styles.value}>{studio.rating?`★ ${studio.rating}`:'New'}</Text></View></View><Section eyebrow="ROOM FIT" title="Equipment & practical details"><Card><Text style={styles.label}>Included / known equipment</Text><Body>{studio.equipment.join(' · ')||'Not published'}</Body><View style={{height:12}}/><Text style={styles.label}>Power</Text><Body>{studio.backupPower?'Backup power reported':'Backup power not reported'}</Body>{studio.nextAvailable?<><View style={{height:12}}/><Text style={styles.label}>Next suitable UAT slot</Text><Body>{studio.nextAvailable}</Body></>:null}</Card></Section>{studio.rooms.length?<Section eyebrow="TIME INVENTORY" title="Rooms">{studio.rooms.map(room=><Card key={room.id}><View style={styles.roomRow}><View style={{flex:1}}><Text style={styles.roomName}>{room.name}</Text><Small>Up to {room.capacity} people · {room.equipment.join(' · ')}</Small></View><Text style={styles.roomPrice}>{money(room.price)}/hr</Text></View></Card>)}</Section>:null}<Section eyebrow="TRUST & TERMS" title="Know before you book"><Card><Body>Provider verification, house rules, cancellation policy, check-in instructions and accessibility should come from canonical provider data. This UAT fixture intentionally does not invent missing terms.</Body></Card></Section><Notice>{UAT_DATA_NOTICE}</Notice></View></ScrollView><View style={[styles.sticky,{paddingBottom:Math.max(insets.bottom,12)}]}><PrimaryButton disabled={!studio.bookable||!online} onPress={()=>router.push(`/booking/${studio.id}`)}>{!online?'Connect to check availability':studio.bookable?'Choose a valid time':'Not bookable yet'}</PrimaryButton></View></Screen>}
const styles=StyleSheet.create({body:{padding:18},summary:{marginTop:18,borderRadius:18,borderWidth:1,borderColor:c.line,backgroundColor:c.white,flexDirection:'row'},summaryCell:{flex:1,padding:12,borderRightWidth:StyleSheet.hairlineWidth,borderRightColor:c.line},value:{fontSize:14,fontWeight:'850',color:c.ink,marginTop:4},label:{fontSize:12,fontWeight:'850',color:c.ink,marginBottom:3},roomRow:{flexDirection:'row',alignItems:'center',gap:12},roomName:{fontSize:15,fontWeight:'850',color:c.ink,marginBottom:3},roomPrice:{fontSize:14,fontWeight:'850',color:c.ink},sticky:{position:'absolute',left:0,right:0,bottom:0,paddingHorizontal:18,paddingTop:10,backgroundColor:c.white,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:c.line}});
