import React from 'react';
import {Alert,Share,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {DESIGN_TOKENS} from '@sessions/product-core';
import {Body,Card,Eyebrow,Notice,PrimaryButton,Screen,SecondaryButton,Section,Small,Title} from '../../src/native-ui';
import {UAT_SESSIONS} from '../../src/uat-data';
import {useOnlineState} from '../../src/network';

const c=DESIGN_TOKENS.color;
export default function SessionDetail(){const{id}=useLocalSearchParams();const router=useRouter();const{online}=useOnlineState();const item=UAT_SESSIONS.find(value=>value.id===id);if(!item)return <Screen><Title>Session unavailable</Title></Screen>;const cancel=()=>Alert.alert('Cancel this session?','Cancellation requires an authenticated participant, fresh server state, the applicable policy and a server-confirmed result. This UAT preview does not mutate the booking.');return <Screen offline={!online}><Eyebrow>{item.reference}</Eyebrow><Title>{item.studio}</Title><Text style={styles.status}>{item.status}</Text><Section eyebrow="WHEN" title={`${item.date} · ${item.time}`}><Card><Body>{item.duration} · {item.room}</Body></Card></Section><Section eyebrow="NEXT ACTIONS" title="Keep rehearsal moving"><View style={{gap:9}}><PrimaryButton onPress={()=>router.push(`/booking/${item.studioId}`)}>Book this room again</PrimaryButton><SecondaryButton onPress={()=>router.push(`/booking/${item.studioId}?repeat=weekly`)}>Start a weekly repeat</SecondaryButton><SecondaryButton onPress={()=>Share.share({message:`Sessions ${item.reference}: ${item.studio}, ${item.date} at ${item.time}, ${item.room}`})}>Share session details</SecondaryButton></View></Section><Section eyebrow="OFFLINE REFERENCE" title="Your booking reference"><Card><Text selectable style={styles.reference}>{item.reference}</Text><Small style={{marginTop:5}}>A compact confirmed reference should remain useful when connectivity is poor. Live changes still require the server.</Small></Card></Section><Notice>Calendar export, entry instructions, receipts and communication must use canonical confirmed booking data. This fixture does not invent access codes, payment state or venue instructions.</Notice><View style={{marginTop:20}}><SecondaryButton onPress={cancel}>Review cancellation options</SecondaryButton></View></Screen>}
const styles=StyleSheet.create({status:{alignSelf:'flex-start',marginTop:10,paddingHorizontal:9,paddingVertical:5,borderRadius:999,backgroundColor:c.successSurface,fontSize:10,fontWeight:'900',textTransform:'uppercase',color:c.success},reference:{fontSize:18,fontWeight:'900',letterSpacing:1,color:c.ink}});
